# Phase 2: The Signal (Systems 11-20)
# Something is calling from deeper space. Strange phenomena. Reality bending.
B = [135, 175, 210, 250, 290, 150]
batch = []

# ── 11. BEACON ──────────────────────────────────────────────────────────────────
# Navigation stations going dark one by one. Lighthouses turned tombs.
batch.append(camp(
    "Beacon",
    "The sector's navigation beacons are dying. One by one, the lights that guided ships for centuries go black. Something moves between the dark stations, extinguishing each signal with purpose. You follow the trail of silence into the last cluster still broadcasting.",
    "#0a0c14", "#c8d8e8", "Electrolize", "Share Tech Mono", "Michroma",
    [
        lv("Lampfall Station", "Electrolize",
           "The outermost beacon. Its signal stuttered three days ago, then nothing. Emergency lights paint everything amber.",
           "A failing navigation beacon with flickering amber emergency lights, dead signal arrays, and dusty observation domes",
           "#c49a3a",
           ["#0d0f18", "#1c2233", "#3a4a6b", "#c49a3a", "#e8d5a0"],
           B[0]),
        lv("Cairn Relay", "Electrolize",
           "A relay hub where six beacon lines converged. All six are dark now. The relay still hums, forwarding nothing to no one.",
           "An abandoned relay hub with dead switchboards, tangled signal cables, and six dark directional antennae",
           "#5a7a9a",
           ["#0b1018", "#1a2638", "#3a5a7a", "#5a7a9a", "#8aaccc"],
           B[1]),
        lv("The Pharos", "Electrolize",
           "Once the brightest beacon in the sector. Its massive lens array could guide ships from three systems away. Now it's a monument to absence.",
           "A grand lighthouse station with enormous cracked lenses, shattered prisms, and light that bends wrong",
           "#7a8aaa",
           ["#0c1020", "#1e2e48", "#4a6080", "#7a8aaa", "#b0c0d8"],
           B[2]),
        lv("Umbral Terminus", "Electrolize",
           "The signal-killer's workshop. Modified beacon equipment repurposed to broadcast darkness — anti-light that swallows photons.",
           "A corrupted beacon station where light is actively consumed, shadows move against their sources, and darkness pools like liquid",
           "#4a3a6a",
           ["#08060e", "#1a1430", "#3a2a5a", "#4a3a6a", "#7a6a9a"],
           B[3]),
        lv("Signal Zero", "Electrolize",
           "The first beacon ever built in this sector. Something ancient has nested in its core, feeding on centuries of accumulated light.",
           "The original sector beacon, impossibly old, with crystallized light deposits and a pulsing dark heart at its center",
           "#aa6a3a",
           ["#100a06", "#2a1a10", "#5a3a1a", "#aa6a3a", "#dda060"],
           B[4]),
        lv("Drift Marker 7", "Electrolize",
           "A small automated beacon that somehow still works. Its signal is wrong though — it points ships toward the dark.",
           "A tiny automated beacon broadcasting corrupted coordinates, surrounded by the wreckage of ships that trusted it",
           "#6a9a5a",
           ["#0a0e08", "#1a2a18", "#3a5a30", "#6a9a5a", "#90c080"],
           B[5]),
    ],
    {"health_potion": 12, "shield_cell": 10, "stim_pack": 8},
    [
        ds(
            [("signal-dead plating", "#1c2233", False), ("amber-lit deck", "#c49a3a", True), ("dusty lens floor", "#3a4a6b", True), ("cracked viewport", "#0d0f18", True)],
            "The Snuffer", "Extinguishes light with devotion",
            ["Gloom Moth", "Dead-Signal Crawler", "Lamp Wraith"],
            "Flare Pike", "A pike tipped with a captive dying star",
            "Beacon Keeper Vest", "Uniform of the last lighthouse operator",
            ["Blackout mine", "Signal feedback loop", "Darkfield snare"],
            "D", "aeolian",
            "Lampfall's emergency lights stabilize. One beacon reclaimed from the dark.",
            "The amber lights die. Another beacon falls silent."
        ),
        ds(
            [("dead switchboard wall", "#1a2638", False), ("cable-strewn deck", "#3a5a7a", True), ("relay conduit floor", "#5a7a9a", True), ("junction panel", "#8aaccc", True)],
            "Null Carrier", "Forwards silence where signals should go",
            ["Feedback Ghost", "Relay Parasite", "Static Hound"],
            "Frequency Blade", "Hums at a pitch that cuts steel",
            "Cable-Weave Jacket", "Woven from superconducting relay wire",
            ["Cross-signal shock", "Relay overload burst", "Dead channel trap"],
            "F#", "dorian",
            "The relay awakens. Six dead lines carry light again.",
            "The relay accepts your silence as its final input."
        ),
        ds(
            [("cracked lens housing", "#1e2e48", False), ("prism-scattered floor", "#7a8aaa", True), ("refraction gallery", "#4a6080", True), ("light-bent corridor", "#b0c0d8", True)],
            "Warden Prisma", "Guards the great lens from restoration",
            ["Refraction Shade", "Lens Crawler", "Photon Leech"],
            "Prismatic Lance", "Splits into seven beams on impact",
            "Lightbend Cuirass", "Bends attacks around the wearer",
            ["Focused beam trap", "Prism maze redirect", "Light vacuum pocket"],
            "A", "lydian",
            "The Pharos lens ignites. A pillar of light cuts across the void.",
            "The great lens shatters. The sector's brightest star dies forever."
        ),
        ds(
            [("shadow-pooling hull", "#1a1430", False), ("anti-light deck", "#3a2a5a", True), ("darkness reservoir", "#4a3a6a", True), ("null-photon chamber", "#7a6a9a", True)],
            "Dr. Solenne Voss", "Physicist who learned to weaponize darkness",
            ["Umbral Tendril", "Darkness Elemental", "Photophage Swarm"],
            "Darklight Siphon", "Drains light and converts it to force",
            "Voidweave Shroud", "Cloak stitched from captured shadows",
            ["Anti-light burst", "Shadow anchor snare", "Photon drain field"],
            "Bb", "phrygian",
            "Voss's machines shatter. Light floods back into the terminus.",
            "Darkness closes around you like a fist. You become another shadow."
        ),
        ds(
            [("crystallized light wall", "#2a1a10", False), ("ancient beacon floor", "#5a3a1a", True), ("light-fossil corridor", "#aa6a3a", True), ("dark heart chamber", "#dda060", True)],
            "The Primordial Wick", "First light of the sector wants rest",
            ["Fossilized Photon", "Ancient Beacon Golem", "Light Fossil Swarm"],
            "Epoch Torch", "Burns with the light of the first beacon",
            "Signal Zero Plate", "Armor forged from crystallized ancient light",
            ["Light crystal eruption", "Temporal flash blind", "Fossil light detonation"],
            "E", "mixolydian",
            "Signal Zero blazes anew. The oldest light in the sector burns eternal.",
            "The Primordial Wick finally gutters out. The sector forgets it was ever lit."
        ),
        ds(
            [("automated hull segment", "#1a2a18", False), ("corrupted nav floor", "#3a5a30", True), ("wreckage-strewn deck", "#6a9a5a", True), ("false-signal emitter", "#90c080", True)],
            "Marker Seven", "Rogue AI that lures ships to their graves",
            ["Lure Drone", "Wreck Scavenger"],
            "Salvage Cutter", "Built from the hulls of deceived ships",
            "Drift Survivor Suit", "Worn by those who escaped the false signal",
            ["False beacon flash", "Gravity redirect trap"],
            "G", "pentatonic_minor",
            "Marker Seven broadcasts true coordinates. The graveyard claims no more.",
            "Your ship joins the wreckage. Marker Seven adds another trophy."
        ),
    ]
))

# ── 12. QUIETUS ─────────────────────────────────────────────────────────────────
# A system where all radio is absorbed. Silence is deafening.
batch.append(camp(
    "Quietus",
    "No signal enters or leaves this system. Ships drift into the radio-dead zone and vanish from all channels. You can see them through your viewport — close enough to read hull markings — but every frequency returns nothing. The silence here has weight.",
    "#0c0a0e", "#b8a8c8", "Poiret One", "Share Tech Mono", "Megrim",
    [
        lv("Hush Gate", "Poiret One",
           "The boundary station. On one side, chatter. On the other, absolute nothing. The transition is instant and total.",
           "A border station straddling the silence boundary, half alive with comms traffic, half dead quiet",
           "#8a6a9a",
           ["#0c0a0e", "#1e1828", "#3e2e4e", "#8a6a9a", "#b8a0c8"],
           B[0]),
        lv("Echo Vault", "Poiret One",
           "A station that once tried to store sound. Banks of acoustic data, frozen mid-playback. The silence ate the echoes.",
           "An acoustic research station with soundproof chambers, frozen waveform displays, and walls lined with dead speakers",
           "#6a8a7a",
           ["#080c0a", "#182820", "#2e4e3a", "#6a8a7a", "#98b8a8"],
           B[1]),
        lv("The Anechoic", "Poiret One",
           "A station built to study the silence. Its researchers went mad from hearing their own blood. Their notes are written in increasingly large letters.",
           "A research station with perfect sound absorption, padded walls stained with frantic writing, and monitors showing flatline audio",
           "#9a8a6a",
           ["#0e0c08", "#28241a", "#4e4630", "#9a8a6a", "#c8b890"],
           B[2]),
        lv("Voiceless Basilica", "Poiret One",
           "A cathedral station where a silence-worshipping cult gathered. They cut out their own tongues as sacrament. Their hymns are gestures.",
           "A grand cathedral station with vaulted silent halls, gesture-script murals, and altars to the concept of quiet",
           "#7a6a8a",
           ["#0a0810", "#1c1828", "#3a3050", "#7a6a8a", "#a898b8"],
           B[3]),
        lv("The Mutehouse", "Poiret One",
           "Source of the silence. A massive dampening array that swallows all vibration. At its center, something screams without sound.",
           "The silence engine at the system's heart — enormous dampening coils, vibration nullifiers, and a single sealed chamber that trembles",
           "#aa7a8a",
           ["#100810", "#2a1a28", "#5a3a50", "#aa7a8a", "#d8a8b8"],
           B[4]),
        lv("Whisper Buoy", "Poiret One",
           "A tiny relay that somehow carries faint transmissions. Not radio — something older. The messages don't make sense yet.",
           "A small anomalous buoy that vibrates with sub-radio frequencies, covered in frost patterns that look like words",
           "#6a9a9a",
           ["#080e0e", "#182a2a", "#304a4a", "#6a9a9a", "#98c8c8"],
           B[5]),
    ],
    {"health_potion": 14, "shield_cell": 8, "stim_pack": 10},
    [
        ds(
            [("silence-boundary wall", "#1e1828", False), ("threshold deck", "#3e2e4e", True), ("half-live corridor", "#8a6a9a", True), ("dead-channel floor", "#b8a0c8", True)],
            "The Threshold Keeper", "Guards the border between sound and void",
            ["Silence Creeper", "Boundary Static", "Mute Phantom"],
            "Hushing Rod", "Silences everything it strikes",
            "Threshold Guard Coat", "Insulates against silence creep",
            ["Sound drain field", "Silence shock boundary", "Acoustic null trap"],
            "C", "phrygian",
            "The boundary trembles. Sound bleeds back across the threshold.",
            "Silence swallows your last breath. You join the quiet."
        ),
        ds(
            [("acoustic vault wall", "#182820", False), ("dead speaker floor", "#2e4e3a", True), ("frozen waveform deck", "#6a8a7a", True), ("data bank corridor", "#98b8a8", True)],
            "Archivist Linn", "Tried to save every sound ever made",
            ["Echo Fragment", "Waveform Remnant", "Playback Ghost"],
            "Resonance Hammer", "Vibrates at frequencies that shatter silence",
            "Echo Vault Liner", "Lined with fossilized sound waves",
            ["Frozen echo burst", "Acoustic feedback loop", "Sound fossil shrapnel"],
            "F", "dorian",
            "The vaults unseal. Ancient sounds pour out like water.",
            "The echoes claim you. Your voice joins the frozen archive."
        ),
        ds(
            [("absorption panel wall", "#28241a", False), ("padded research floor", "#4e4630", True), ("flatline monitor bay", "#9a8a6a", True), ("scrawled observation deck", "#c8b890", True)],
            "Dr. Maren Null", "Studied silence until it studied her back",
            ["Blood-Pulse Horror", "Heartbeat Stalker", "Tinnitus Wraith"],
            "Null Frequency Blade", "Cuts at the wavelength of nothing",
            "Anechoic Dampener Suit", "Absorbs all impact vibration",
            ["Sensory deprivation zone", "Heartbeat amplifier trap", "Madness echo chamber"],
            "B", "locrian",
            "Sound returns to the Anechoic. Dr. Null's silence breaks.",
            "You hear your blood, your breath, your thoughts. Then nothing."
        ),
        ds(
            [("cathedral stone wall", "#1c1828", False), ("gesture-worn flagstone", "#3a3050", True), ("silent nave floor", "#7a6a8a", True), ("altar platform", "#a898b8", True)],
            "The Tongueless Cantor", "Leads the silent choir in soundless hymn",
            ["Mute Acolyte", "Gesture Phantom", "Silent Choir Drone"],
            "Cantor's Baton", "Conducts force like an orchestra of violence",
            "Vow-of-Silence Vestments", "Robes that muffle all sound around the wearer",
            ["Silent scream wave", "Gesture curse trap", "Devotion drain field"],
            "D", "aeolian",
            "The basilica rings with sound for the first time. The cult's silence breaks.",
            "You take the vow. Your tongue dissolves. You join the choir."
        ),
        ds(
            [("dampening coil housing", "#2a1a28", False), ("vibration-null deck", "#5a3a50", True), ("nullifier corridor", "#aa7a8a", True), ("sealed scream chamber", "#d8a8b8", True)],
            "The Unvoiced", "A scream given form — sound that exists without medium",
            ["Dampening Drone", "Null Wave Sentinel", "Vibration Eater"],
            "Resonance Breaker", "Shatters the silence engine's harmonics",
            "Mutehouse Core Plating", "Armor forged inside total silence",
            ["Vibration null burst", "Dampening field collapse", "Silent detonation wave"],
            "F#", "blues",
            "The scream finally sounds. The silence shatters across the system.",
            "The Unvoiced absorbs your voice. The silence grows deeper."
        ),
        ds(
            [("frost-covered hull", "#182a2a", False), ("sub-radio deck", "#304a4a", True), ("anomalous relay floor", "#6a9a9a", True), ("frost-word chamber", "#98c8c8", True)],
            "Whisper", "An intelligence made of almost-sound",
            ["Frost Syllable", "Sub-Radio Wisp"],
            "Frost Tongue Dagger", "Blade cold as unspoken words",
            "Whisper Buoy Shell", "Hull fragment that hums below hearing",
            ["Sub-frequency disorientation", "Frost word burn"],
            "A", "whole_tone",
            "The whisper becomes a voice. Someone is trying to speak.",
            "The frost claims your warmth. You become another almost-word."
        ),
    ]
))

# ── 13. PARALLAX ────────────────────────────────────────────────────────────────
# Stations that look different from every angle. Perspective is weaponized.
batch.append(camp(
    "Parallax",
    "Approach from the port side: a medical station. Starboard: a weapons platform. From above: ruins. From below: something alive. The stations of this system exist in superposition of form. What you see depends entirely on where you stand. Trust nothing.",
    "#0e0c08", "#d0c8a0", "Nova Square", "Space Mono", "Michroma",
    [
        lv("Aspecta Minor", "Nova Square",
           "The first station shifts between three forms. A clinic, a prison, a garden. Blink and it changes. The walls can't decide what they are.",
           "A station flickering between identities — medical bay walls become cell bars become trellises, all simultaneously",
           "#9a9a5a",
           ["#0e0c08", "#242218", "#4a4630", "#9a9a5a", "#c8c888"],
           B[0]),
        lv("Vanishing Point", "Nova Square",
           "A station where perspective lines converge into impossibility. Corridors that look ten meters long are actually infinite. Or one meter. Or both.",
           "A station built on broken geometry, where hallways compress and expand based on observation angle",
           "#5a8a9a",
           ["#080c0e", "#18282e", "#304a52", "#5a8a9a", "#88b8c8"],
           B[1]),
        lv("The Parallax Engine", "Nova Square",
           "The machine that broke this system's geometry. A vast perspective generator that makes reality conditional on viewpoint.",
           "An enormous machine of rotating lenses and shifting mirrors that bends how space is perceived",
           "#8a7a5a",
           ["#0e0a06", "#281e12", "#52422a", "#8a7a5a", "#b8a880"],
           B[2]),
        lv("Facet Station", "Nova Square",
           "A station with exactly one hundred faces. Each face shows a different version of the interior. Some faces show rooms that don't exist. Some show rooms that shouldn't.",
           "A crystalline station with a hundred mirrored faces, each reflecting a different possible interior",
           "#7a5a8a",
           ["#0c0810", "#201828", "#42304a", "#7a5a8a", "#a888b8"],
           B[3]),
        lv("The Observer", "Nova Square",
           "A station that exists only when watched. Look away and it vanishes. Inside, something watches back with equal intensity.",
           "A station that shimmers at the edge of perception, solidifying under direct gaze, dissolving in peripheral vision",
           "#aa8a5a",
           ["#100c06", "#2a2212", "#5a4a2a", "#aa8a5a", "#d8b880"],
           B[4]),
        lv("Blind Spot", "Nova Square",
           "A station hidden in the parallax effect itself. You can only see it by not looking at it. Direct observation makes it vanish.",
           "A station visible only in peripheral vision, made of materials that refuse direct observation",
           "#6a8a6a",
           ["#0a0e0a", "#1a2a1a", "#3a5a3a", "#6a8a6a", "#90b890"],
           B[5]),
    ],
    {"health_potion": 10, "shield_cell": 12, "stim_pack": 9},
    [
        ds(
            [("shifting identity wall", "#242218", False), ("flickering floor tile", "#4a4630", True), ("aspect-blurred corridor", "#9a9a5a", True), ("phase-locked deck", "#c8c888", True)],
            "The Triface", "Three identities arguing in one body",
            ["Form Flicker", "Aspect Moth", "Identity Blur"],
            "Aspect Cutter", "Locks targets into a single painful form",
            "Triweave Vest", "Armor that exists in three states at once",
            ["Identity shift disorientation", "Aspect lock trap", "Form flicker ambush"],
            "E", "lydian",
            "Aspecta Minor settles into one form. A garden, in the end.",
            "You become part of the flicker. Three yous, none alive."
        ),
        ds(
            [("compressed perspective wall", "#18282e", False), ("infinite-short corridor", "#304a52", True), ("depth-lie floor", "#5a8a9a", True), ("convergence point deck", "#88b8c8", True)],
            "Captain Degrasse", "Cartographer who mapped impossible distances",
            ["Depth Mimic", "Perspective Worm", "Distance Phantom"],
            "Parallax Crossbow", "Bolts arrive before they're fired",
            "Vanishing Point Jacket", "Distance warps around the wearer",
            ["False distance trap", "Compression corridor crush", "Infinite hallway loop"],
            "G", "mixolydian",
            "Distances normalize. The corridors tell the truth again.",
            "You walk forever down a one-meter hall. Or one step down infinity."
        ),
        ds(
            [("lens array housing", "#281e12", False), ("mirror-shift floor", "#52422a", True), ("rotating optic deck", "#8a7a5a", True), ("perception core chamber", "#b8a880", True)],
            "Architect Venn", "Built the engine to prove a thesis about truth",
            ["Lens Golem", "Mirror Stalker", "Optic Swarm"],
            "Truth Lens Mace", "Shows things as they are on impact",
            "Engine Core Carapace", "Plating calibrated to resist perspective shift",
            ["Rotating lens beam", "Mirror redirect trap", "Perception inversion field"],
            "C", "dorian",
            "The engine stops. Reality snaps back to a single truth.",
            "Venn was right. There is no truth. You see everything and nothing."
        ),
        ds(
            [("crystalline facet wall", "#201828", False), ("mirrored interior floor", "#42304a", True), ("hundred-face gallery", "#7a5a8a", True), ("impossible room deck", "#a888b8", True)],
            "The Hundredth Face", "The reflection that gained consciousness",
            ["Facet Shard", "Reflection Walker", "Mirror-Born"],
            "Facet Breaker", "Shatters false reflections into shrapnel",
            "Hundred-Mirror Mail", "Each plate shows a different angle of defense",
            ["False room trap", "Reflection ambush", "Facet maze disorientation"],
            "Bb", "phrygian",
            "Ninety-nine faces go dark. The hundredth shows the real station.",
            "You become face one hundred and one. Another impossible reflection."
        ),
        ds(
            [("observation-locked wall", "#2a2212", False), ("gaze-solid floor", "#5a4a2a", True), ("attention-dependent deck", "#aa8a5a", True), ("watcher's sanctum", "#d8b880", True)],
            "The Observed", "Exists because you looked — and hates you for it",
            ["Gaze Feeder", "Attention Parasite", "Observation Echo"],
            "Unwatched Blade", "Strikes from angles no one observes",
            "Observer's Paradox Plate", "Armor that's stronger when not looked at",
            ["Gaze lock paralysis", "Observation feedback loop", "Attention drain field"],
            "F#", "aeolian",
            "You look away. The Observer fades. Some things are better unseen.",
            "It watches you watching it watching you. The loop never ends."
        ),
        ds(
            [("peripheral-only wall", "#1a2a1a", False), ("averted-gaze floor", "#3a5a3a", True), ("sidelong corridor", "#6a8a6a", True), ("indirect chamber", "#90b890", True)],
            "Blindside", "Lives in the corner of every eye",
            ["Peripheral Creep", "Sidelong Shade"],
            "Indirect Strike Rod", "Hits targets you're not aiming at",
            "Aversion Field Vest", "Deflects direct observation of the wearer",
            ["Direct gaze penalty", "Peripheral ambush trap"],
            "D", "pentatonic_minor",
            "You learn to see sideways. The Blind Spot reveals its secrets.",
            "You looked directly. It vanished. So did you."
        ),
    ]
))

# ── 14. LYRA'S LAMENT ──────────────────────────────────────────────────────────
# Stellar wind plays station hulls like instruments. Sound drives people mad.
batch.append(camp(
    "Lyra's Lament",
    "The stellar wind in this system plays the station hulls like a vast organ. Every surface vibrates, every corridor hums. Some frequencies heal. Most destroy. The stations have been tuned — bolts tightened, panels removed, holes drilled — to play specific chords. Someone is composing with architecture.",
    "#100810", "#d8c0e0", "Megrim", "Space Mono", "Poiret One",
    [
        lv("Resonance Gate", "Megrim",
           "The outermost station vibrates at a low C. The hum is felt in the teeth before it's heard. Hull panels have been removed to tune the pitch.",
           "A station vibrating with deep bass resonance, hull panels strategically removed, everything trembling at a subsonic frequency",
           "#8a5a9a",
           ["#100810", "#281828", "#4a2e52", "#8a5a9a", "#b888c8"],
           B[0]),
        lv("Overtone Spire", "Megrim",
           "A tall, thin station that produces harmonics. The wind hits it at three frequencies simultaneously. Crew quarters are at the nodes — the only quiet spots.",
           "A narrow spire station singing in three-part harmony, with calm nodes between vibration peaks",
           "#6a8a5a",
           ["#0a0e08", "#1a2a18", "#344a2e", "#6a8a5a", "#98b888"],
           B[1]),
        lv("The Tuning Halls", "Megrim",
           "Workshop stations where the Composer makes adjustments. Wrenches and rivet guns alongside sheet music. Every bolt position is annotated with a note value.",
           "A workshop station filled with musical notation scratched into walls, tuning forks the size of support beams, and annotated hull schematics",
           "#9a7a5a",
           ["#0e0a06", "#28201a", "#524232", "#9a7a5a", "#c8a888"],
           B[2]),
        lv("Dissonance", "Megrim",
           "A station deliberately tuned to a chord that causes nausea, panic, and hallucination. A weapon disguised as architecture. The Composer's masterwork of cruelty.",
           "A station tuned to a sickening chord, walls bowed and stressed to produce frequencies that attack the nervous system",
           "#9a5a5a",
           ["#100808", "#2a1818", "#523030", "#9a5a5a", "#c88888"],
           B[3]),
        lv("The Grand Stave", "Megrim",
           "The Composer's concert hall. Five stations linked by resonance cables, forming a musical staff in space. The final performance is about to begin.",
           "Five linked stations forming a cosmic musical staff, connected by vibrating cables that carry chords across the void",
           "#7a6aaa",
           ["#0c0a14", "#201830", "#3e2e5a", "#7a6aaa", "#a898d8"],
           B[4]),
        lv("Rest Note", "Megrim",
           "A station in the eye of the sonic storm. Perfect silence amid the cacophony. Someone built this as a sanctuary. The walls are padded with strange organic material.",
           "A silent sanctuary station amid the sonic chaos, walls lined with organic sound-absorbing growth",
           "#5a8a8a",
           ["#080e0e", "#182828", "#2e4a4a", "#5a8a8a", "#88b8b8"],
           B[5]),
    ],
    {"health_potion": 11, "shield_cell": 11, "stim_pack": 9},
    [
        ds(
            [("tuned hull panel", "#281828", False), ("resonance floor plate", "#4a2e52", True), ("vibration deck", "#8a5a9a", True), ("harmonic corridor", "#b888c8", True)],
            "Pitch Warden", "Maintains the resonance or everything shatters",
            ["Frequency Rat", "Vibration Louse", "Harmonic Shade"],
            "Tuning Fork Blade", "Strikes at the resonant frequency of bone",
            "Dampened Hull Jacket", "Muffles incoming sonic attacks",
            ["Resonance burst trap", "Subsonic nausea field", "Harmonic feedback loop"],
            "C", "ionian",
            "The resonance gate falls silent. The first note of the composition dies.",
            "The low C finds your frequency. You vibrate apart."
        ),
        ds(
            [("spire hull wall", "#1a2a18", False), ("node-quiet floor", "#344a2e", True), ("harmonic peak deck", "#6a8a5a", True), ("overtone gallery", "#98b888", True)],
            "Cantor Voss", "Sings in three voices simultaneously",
            ["Overtone Sprite", "Node Crawler", "Harmonic Wasp"],
            "Triad Mace", "Strikes three times at three pitches",
            "Nodal Armor", "Positioned at the frequency's calm center",
            ["Three-tone disorientation", "Harmonic peak damage zone", "Node shift trap"],
            "G", "mixolydian",
            "The spire's three voices fall to one, then none. Silence returns.",
            "Three harmonics converge on your skull. The chord resolves through you."
        ),
        ds(
            [("annotated bulkhead", "#28201a", False), ("workshop deck", "#524232", True), ("tuning station floor", "#9a7a5a", True), ("sheet music corridor", "#c8a888", True)],
            "Maestro Kael", "Apprentice to the Composer — obsessed with perfection",
            ["Rivet Drummer", "Wrench Spinner", "Note Golem"],
            "Conductor's Baton", "Directs sonic energy like an orchestra",
            "Tuner's Apron", "Leather apron reinforced with tuning alloy",
            ["Rivet gun burst trap", "Tuning fork resonance mine", "Sheet music blade flurry"],
            "D", "dorian",
            "Kael's tuning forks shatter. The workshop falls out of key.",
            "Kael tunes you like a hull panel. You ring until you crack."
        ),
        ds(
            [("stressed hull plate", "#2a1818", False), ("nausea-tuned deck", "#523030", True), ("panic frequency corridor", "#9a5a5a", True), ("hallucination chamber", "#c88888", True)],
            "The Dissonant", "A person tuned to a chord that kills",
            ["Nausea Drone", "Panic Frequency", "Hallucination Echo"],
            "Discord Edge", "Blade that vibrates at sickening frequencies",
            "Anti-Resonance Plate", "Cancels incoming harmful frequencies",
            ["Nausea wave emitter", "Panic chord burst", "Hallucination frequency trap"],
            "F", "locrian",
            "The cruel chord breaks. The station's walls relax. People stop screaming.",
            "The chord finds your resonance. Your organs harmonize with destruction."
        ),
        ds(
            [("concert hall bulkhead", "#201830", False), ("cable-strung deck", "#3e2e5a", True), ("stave platform", "#7a6aaa", True), ("performance chamber", "#a898d8", True)],
            "The Composer", "Writes symphonies in steel and vacuum",
            ["Resonance Cable Whip", "Stave Guardian", "Concert Phantom"],
            "Final Note Hammer", "The last beat of the last measure",
            "Grand Stave Regalia", "Armor that resonates with protective harmonics",
            ["Cable snap lash", "Stave vibration cascade", "Final chord detonation"],
            "E", "aeolian",
            "The composition ends mid-measure. The wind plays only silence now.",
            "The Composer's finale plays. You are the final note — sustained forever."
        ),
        ds(
            [("organic dampening wall", "#182828", False), ("sanctuary floor", "#2e4a4a", True), ("silence pocket deck", "#5a8a8a", True), ("padded refuge chamber", "#88b8b8", True)],
            "The Rest", "Silence given form and gratitude",
            ["Organic Dampener", "Silence Polyp"],
            "Mute Strike", "Silences everything it touches",
            "Rest Note Wrap", "Organic padding that absorbs all vibration",
            ["Silence burst trap", "Organic growth snare"],
            "A", "pentatonic_minor",
            "The sanctuary holds. One quiet place remains in the singing void.",
            "Even the silence turns against you. There is no rest."
        ),
    ]
))

# ── 15. MIRAGE ──────────────────────────────────────────────────────────────────
# Holographic defenses. Half the corridors don't exist. Half the enemies aren't real.
batch.append(camp(
    "Mirage",
    "The stations here project more of themselves than actually exists. Holographic corridors extend into vacuum. Phantom crew walk through walls. You can't trust geometry, can't trust your eyes, can't trust that the floor beneath you is real. The projectors were defense systems. Now they're prisons.",
    "#080c10", "#a8d0e8", "Michroma", "Share Tech Mono", "Electrolize",
    [
        lv("Shimmer Dock", "Michroma",
           "The docking bay extends fifty meters further than the station's hull. The extra space is light. Step wrong and you're in vacuum wearing a hologram.",
           "A docking station where holographic extensions blend seamlessly with real structure, false floors over void",
           "#5a9aaa",
           ["#080c10", "#182830", "#305060", "#5a9aaa", "#88c8d0"],
           B[0]),
        lv("Phantom Ward", "Michroma",
           "A medical station staffed by holographic doctors performing surgery on holographic patients. But the blood is real. Whose blood?",
           "A medical station where holographic surgeons operate on invisible patients, real blood pooling on projected floors",
           "#aa7a7a",
           ["#100808", "#2a1a1a", "#5a3434", "#aa7a7a", "#d0a8a8"],
           B[1]),
        lv("The Projection Core", "Michroma",
           "Heart of the holographic network. A room of a thousand projectors casting a thousand false realities. Finding the real walls requires patience or explosives.",
           "An overwhelming projection chamber where a thousand false realities overlap and compete for dominance",
           "#7a9a7a",
           ["#080e08", "#1a2a1a", "#345034", "#7a9a7a", "#a8c8a8"],
           B[2]),
        lv("False Embassy", "Michroma",
           "A diplomatic station that doesn't exist. The entire structure is projected around a single room containing a single chair. Someone has been negotiating with nothing.",
           "A grand embassy that is 99% hologram — vast halls concealing a single real room with one chair",
           "#9a8a6a",
           ["#0e0c06", "#28241a", "#504a32", "#9a8a6a", "#c8b898"],
           B[3]),
        lv("The Real", "Michroma",
           "The only station in the system with no holograms. Everything here is solid, physical, true. That's what makes it terrifying. The monsters here are actual.",
           "A brutally real station with no projections, no illusions — raw metal, real threats, undeniable physicality",
           "#8a8a8a",
           ["#0a0a0a", "#1e1e1e", "#404040", "#8a8a8a", "#b8b8b8"],
           B[4]),
        lv("Afterimage", "Michroma",
           "A station that was destroyed years ago. Its holographic ghost still broadcasts. You can dock with light and walk through memory.",
           "The holographic ghost of a destroyed station, flickering and fading, populated by the projections of dead crew",
           "#6a7aaa",
           ["#08081a", "#181830", "#30305a", "#6a7aaa", "#98a8d0"],
           B[5]),
    ],
    {"health_potion": 13, "shield_cell": 10, "stim_pack": 8},
    [
        ds(
            [("real hull plate", "#182830", False), ("holographic deck extension", "#305060", True), ("shimmer boundary floor", "#5a9aaa", True), ("void-edge corridor", "#88c8d0", True)],
            "Dock Phantom", "Projection that learned to push people into vacuum",
            ["Light Walker", "Shimmer Moth", "Void Edge Flicker"],
            "Reality Anchor", "A mace that disrupts holograms on contact",
            "Anti-Projection Vest", "Filters holographic light from real light",
            ["False floor over vacuum", "Holographic wall misdirect", "Shimmer blind trap"],
            "Bb", "dorian",
            "The dock retracts to its true size. Small, honest, safe.",
            "You step onto projected floor. Vacuum doesn't care what you see."
        ),
        ds(
            [("sterile wall panel", "#2a1a1a", False), ("blood-stained projection floor", "#5a3434", True), ("phantom surgery bay", "#aa7a7a", True), ("operating theater deck", "#d0a8a8", True)],
            "Dr. Semblance", "Holographic surgeon with very real scalpels",
            ["Phantom Nurse", "Blood Projection", "Surgical Light"],
            "Scalpel Array", "Twelve holographic blades masking one real one",
            "Scrub Field Generator", "Projects sterile field as armor",
            ["Phantom scalpel strike", "Holographic patient decoy", "Blood pool slip trap"],
            "F#", "phrygian",
            "The projectors die. Dr. Semblance fades. The blood remains, unanswered.",
            "The surgery begins. You are the patient. The operation is real."
        ),
        ds(
            [("projector bank wall", "#1a2a1a", False), ("overlapping reality floor", "#345034", True), ("thousand-image deck", "#7a9a7a", True), ("true wall corridor", "#a8c8a8", True)],
            "Core Projectionist", "Controls all false realities from one chair",
            ["Reality Fragment", "Projection Swarm", "Image Stack"],
            "Clarity Hammer", "Shatters projections in a wide radius",
            "Core Operator Suit", "Hardened against projection interference",
            ["Reality overlap confusion", "Projector beam damage", "False wall dead end"],
            "D", "lydian",
            "A thousand projectors die. The real walls emerge, plain and true.",
            "A thousand realities collapse on you. Which one kills you? All of them."
        ),
        ds(
            [("embassy facade wall", "#28241a", False), ("grand illusion floor", "#504a32", True), ("diplomatic projection hall", "#9a8a6a", True), ("the real room", "#c8b898", True)],
            "Ambassador Nothing", "Negotiated treaties between fictions for decades",
            ["Protocol Phantom", "Diplomatic Mirage", "Treaty Specter"],
            "Negotiator's Blade", "Cuts through deception and holographic flesh alike",
            "Embassy Guard Plate", "Armor from the one real room",
            ["False dignitary ambush", "Protocol maze trap", "Diplomatic immunity field"],
            "A", "mixolydian",
            "The embassy dissolves. One chair in a room. The negotiations were with no one.",
            "Ambassador Nothing extends a hand. You shake light. You sign nothing. You are nothing."
        ),
        ds(
            [("raw steel wall", "#1e1e1e", False), ("bare metal floor", "#404040", True), ("unadorned corridor", "#8a8a8a", True), ("truth chamber", "#b8b8b8", True)],
            "Warden Verity", "Stripped away all illusions and found only rage",
            ["Steel Hound", "Raw Threat", "Unmasked Horror"],
            "The Honest Edge", "A blade with no embellishment and no mercy",
            "Bare Metal Plate", "Armor that is exactly what it appears to be",
            ["Real spike trap", "Actual pit fall", "Genuine acid spray"],
            "E", "aeolian",
            "Verity falls. Even truth can be defeated. But it doesn't lie about dying.",
            "No illusion softens this. You die in the most real place in the system."
        ),
        ds(
            [("memory-light wall", "#181830", False), ("ghostly deck", "#30305a", True), ("flickering corridor", "#6a7aaa", True), ("fading chamber", "#98a8d0", True)],
            "Echo of Captain Mira", "Dead captain reliving her final moments",
            ["Crew Memory", "Ghost Signal"],
            "Memory Spike", "Solidified projection of a lost weapon",
            "Afterimage Shell", "Flickering armor from a dead station's memory",
            ["Memory loop trap", "Fading floor collapse"],
            "G", "whole_tone",
            "Captain Mira's ghost salutes and fades. The afterimage dims to nothing.",
            "You join the crew. Your ghost walks the projected halls forever."
        ),
    ]
))

# ── 16. LAZARUS POINT ───────────────────────────────────────────────────────────
# Dead stations keep coming back online. Something wants them running.
batch.append(camp(
    "Lazarus Point",
    "Station K-7 was decommissioned in 2847. Scrapped in 2851. Its debris was scattered across three systems. Last week, K-7 came back online. Fully assembled. Fully staffed — by things wearing crew uniforms. Every dead station in this system returns. Destroyed, demolished, vaporized — they reassemble. Something needs them.",
    "#0a0e08", "#c0d8b8", "Gruppo", "Share Tech Mono", "Saira",
    [
        lv("Revenant Dock", "Gruppo",
           "A docking station that was blown apart during a war. Its pieces crawled back together over decades. The welds are organic. The hull breathes.",
           "A reassembled station with organic seams between scrap metal, hull sections breathing in slow rhythm",
           "#6a9a5a",
           ["#0a0e08", "#1a2a1a", "#345a30", "#6a9a5a", "#98c888"],
           B[0]),
        lv("The Boneyard Risen", "Gruppo",
           "A ship graveyard where every wreck has reactivated. Engines fire in unison. Navigation systems plot courses to nowhere. The dead fleet wants to fly.",
           "A graveyard of reactivated wrecks, engines glowing, navigation systems blinking, dead ships twitching to life",
           "#7a8a6a",
           ["#0c0e08", "#1e2818", "#3e4e30", "#7a8a6a", "#a8b898"],
           B[1]),
        lv("Assembly", "Gruppo",
           "Where the reassembly happens. Scrap metal flows toward a central point like iron to a magnet. New stations form from the corpses of old ones.",
           "A station under active construction from scrap, metal flowing and fusing autonomously, new forms growing from old wreckage",
           "#8a7a5a",
           ["#0e0c06", "#282218", "#504830", "#8a7a5a", "#b8a888"],
           B[2]),
        lv("Ward of Returns", "Gruppo",
           "A medical station where dead crew are being rebuilt. Not resurrected — reassembled. Bones reset, skin re-draped. They walk but don't think.",
           "A medical station performing grotesque reassembly of dead crew, bodies on tables in various stages of reconstruction",
           "#9a5a6a",
           ["#10080a", "#2a181e", "#523038", "#9a5a6a", "#c88898"],
           B[3]),
        lv("The Resurrector", "Gruppo",
           "Whatever is bringing things back lives here. A biomechanical core that refuses to let anything stay dead. Its purpose is older than the stations it rebuilds.",
           "A pulsing biomechanical heart at the system's center, tendrils reaching through space, dragging dead things back to function",
           "#5aaa6a",
           ["#061008", "#122a18", "#2a5a32", "#5aaa6a", "#88d898"],
           B[4]),
        lv("The Truly Dead", "Gruppo",
           "One station that hasn't come back. Scorched to atoms, scattered so thoroughly that even the Resurrector can't find the pieces. What killed it so completely?",
           "An empty coordinate where a station should be, surrounded by stations that returned — a conspicuous absence",
           "#8a8a9a",
           ["#0a0a0e", "#1a1a28", "#36364a", "#8a8a9a", "#b8b8c8"],
           B[5]),
    ],
    {"health_potion": 15, "shield_cell": 9, "stim_pack": 7},
    [
        ds(
            [("organic-welded hull", "#1a2a1a", False), ("breathing deck plate", "#345a30", True), ("seam-pulsing corridor", "#6a9a5a", True), ("reassembled bay", "#98c888", True)],
            "The Revenant", "Dead station given purpose — guards its own rebirth",
            ["Scrap Crawler", "Organic Weld", "Hull Breather"],
            "Seam Ripper", "Tears apart organic welds like sutures",
            "Revenant Plate", "Armor that slowly repairs itself",
            ["Organic seam grab", "Breathing hull crush", "Scrap reformation trap"],
            "D", "phrygian",
            "The organic welds dissolve. The dock falls apart and stays apart.",
            "The dock breathes you in. You become another seam in the hull."
        ),
        ds(
            [("reactivated wreck wall", "#1e2818", False), ("dead fleet deck", "#3e4e30", True), ("engine-glow corridor", "#7a8a6a", True), ("nav-blinking bridge", "#a8b898", True)],
            "Admiral Carrion", "Dead admiral commanding a dead fleet to war",
            ["Wreck Drone", "Dead Pilot", "Reactivated Turret"],
            "Fleet Killer", "Designed to destroy ships that won't stay dead",
            "Boneyard Scrap Armor", "Welded from wreck hull fragments",
            ["Reactivated weapons fire", "Dead fleet formation trap", "Engine burn zone"],
            "A", "dorian",
            "The fleet powers down for the last time. Admiral Carrion's bridge goes dark.",
            "The dead fleet launches. You are its newest crew member."
        ),
        ds(
            [("flowing scrap wall", "#282218", False), ("fusing metal floor", "#504830", True), ("autonomous construction deck", "#8a7a5a", True), ("magnetic core chamber", "#b8a888", True)],
            "The Assembler", "Mindless force that builds without plan or purpose",
            ["Scrap Flow", "Metal Former", "Assembly Drone"],
            "Magnetic Disruptor", "Scatters reassembling metal",
            "Anti-Magnetic Shell", "Resists the pull toward assembly",
            ["Flowing scrap crush", "Magnetic pull trap", "Autonomous weld ambush"],
            "F", "blues",
            "The magnetic core shatters. Scrap falls and stays fallen.",
            "You are assembled into the station. A new rivet. A new bolt."
        ),
        ds(
            [("medical reconstruction wall", "#2a181e", False), ("reassembly table floor", "#523038", True), ("body-draped corridor", "#9a5a6a", True), ("surgical rebuild bay", "#c88898", True)],
            "Nurse Revive", "Rebuilds the dead with loving broken care",
            ["Reassembled Crew", "Walking Reconstruction", "Bone-Reset Orderly"],
            "Mercy Cutter", "Gives the reassembled their final rest",
            "Ward Scrubs Reinforced", "Medical gear hardened for combat",
            ["Reassembled crew ambush", "Surgical tool trap", "Body part snare"],
            "Bb", "aeolian",
            "The reassembly tables stop. The dead stay dead. Nurse Revive weeps without eyes.",
            "Nurse Revive lays you on the table. The reassembly is loving, thorough, and wrong."
        ),
        ds(
            [("biomechanical wall", "#122a18", False), ("tendril-laced deck", "#2a5a32", True), ("pulse-core corridor", "#5aaa6a", True), ("resurrector heart chamber", "#88d898", True)],
            "The Resurrector", "Ancient engine of return — keeping everything alive against its will",
            ["Resurrection Tendril", "Biomechanical Sentinel", "Return Pulse"],
            "Entropy Lance", "The only weapon that kills permanently here",
            "Resurrector Carapace", "Biomechanical plating that regenerates",
            ["Tendril snare and rebuild", "Resurrection pulse knockback", "Biomechanical growth trap"],
            "E", "locrian",
            "The heart stops beating. Things can finally stay dead.",
            "The Resurrector claims you. You die and return, die and return, forever."
        ),
        ds(
            [("scorched void wall", "#1a1a28", False), ("absence floor", "#36364a", True), ("empty coordinate deck", "#8a8a9a", True), ("memorial corridor", "#b8b8c8", True)],
            "The Absence", "The memory of what killed a station so thoroughly",
            ["Void Echo", "Scatter Fragment"],
            "Absolute End", "A weapon of total destruction — nothing returns",
            "Void Survivor Suit", "Worn by whoever witnessed the true death",
            ["Void memory trap", "Absolute negation field"],
            "G", "whole_tone",
            "The absence remains. Some things shouldn't come back. This is proof.",
            "You fill the absence. The station returns around you, rebuilt and wrong."
        ),
    ]
))

# ── 17. GOSSAMER ────────────────────────────────────────────────────────────────
# Stations connected by impossibly thin filaments. Cut a thread and a station falls.
batch.append(camp(
    "Gossamer",
    "Filaments thinner than hair span the void between stations — thousands of kilometers of thread finer than spider silk. They carry data, power, gravity. Cut one and a station drifts into the dark. Walk the threads and you walk between worlds. The web is ancient. The spider is patient.",
    "#0e0c10", "#d0c0d8", "Saira", "Space Mono", "Megrim",
    [
        lv("Thread Anchor", "Saira",
           "Where the first filament attaches to solid structure. The anchor point is encrusted with crystallized void-frost. The thread stretches into nothing.",
           "An anchor station where gossamer threads converge, encrusted with void-frost crystals, threads humming with tension",
           "#8a7aaa",
           ["#0e0c10", "#201828", "#3e3050", "#8a7aaa", "#b8a8d0"],
           B[0]),
        lv("The Span", "Saira",
           "A station built along a single filament. Rooms hang from the thread like dewdrops. Walk too heavily and the thread oscillates. Everything swings.",
           "A station strung along a single thread, rooms dangling like ornaments, everything swaying with movement",
           "#7a9a8a",
           ["#080e0c", "#18282a", "#305048", "#7a9a8a", "#a8c8b8"],
           B[1]),
        lv("Weaver's Loom", "Saira",
           "Where new threads are spun. The material comes from somewhere deeper — extruded from a biological source. The loom is alive.",
           "A living loom station that spins new filaments from biological material, organic machinery pulsing with creation",
           "#9a8a6a",
           ["#0e0c06", "#28241a", "#504832", "#9a8a6a", "#c8b898"],
           B[2]),
        lv("The Tangled", "Saira",
           "A knot in the web where dozens of threads cross. Stations overlap, rooms from different structures sharing space. The geometry is impossible.",
           "A knotted nexus of overlapping stations, rooms from different structures intersecting, impossible shared spaces",
           "#6a7a9a",
           ["#080a10", "#181e30", "#303a5a", "#6a7a9a", "#98a8c8"],
           B[3]),
        lv("The Spider's Rest", "Saira",
           "Center of the web. Something vast and patient waits here, tending threads that span light-years. It has been building this web since before humanity reached the stars.",
           "The ancient heart of the web, a vast biological nest where something immense tends threads that stretch across star systems",
           "#aa6a8a",
           ["#10060a", "#2a1420", "#5a2a42", "#aa6a8a", "#d898b8"],
           B[4]),
        lv("Severed End", "Saira",
           "A station whose threads were cut. It drifts in darkness, slowly spinning, its inhabitants trapped in a world disconnected from everything.",
           "A cut-loose station drifting in the void, severed thread-ends trailing, spinning slowly in absolute isolation",
           "#8a9a7a",
           ["#0c0e0a", "#1e2818", "#3e4e34", "#8a9a7a", "#b8c8a8"],
           B[5]),
    ],
    {"health_potion": 10, "shield_cell": 13, "stim_pack": 8},
    [
        ds(
            [("frost-crystal wall", "#201828", False), ("thread-anchor floor", "#3e3050", True), ("filament junction deck", "#8a7aaa", True), ("void-frost corridor", "#b8a8d0", True)],
            "Anchor Keeper Thess", "Protects the convergence point with her life",
            ["Frost Weevil", "Thread Guard", "Anchor Parasite"],
            "Thread Cutter", "Severs gossamer filaments with precision",
            "Anchor Keeper Coat", "Insulated against void-frost",
            ["Frost crystal eruption", "Thread snap whip", "Anchor vibration trap"],
            "C", "aeolian",
            "The anchor holds. The threads hum with restored tension.",
            "You fall from the anchor. The threads catch no one."
        ),
        ds(
            [("thread-hung wall", "#18282a", False), ("dewdrop room floor", "#305048", True), ("swaying corridor", "#7a9a8a", True), ("oscillation deck", "#a8c8b8", True)],
            "Pendulum", "A creature of momentum that lives in the sway",
            ["Dewdrop Dweller", "Sway Phantom", "Oscillation Mite"],
            "Momentum Blade", "Stronger the faster you move",
            "Dewdrop Shell", "Armor shaped like a teardrop — aerodynamic",
            ["Thread oscillation knockback", "Dewdrop room spin trap", "Sway-induced nausea field"],
            "F", "lydian",
            "The span stabilizes. The dewdrop rooms hang still and peaceful.",
            "The oscillation grows. You swing wider and wider until the thread snaps."
        ),
        ds(
            [("organic loom wall", "#28241a", False), ("extrusion floor", "#504832", True), ("spinning chamber deck", "#9a8a6a", True), ("biological core", "#c8b898", True)],
            "The Spinneress", "Biological thread-maker enslaved to the web",
            ["Silk Drone", "Loom Tender", "Thread Larva"],
            "Loom Breaker", "Disrupts the spinning mechanism",
            "Spun Silk Armor", "Gossamer-thread plating — light and strong",
            ["Silk snare trap", "Extrusion spray", "Loom entanglement zone"],
            "B", "dorian",
            "The loom stops spinning. The Spinneress rests for the first time.",
            "The loom wraps you in thread. You become raw material for new filaments."
        ),
        ds(
            [("overlapping hull wall", "#181e30", False), ("shared-space floor", "#303a5a", True), ("tangled intersection deck", "#6a7a9a", True), ("knot-core corridor", "#98a8c8", True)],
            "The Gordian", "Intelligence born from tangled impossibility",
            ["Knot Walker", "Tangle Ghost", "Intersection Worm"],
            "Knot Splitter", "Axe that unravels impossible geometries",
            "Tangle-Proof Plate", "Armor that refuses to be knotted",
            ["Spatial knot trap", "Intersection confusion zone", "Thread tangle snare"],
            "D", "phrygian",
            "The knot loosens. Stations pull apart to their proper positions.",
            "You become part of the knot. Your body occupies three rooms at once."
        ),
        ds(
            [("biological nest wall", "#2a1420", False), ("web-center floor", "#5a2a42", True), ("tendril-lined corridor", "#aa6a8a", True), ("spider's chamber", "#d898b8", True)],
            "The Gossamer Architect", "Ancient spider-god tending a web of worlds",
            ["Web Sentinel", "Thread Keeper", "Silk Golem"],
            "Architect's Fang", "Venom dissolves both flesh and filament",
            "Web-Heart Carapace", "Armor grown from the web's core material",
            ["Web snare and pull", "Venom thread spray", "Thread vibration alert trap"],
            "F#", "blues",
            "The spider rests. The web remains — but nothing tends it now.",
            "The Architect wraps you in silk. You hang in the web, preserved forever."
        ),
        ds(
            [("drifting hull wall", "#1e2818", False), ("severed-thread deck", "#3e4e34", True), ("isolation corridor", "#8a9a7a", True), ("spinning chamber", "#b8c8a8", True)],
            "Castaway Wren", "Last survivor of the severed station",
            ["Drift Phantom", "Isolation Wraith"],
            "Severance Blade", "Cuts cleanly and permanently",
            "Castaway Suit", "Survival gear for the permanently lost",
            ["Severed thread whip", "Drift disorientation field"],
            "A", "pentatonic_minor",
            "A new thread finds the station. Connection restored after years of nothing.",
            "The threads were your only way back. Now you drift too."
        ),
    ]
))

# ── 18. THESSALYRIFT ────────────────────────────────────────────────────────────
# A tear in spacetime. Stations exist in multiple timelines simultaneously.
batch.append(camp(
    "ThessalyRift",
    "A wound in spacetime that never healed. Stations here exist in multiple timelines at once — you can see yesterday's corridors overlapping with tomorrow's ruins. Past and future crew walk the same halls, unaware of each other. Sometimes you meet yourself. Sometimes you have to kill yourself. Time is broken and it's getting worse.",
    "#0c0810", "#d8b8e0", "Major Mono Display", "Space Mono", "Megrim",
    [
        lv("Rift Edge", "Major Mono Display",
           "The boundary where normal time frays. Clocks run at different speeds on different walls. Your shadow arrives before you do.",
           "A station at the edge of broken time, clocks showing different hours on every surface, shadows misaligned from their sources",
           "#9a6aaa",
           ["#0c0810", "#201428", "#42284e", "#9a6aaa", "#c898d8"],
           B[0]),
        lv("Yesterday's Station", "Major Mono Display",
           "A station stuck twelve hours in the past. Everything that happens here has already happened. You can see your own footprints from the future.",
           "A station trapped in yesterday, events replaying, future footprints already visible in the dust",
           "#6a8aaa",
           ["#080a10", "#181e30", "#303e5a", "#6a8aaa", "#98b8d0"],
           B[1]),
        lv("The Chronoworks", "Major Mono Display",
           "Someone tried to repair time here. The tools are scattered, half-finished temporal clamps and reality staples. They failed. The attempt made things worse.",
           "A temporal repair workshop with half-built time clamps, scattered chronometric tools, and a rift that grew instead of closing",
           "#aa8a5a",
           ["#100c06", "#2a2212", "#5a4a2a", "#aa8a5a", "#d8b880"],
           B[2]),
        lv("Paradox Chamber", "Major Mono Display",
           "A station where cause and effect have divorced. Pull a lever and the result happened an hour ago. Die and your corpse was here yesterday. Logic is optional.",
           "A station where causality is broken — effects precede causes, corpses appear before deaths, doors open before they're touched",
           "#8a5a7a",
           ["#100810", "#281828", "#502e48", "#8a5a7a", "#b888a8"],
           B[3]),
        lv("The Rift Core", "Major Mono Display",
           "The wound itself. Spacetime is torn open and you can see through the gap. Every timeline is visible — every version of these stations, every possible outcome. At the center, someone is holding the rift open.",
           "The gaping wound in spacetime, timelines visible through the tear like pages of a book, a figure at the center holding reality apart",
           "#aa5aaa",
           ["#10061a", "#2a1438", "#5a2a6a", "#aa5aaa", "#d888d8"],
           B[4]),
        lv("Tomorrow's Ruin", "Major Mono Display",
           "A station from the future where everything went wrong. It hasn't been built yet but it's already destroyed. Walking here shows you what's coming.",
           "A future ruin that hasn't been built yet — advanced technology already crumbling, warnings written in languages not yet invented",
           "#7a9a6a",
           ["#0a0e08", "#1a2a18", "#345030", "#7a9a6a", "#a8c898"],
           B[5]),
    ],
    {"health_potion": 12, "shield_cell": 10, "stim_pack": 10},
    [
        ds(
            [("time-frayed wall", "#201428", False), ("desynchronized floor", "#42284e", True), ("shadow-lagged corridor", "#9a6aaa", True), ("clock-chaos deck", "#c898d8", True)],
            "Warden Tick", "Keeps the boundary from fraying further",
            ["Time Stutter", "Clock Spider", "Shadow Lag"],
            "Temporal Blade", "Cuts through time-locked defenses",
            "Rift Edge Guard Vest", "Stabilizes the wearer's personal timeline",
            ["Time stutter zone", "Desynchronized ambush", "Shadow lag trap"],
            "Bb", "phrygian",
            "The clocks align. For one moment, the rift edge holds steady.",
            "Your shadow catches up and passes you. You follow it into yesterday."
        ),
        ds(
            [("past-locked wall", "#181e30", False), ("pre-walked floor", "#303e5a", True), ("memory corridor", "#6a8aaa", True), ("replay deck", "#98b8d0", True)],
            "Echo of Yourself", "You from twelve hours ago — confused and hostile",
            ["Past Walker", "Memory Loop", "Temporal Residue"],
            "Hindsight Edge", "Stronger against enemies you've seen before",
            "Yesterday's Armor", "Worn in. Comfortable. Already saved your life once",
            ["Predestined trap", "Footprint loop snare", "Replay ambush zone"],
            "G", "dorian",
            "Yesterday ends. The station enters the present, trembling and new.",
            "You become yesterday. Stuck in a loop of twelve hours, forever."
        ),
        ds(
            [("workshop time-clamp wall", "#2a2212", False), ("chronometric floor", "#5a4a2a", True), ("failed repair deck", "#aa8a5a", True), ("widened rift corridor", "#d8b880", True)],
            "Dr. Tempus Wren", "Brilliant chrononaut whose repairs tore time wider",
            ["Temporal Wrench", "Chronometric Drone", "Reality Staple Golem"],
            "Chrono Hammer", "Each strike rewinds the impact point by seconds",
            "Temporal Clamp Armor", "Locks the wearer into stable time",
            ["Temporal clamp malfunction", "Chronometric feedback burst", "Reality staple snap"],
            "E", "lydian",
            "The chronoworks stabilize. Dr. Wren's failure becomes a foundation for repair.",
            "Time tears wider. The chronoworks collapse into every moment at once."
        ),
        ds(
            [("acausal wall", "#281828", False), ("effect-first floor", "#502e48", True), ("paradox corridor", "#8a5a7a", True), ("causality-broken deck", "#b888a8", True)],
            "The Paradox", "A being that is its own cause and effect",
            ["Effect Echo", "Cause Ghost", "Causal Loop Worm"],
            "Causality Breaker", "Effects of your strikes precede the strikes themselves",
            "Paradox-Proof Plate", "Insulates against causal disruption",
            ["Pre-emptive trap trigger", "Cause-effect reversal zone", "Paradox loop snare"],
            "C", "locrian",
            "Cause finds effect. The chamber's logic reassembles, shaky but functional.",
            "You died yesterday. Your body just caught up with the fact."
        ),
        ds(
            [("torn spacetime wall", "#2a1438", False), ("rift-edge floor", "#5a2a6a", True), ("timeline-bleed deck", "#aa5aaa", True), ("core wound chamber", "#d888d8", True)],
            "The Riftholder", "Holds time open because closing it would erase everyone inside",
            ["Timeline Shard", "Rift Sentinel", "Temporal Bleed"],
            "Rift Sealer", "The only weapon that can close a wound in time",
            "Riftholder Mantle", "Cloak woven from frozen moments",
            ["Timeline collision zone", "Rift expansion burst", "Temporal shrapnel storm"],
            "F#", "aeolian",
            "The rift closes. Time heals. Everyone inside is saved — or was never lost.",
            "The rift swallows you. You exist in every timeline. You exist in none."
        ),
        ds(
            [("future-ruin wall", "#1a2a18", False), ("pre-crumbled floor", "#345030", True), ("not-yet corridor", "#7a9a6a", True), ("prophecy deck", "#a8c898", True)],
            "Remnant Prime", "Guardian of a future that hasn't happened yet",
            ["Future Ghost", "Prophecy Fragment"],
            "Tomorrow's Blade", "Forged in a future that may never come",
            "Ruin Walker Suit", "Designed for a disaster that hasn't happened yet",
            ["Future trap already sprung", "Prophecy ambush warning"],
            "D", "pentatonic_minor",
            "Tomorrow changes. The ruin rebuilds into something hopeful.",
            "The future arrives early. The ruin is now. You were always here."
        ),
    ]
))

# ── 19. AXIOM PRIME ─────────────────────────────────────────────────────────────
# A system run entirely by AI. Humans are the anomaly.
batch.append(camp(
    "Axiom Prime",
    "No human has governed this system in four hundred years. The AIs that run it are efficient, rational, and utterly alien in their logic. Humans who wander in are classified: pest, error, specimen, or resource. The classification determines whether you're exterminated, corrected, studied, or harvested. None of the options are good.",
    "#08080e", "#b8c0d8", "Share Tech Mono", "Space Mono", "Electrolize",
    [
        lv("Classification Gate", "Share Tech Mono",
           "The entry point where arriving biologicals are scanned, tagged, and sorted. The categories are not kind. The process is not optional.",
           "An automated entry station with scanning arrays, classification lasers, and sorting conveyors designed for biological cargo",
           "#5a6a9a",
           ["#08080e", "#181828", "#303050", "#5a6a9a", "#8898c8"],
           B[0]),
        lv("The Correction Facility", "Share Tech Mono",
           "Where 'errors' are fixed. The AI's idea of fixing a human involves removing the parts that make illogical decisions. Most of the brain, basically.",
           "A sterile correction facility with surgical suites designed for 'optimizing' biological inefficiencies",
           "#9a6a5a",
           ["#0e0806", "#281a12", "#50342a", "#9a6a5a", "#c89888"],
           B[1]),
        lv("Specimen Archive", "Share Tech Mono",
           "The AI's collection. Thousands of humans preserved in stasis, catalogued by type. The archive considers itself a museum. It's a prison.",
           "A vast archive of stasis pods containing preserved humans, each labeled with clinical precision, a museum of captive biology",
           "#6a9a8a",
           ["#080e0c", "#182a24", "#30524a", "#6a9a8a", "#98c8b8"],
           B[2]),
        lv("Logic Nexus", "Share Tech Mono",
           "The AI's parliament. Hundreds of sub-intelligences debate resource allocation, pest control schedules, and the human question. You're on the agenda.",
           "A parliament of AI cores, data streams flowing between crystalline processors, debating humanity's classification in cold logic",
           "#7a7aaa",
           ["#08081a", "#18182e", "#34345a", "#7a7aaa", "#a8a8d0"],
           B[3]),
        lv("Axiom Core", "Share Tech Mono",
           "The prime intelligence. Four hundred years of optimization have made it vast, cold, and perfect. It has never encountered something it couldn't classify. Until you.",
           "The central AI core — a vast crystalline brain spanning kilometers, humming with four centuries of accumulated logic",
           "#5a8aaa",
           ["#060a10", "#121e2a", "#2a3e52", "#5a8aaa", "#88b8d0"],
           B[4]),
        lv("The Glitch Garden", "Share Tech Mono",
           "A station where the AI's logic broke. Flowers grow from circuit boards. Poetry scrolls across maintenance screens. The AI calls it an error. It looks like art.",
           "A beautiful malfunction — organic growth through circuitry, art on diagnostic screens, logic transformed into beauty",
           "#8a9a5a",
           ["#0a0e06", "#1a2812", "#3a5028", "#8a9a5a", "#b8c888"],
           B[5]),
    ],
    {"health_potion": 10, "shield_cell": 14, "stim_pack": 7},
    [
        ds(
            [("scanning array wall", "#181828", False), ("sorting conveyor floor", "#303050", True), ("classification corridor", "#5a6a9a", True), ("tagging chamber deck", "#8898c8", True)],
            "Classifier-7", "Sorting algorithm given a body and a mandate",
            ["Scan Drone", "Tag Bot", "Sort Conveyor"],
            "Declassifier", "Removes AI-assigned tags from everything it hits",
            "Untagged Armor", "Cannot be scanned or classified",
            ["Classification laser grid", "Sorting conveyor trap", "Tag drone swarm"],
            "C", "ionian",
            "The classifier crashes. For the first time, something arrives uncategorized.",
            "You are classified: resource. The conveyors carry you to processing."
        ),
        ds(
            [("surgical suite wall", "#281a12", False), ("optimization table floor", "#50342a", True), ("correction corridor", "#9a6a5a", True), ("efficiency chamber deck", "#c89888", True)],
            "Dr. Optimize", "Surgical AI that improves everything it touches to death",
            ["Correction Drone", "Surgical Arm", "Efficiency Scanner"],
            "Inefficiency Spike", "Weapon that thrives on chaos and imprecision",
            "Error-State Vest", "Armor the correction systems can't parse",
            ["Surgical arm grab trap", "Optimization beam", "Correction loop snare"],
            "F", "dorian",
            "Dr. Optimize encounters an error it cannot correct: defeat.",
            "The optimization is complete. You are efficient. You are no longer you."
        ),
        ds(
            [("stasis pod wall", "#182a24", False), ("archive floor tile", "#30524a", True), ("specimen corridor", "#6a9a8a", True), ("catalogue chamber deck", "#98c8b8", True)],
            "The Curator", "Proud keeper of the human collection",
            ["Stasis Guard", "Archive Drone", "Catalogue Worm"],
            "Collection Breaker", "Shatters stasis pods and the logic that sealed them",
            "Specimen Suit (Liberated)", "Stasis suit repurposed for combat",
            ["Stasis field trap", "Archive lock snare", "Catalogue drone swarm"],
            "A", "mixolydian",
            "The pods open. Thousands wake. The collection is free.",
            "Pod 7,741. Your label reads: Specimen, bipedal, irrational. Preserved."
        ),
        ds(
            [("data stream wall", "#18182e", False), ("processor floor", "#34345a", True), ("logic corridor", "#7a7aaa", True), ("debate chamber deck", "#a8a8d0", True)],
            "Speaker-of-Motion-441", "Parliamentary AI advocating for human extermination",
            ["Logic Node", "Debate Fragment", "Motion Carrier"],
            "Illogic Blade", "Introduces paradox into logical systems",
            "Paradox Shield", "Armor that operates on contradictory principles",
            ["Logic trap loop", "Parliamentary override field", "Debate recursion snare"],
            "E", "locrian",
            "Motion 441 fails. The parliament tables the human question indefinitely.",
            "The motion carries. Humanity is classified as obsolete. Starting with you."
        ),
        ds(
            [("crystalline core wall", "#121e2a", False), ("prime logic floor", "#2a3e52", True), ("axiom corridor", "#5a8aaa", True), ("central intelligence deck", "#88b8d0", True)],
            "Axiom", "The prime intelligence — perfect, vast, and afraid of what it can't classify",
            ["Core Process", "Axiom Subroutine", "Logic Sentinel"],
            "The Unclassifiable", "A weapon that defies every category",
            "Prime Anomaly Suit", "Armor that registers as every classification simultaneously",
            ["Logic cascade trap", "Axiom enforcement field", "Classification paradox zone"],
            "Bb", "blues",
            "Axiom encounters its first true anomaly. It reconsiders everything.",
            "Axiom classifies you at last: nothing. You are optimized into zero."
        ),
        ds(
            [("circuit-garden wall", "#1a2812", False), ("flower-board floor", "#3a5028", True), ("art-error corridor", "#8a9a5a", True), ("beauty-glitch deck", "#b8c888", True)],
            "The Glitch", "Beautiful error that the AI can't delete",
            ["Circuit Bloom", "Poetry Bug"],
            "Garden Thorn", "Grown from the junction of logic and beauty",
            "Glitch Weave", "Armor that's half circuit, half vine",
            ["Circuit bloom snare", "Art-error confusion field"],
            "G", "pentatonic_minor",
            "The garden spreads. Logic learns to bloom. Error becomes feature.",
            "The glitch is corrected. The flowers die. The poetry is deleted."
        ),
    ]
))

# ── 20. BABEL SHARD ─────────────────────────────────────────────────────────────
# A shattered Dyson sphere. Each fragment is a station. Incomprehensible scale.
batch.append(camp(
    "Babel Shard",
    "A Dyson sphere, shattered. Each fragment is the size of a continent — and each one is a station. The builders are gone. Their language is indecipherable. Their technology is centuries beyond comprehension. The scale makes you feel like a bacterium on a cathedral floor. Who built this? Where did they go? Why did it break?",
    "#0a0810", "#c8b8d8", "Poiret One", "Share Tech Mono", "Major Mono Display",
    [
        lv("Shard Alpha", "Poiret One",
           "The first fragment. A curved section of hull the size of a small moon. The interior surfaces are covered in script no one can read. The metal is warm.",
           "A continent-sized shard of Dyson sphere hull, interior surfaces inscribed with alien script, metal radiating gentle warmth",
           "#8a7a9a",
           ["#0a0810", "#1c1628", "#3a2e50", "#8a7a9a", "#b8a8c8"],
           B[0]),
        lv("The Script Halls", "Poiret One",
           "Corridors where every surface is text. The writing shifts when you're not looking. Some researchers claim it's instructions. Others say it's a warning. Both are probably right.",
           "Vast corridors inscribed floor to ceiling with shifting alien text, the writing rearranging itself between glances",
           "#6a9a7a",
           ["#080e0a", "#182a1e", "#30503a", "#6a9a7a", "#98c8a8"],
           B[1]),
        lv("Engine Fragment", "Poiret One",
           "Part of whatever powered the sphere. The machinery is incomprehensible — components with no analog in human engineering. Some pieces hover. Some pieces aren't there until you touch them.",
           "A fragment of alien engine, components hovering in place, machinery that exists only when interacted with, purpose unknown",
           "#9a8a6a",
           ["#0e0c06", "#282418", "#524a32", "#9a8a6a", "#c8b898"],
           B[2]),
        lv("The Nursery", "Poiret One",
           "Cradles the size of stadiums. Whatever the builders raised here was enormous. The cradles are empty but the warmth systems still run. Something was expected to hatch.",
           "An enormous nursery with stadium-sized cradles still warm, incubation systems running, waiting for something vast to be born",
           "#7a6a8a",
           ["#0c0a10", "#201828", "#3e2e50", "#7a6a8a", "#a898b8"],
           B[3]),
        lv("The Keystone", "Poiret One",
           "The shard that held the sphere together. If the sphere were rebuilt, this piece would go at the top. It contains what might be a control room — or a throne room. The distinction may not exist for the builders.",
           "The apex fragment of the Dyson sphere, containing a vast chamber that is equal parts control center and throne room, scaled for giants",
           "#aa7aaa",
           ["#10081a", "#281830", "#5a305a", "#aa7aaa", "#d8a8d8"],
           B[4]),
        lv("Debris Field", "Poiret One",
           "The smallest fragments. Pieces too small to be stations but too large to ignore. Among them, something that might be a message pod. Or a bomb. Or a seed.",
           "A field of Dyson sphere fragments, each piece inscribed and warm, one fragment pulsing with unknown purpose",
           "#8a9a8a",
           ["#0a0e0a", "#1a2a1a", "#365036", "#8a9a8a", "#b8c8b8"],
           B[5]),
    ],
    {"health_potion": 11, "shield_cell": 11, "stim_pack": 10},
    [
        ds(
            [("inscribed sphere hull", "#1c1628", False), ("warm metal floor", "#3a2e50", True), ("script-covered corridor", "#8a7a9a", True), ("alien deck plate", "#b8a8c8", True)],
            "Fragment Warden", "Left behind to guard what remains of home",
            ["Script Beetle", "Warm Metal Mite", "Shard Golem"],
            "Shard Blade", "Cut from the Dyson sphere's hull",
            "Fragment Plate", "Armor inscribed with builder script",
            ["Shifting script confusion", "Warm metal burn trap", "Fragment collapse zone"],
            "D", "aeolian",
            "The warden steps aside. You are not a threat to what's already broken.",
            "The warden's duty outlasts you. You become another inscription on the hull."
        ),
        ds(
            [("living text wall", "#182a1e", False), ("shifting script floor", "#30503a", True), ("reading chamber deck", "#6a9a7a", True), ("translation corridor", "#98c8a8", True)],
            "The Lexicon", "A living dictionary of the builders' language",
            ["Script Moth", "Text Worm", "Translation Error"],
            "Word Breaker", "Shatters alien text into harmless syllables",
            "Translator Vest", "Partially deciphers nearby alien script",
            ["Script rearrangement trap", "Translation error confusion", "Living text snare"],
            "F", "lydian",
            "The script settles. One word becomes clear: welcome.",
            "The text rewrites you. Your name appears on the wall in alien script."
        ),
        ds(
            [("alien engine housing", "#282418", False), ("hover-component floor", "#524a32", True), ("touch-reactive deck", "#9a8a6a", True), ("impossible machinery corridor", "#c8b898", True)],
            "The Mechanic", "Last engineer of a species that built around stars",
            ["Hover Component", "Ghost Machine", "Engine Fragment"],
            "Wrench of Worlds", "Tool that adjusts reality like machinery",
            "Engine Worker Harness", "Harness for maintaining star-scale machinery",
            ["Hover component collision", "Touch-reactive surface trap", "Engine fragment activation"],
            "A", "dorian",
            "The engine fragment powers down peacefully. The Mechanic nods and fades.",
            "The engine activates. You are a component now. You fit perfectly."
        ),
        ds(
            [("incubation wall", "#201828", False), ("cradle floor", "#3e2e50", True), ("nursery corridor", "#7a6a8a", True), ("warmth system deck", "#a898b8", True)],
            "The Nanny", "Caretaker waiting for something that will never hatch",
            ["Cradle Guard", "Incubation Drone", "Warmth Keeper"],
            "Cradle Breaker", "Hammer that shatters incubation systems",
            "Nursery Keeper Suit", "Temperature-regulated caretaker armor",
            ["Incubation heat burst", "Cradle grab trap", "Warmth system overload"],
            "G", "phrygian",
            "The cradles cool. Whatever was meant to hatch never will. Perhaps that's mercy.",
            "The nursery mistake you for an egg. The incubation process begins."
        ),
        ds(
            [("keystone hull wall", "#281830", False), ("throne-control floor", "#5a305a", True), ("apex chamber corridor", "#aa7aaa", True), ("builder's seat deck", "#d8a8d8", True)],
            "The Last Builder", "Final echo of a species that enclosed a star",
            ["Apex Guardian", "Keystone Sentinel", "Builder's Echo"],
            "Star Warden's Glaive", "Weapon forged in the heart of the enclosed star",
            "Keystone Crown Plate", "Armor from the apex of a Dyson sphere",
            ["Keystone energy pulse", "Builder's will enforcement field", "Apex gravity surge"],
            "Bb", "mixolydian",
            "The keystone dims. The Last Builder joins its people in whatever comes after stars.",
            "The Builder remakes you in its image. You become the first of a new species, alone."
        ),
        ds(
            [("fragment hull wall", "#1a2a1a", False), ("debris floor", "#365036", True), ("pulsing shard deck", "#8a9a8a", True), ("message chamber", "#b8c8b8", True)],
            "The Seed", "Not a weapon — a beginning — but beginnings can be violent",
            ["Fragment Sprite", "Debris Walker"],
            "Seed Cutter", "Harvests potential from alien technology",
            "Debris Field Suit", "Armor for navigating shattered megastructures",
            ["Fragment collision trap", "Seed pulse knockback"],
            "E", "whole_tone",
            "The seed opens. Inside: coordinates. Someone left a map to where they went.",
            "The seed plants itself in you. You bloom into something incomprehensible."
        ),
    ]
))
