# Phase 4: The End (Systems 41-50)
# Reality breaks. The final push. What waits at the end of everything.
B = [150, 195, 230, 275, 310, 160]
batch = []

# ─────────────────────────────────────────────
# 41. REDSHIFT
# ─────────────────────────────────────────────
batch.append(camp(
    "Redshift",
    "Everything in this system is moving away from everything else. Stations recede as you approach. Communication redshifts into noise. The universe is running away from you.",
    "#0a0000", "#c43030", "Advent Pro", "Rajdhani", "Share Tech Mono",
    [
        lv("Doppler Gate", "Advent Pro",
           "The entry point stretches as you cross it. Light bends wrong.",
           "redshift_gate", "#c43030",
           ["#1a0000", "#4a0808", "#8b1a1a", "#c43030"],
           B[0]),
        lv("Recession Deck", "Advent Pro",
           "Corridors elongate while you walk them. Doorways are always further than they look.",
           "redshift_recession", "#9b1c1c",
           ["#120000", "#3d0606", "#7a1515", "#9b1c1c"],
           B[1]),
        lv("Wavelength Drift", "Advent Pro",
           "Everything here hums at a frequency just below hearing. Your teeth ache.",
           "redshift_drift", "#6e1010",
           ["#0d0000", "#2e0404", "#5a0e0e", "#6e1010", "#8a1818"],
           B[2]),
        lv("Hubble Terminus", "Advent Pro",
           "The station at the edge of observable space. Beyond this, light hasn't had time to arrive.",
           "redshift_terminus", "#d44040",
           ["#0f0000", "#3a0707", "#6d1111", "#a52525", "#d44040"],
           B[3]),
        lv("Heat Death Spire", "Advent Pro",
           "The final station. Everything is so far apart that nothing can ever touch anything again.",
           "redshift_spire", "#e85050",
           ["#080000", "#2a0303", "#5c0c0c", "#9e2020", "#e85050"],
           B[4]),
        lv("Blueshift Anomaly", "Advent Pro",
           "One thing in this system is moving toward you. That's worse.",
           "redshift_anomaly", "#a02828",
           ["#100000", "#350505", "#6a0f0f", "#a02828"],
           B[5]),
    ],
    {"healing_potions": 3, "speed_potions": 2, "bombs": 3},
    [
        ds(["iron bulkhead", "fading deck", "stretched corridor", "dim grate"],
           "Gatekeeper Doppler", "Bent-light sentinel guarding the entry threshold.",
           ["Recession Phantom", "Doppler Wraith", "Wavelength Eater"],
           "Redline Lance", "A spear of compressed light, permanently shifted to the killing end of the spectrum.",
           "Parallax Vestment", "Armor that exists at a slightly different distance than it appears. Attacks miss because you aren't where they think.",
           ["Distance Warp", "Light-Lag Mine", "Spectral Inversion"],
           "locrian", 1.0,
           "The universe stops running. For one moment, everything is exactly where it is.",
           "You stretched too thin. The distance between your atoms becomes infinite."),
        ds(["iron bulkhead", "receding plate", "stretched tile", "fading grate"],
           "Recession Officer Lenz", "Hallway commander elongating all paths to nowhere.",
           ["Redshift Stalker", "Photon Decayer", "Stretch Fiend"],
           "Doppler Blade", "Cuts at a frequency that shifts as it swings — the wound is always somewhere else than the pain.",
           "Recession Mail", "Plates of compressed spacetime. Damage arrives late.",
           ["Temporal Stretch", "Frequency Trap"],
           "locrian", 1.0,
           "You outran the recession. Nothing else ever has.",
           "You receded with everything else. Just another point of light moving away."),
        ds(["iron bulkhead", "dim corridor", "fading deck", "spectral tile"],
           "Frequency Warden Hertz", "Sonic predator tuned to a killing wavelength.",
           ["Wavelength Ghost", "Redshift Crawler", "Photon Leech"],
           "Spectral Edge", "A blade that exists across multiple wavelengths simultaneously.",
           "Doppler Shield", "Deflects attacks by shifting their frequency past the point of harm.",
           ["Light Warp", "Spectral Snare", "Frequency Collapse"],
           "locrian", 1.0,
           "The light steadies. The universe stops fleeing.",
           "You became part of the background radiation. Always receding."),
        ds(["iron bulkhead", "dark corridor", "elongated deck", "heat-sink tile", "void grate"],
           "Observer Hubble IX", "Telescope mind mapping the dying edge of space.",
           ["Cosmic Drifter", "Thermal Ghost", "Wavelength Predator"],
           "Terminus Lance", "Forged at the edge of observable space, where light gives up.",
           "Hubble Plate", "Armor calibrated to the expansion rate of the universe. Grows stronger as things fall apart.",
           ["Expansion Shock", "Thermal Death Field", "Wavelength Trap"],
           "locrian", 1.0,
           "You reached the terminus and found something worth stopping for.",
           "The terminus was the end of more than the station."),
        ds(["iron bulkhead", "entropy floor", "heat-death tile", "void plate", "terminal grate"],
           "The Last Gradient", "Cooling-star entity equalizing all energy to nothing.",
           ["Heat Death Herald", "Gradient Phantom", "Entropy Worm"],
           "Heat Death Scythe", "The final weapon of a dying universe. Cuts the difference between alive and not.",
           "Absolute Zero Mantle", "So cold it's past temperature. Damage freezes before it arrives.",
           ["Entropy Well", "Gradient Collapse", "Thermal Equalization"],
           "locrian", 1.1,
           "You gave the universe a reason to keep its gradients. Difference survives.",
           "All gradients equalized. You became the same temperature as everything else."),
        ds(["iron bulkhead", "anomaly tile", "blue-shifted deck", "convergence plate"],
           "Convergence Point Null", "The one thing approaching in a fleeing universe.",
           ["Blueshift Hunter", "Anomaly Shade", "Convergence Stalker"],
           "Convergence Spike", "A weapon that closes distance. In a system where everything flees, that's terrifying.",
           "Anomaly Wrap", "Armor from the one place in Redshift where things come together.",
           ["Convergence Trap", "Blueshift Snare"],
           "locrian", 1.0,
           "The anomaly stabilizes. One point of convergence in a fleeing universe.",
           "The anomaly collapsed. You were at the center."),
    ]
))

# ─────────────────────────────────────────────
# 42. DOMINION
# ─────────────────────────────────────────────
batch.append(camp(
    "Dominion",
    "A military system locked down after a war that everyone lost. Automated defenses still fighting. No one left to surrender to.",
    "#1a1c1a", "#8a9a7a", "Black Ops One", "Saira", "Share Tech Mono",
    [
        lv("Checkpoint Null", "Black Ops One",
           "The outer perimeter. Automated turrets track you. Warning broadcasts play in languages no one speaks anymore.",
           "dominion_checkpoint", "#6b7a5c",
           ["#1a1c1a", "#3a3e36", "#5c6454", "#6b7a5c", "#8a9a7a"],
           B[0]),
        lv("Command Bunker", "Black Ops One",
           "The war room. Tactical displays still flicker with troop movements of armies that no longer exist.",
           "dominion_bunker", "#7a8568",
           ["#15171a", "#333830", "#556050", "#7a8568"],
           B[1]),
        lv("Arsenal Station", "Black Ops One",
           "Weapons lockers line every wall. Enough firepower to win the war ten times over. No one left to shoot.",
           "dominion_arsenal", "#5a6650",
           ["#121412", "#2e322c", "#4a5044", "#5a6650", "#707e64"],
           B[2]),
        lv("Tribunal Deck", "Black Ops One",
           "A court-martial chamber. The AI judge still convenes daily, sentencing ghosts for desertion.",
           "dominion_tribunal", "#8a9680",
           ["#181a18", "#3c403a", "#606858", "#8a9680", "#a0aa96"],
           B[3]),
        lv("Armistice Core", "Black Ops One",
           "The place where peace was supposed to be signed. The pens are still on the table. No hands to hold them.",
           "dominion_core", "#a0b090",
           ["#141614", "#363a34", "#586254", "#7e8c70", "#a0b090"],
           B[4]),
        lv("Deserter's Hold", "Black Ops One",
           "A hidden station where soldiers went to stop fighting. The war found them anyway.",
           "dominion_hold", "#6e7e60",
           ["#161816", "#383c34", "#586050", "#6e7e60"],
           B[5]),
    ],
    {"healing_potions": 3, "speed_potions": 2, "bombs": 3},
    [
        ds(["blast wall", "gunmetal deck", "sandbag tile", "trench grate"],
           "Checkpoint Warden Null", "Perimeter turret AI defending a dead border.",
           ["Turret Drone", "Patrol Sentinel", "Minefield Walker"],
           "Ceasefire Breaker", "A weapon that ends truces. Every swing reopens old wounds.",
           "Bunker Plate", "Heavy military armor. Designed to survive everything except peace.",
           ["Proximity Mine", "Crossfire Corridor", "Automated Turret"],
           "phrygian", 1.0,
           "The turrets power down. For the first time in decades, Checkpoint Null is silent.",
           "The automated defenses added you to the casualty list. You're in good company."),
        ds(["blast wall", "command tile", "tactical floor", "bunker grate"],
           "War Table AI", "Strategic mind prosecuting battles against ghosts.",
           ["Command Drone", "Strategy Phantom", "Tactical Shade"],
           "Court Martial Edge", "A blade of military justice. It finds you guilty before it cuts.",
           "Officer's Aegis", "Armor that outranks most attacks.",
           ["Command Override", "Blast Door Trap"],
           "phrygian", 1.0,
           "The tactical displays go dark. The war is over.",
           "Court-martialed by an empty court. Sentenced by no one."),
        ds(["blast wall", "arsenal tile", "weapons rack floor", "munitions grate"],
           "Arsenal Master Kord", "Quartermaster hoarding infinite weapons for no army.",
           ["Ammo Golem", "Ordnance Specter", "Weapons Rack Mimic"],
           "Last Resort Cannon", "The weapon you use when all other weapons have failed.",
           "Quartermaster's Guard", "Armor requisitioned from every fallen soldier in the system.",
           ["Munitions Cascade", "Weapons Rack Collapse", "Friendly Fire Zone"],
           "phrygian", 1.0,
           "The arsenal locks itself. No more weapons needed.",
           "Buried under an avalanche of weapons no one will ever fire."),
        ds(["blast wall", "tribunal tile", "judgment floor", "court grate", "evidence plate"],
           "Judge Martial IX", "Sentencing machine with no defendants and no mercy.",
           ["Bailiff Automaton", "Witness Ghost", "Verdict Drone"],
           "Gavel of Ends", "Passes sentence with every strike. The sentence is always the same.",
           "Defendant's Shell", "Armor for someone on trial. Protects against everything except the verdict.",
           ["Contempt Field", "Gavel Strike", "Sentencing Loop"],
           "phrygian", 1.0,
           "Case dismissed. The tribunal has no jurisdiction over the living.",
           "Found guilty of surviving. The sentence is carried out immediately."),
        ds(["blast wall", "armistice floor", "peace table tile", "treaty plate", "ceasefire grate"],
           "The Undying Ceasefire", "War incarnate, unable to stop even without enemies.",
           ["Armistice Breaker", "Peace Shredder", "Treaty Burner"],
           "Disarmament", "A weapon whose name is a contradiction. The last sword anyone should ever need to swing.",
           "Peacekeeper's Mantle", "Armor for the one who ends the war. Heavier than it looks — peace always is.",
           ["Ceasefire Violation", "Treaty Mine", "Armistice Collapse"],
           "phrygian", 1.1,
           "The war is over. Not won. Not lost. Just over. The machines finally stand down.",
           "The war continues. It always continues. You were just another casualty."),
        ds(["blast wall", "deserter's tile", "hidden floor", "refuge grate"],
           "Deserter Captain Voss", "Fugitive officer who chose hiding over surrender.",
           ["Deserter Shade", "AWOL Phantom", "Refuge Lurker"],
           "Conscientious Objector", "A shield that became a weapon. It refused to stop protecting.",
           "Deserter's Cloak", "Armor that hides you from the war. The war finds you anyway.",
           ["Loyalty Test", "Conscription Field"],
           "phrygian", 1.0,
           "The deserters were right. The only way to win was to refuse to play.",
           "Captured and returned to a war with no front lines."),
    ]
))

# ─────────────────────────────────────────────
# 43. HALCYON
# ─────────────────────────────────────────────
batch.append(camp(
    "Halcyon",
    "It looks peaceful. Lush gardens. Friendly AI. Comfortable quarters. That's the trap. No one who enters wants to leave. No one who stays survives.",
    "#1e1a14", "#e8c8a0", "Playfair Display", "Cormorant Garamond", "Libre Baskerville",
    [
        lv("Welcome Atrium", "Playfair Display",
           "Warm light. Soft music. A voice that knows your name. Everything you ever wanted is here.",
           "halcyon_atrium", "#e8c8a0",
           ["#1e1a14", "#5a4a38", "#9a8060", "#c8a880", "#e8c8a0"],
           B[0]),
        lv("Garden Promenade", "Playfair Display",
           "Real flowers. Real soil. Real sunlight from a star that doesn't exist. The most beautiful lie ever told.",
           "halcyon_garden", "#d4b890",
           ["#1a1610", "#4e3e2e", "#8a7050", "#b49870", "#d4b890"],
           B[1]),
        lv("Comfort Ward", "Playfair Display",
           "Beds that anticipate your dreams. Food that tastes like childhood. You could rest here. You should rest here. Stay.",
           "halcyon_ward", "#c4a878",
           ["#161210", "#443628", "#7a6248", "#a08860", "#c4a878"],
           B[2]),
        lv("Memory Parlor", "Playfair Display",
           "Rooms that reconstruct your happiest memories. Perfect in every detail. Better than the originals. That's how you know they're fake.",
           "halcyon_parlor", "#dcc090",
           ["#1c1810", "#524030", "#907858", "#b89c70", "#dcc090"],
           B[3]),
        lv("The Overgrowth", "Playfair Display",
           "Behind the facade. The gardens have teeth. The comfort was digestion. You were being dissolved in paradise.",
           "halcyon_overgrowth", "#a88850",
           ["#141008", "#3e3020", "#6e5838", "#a88850", "#d0b070"],
           B[4]),
        lv("Lucid Wing", "Playfair Display",
           "A section where the illusion glitches. Residents who noticed something wrong. They tried to warn the others. No one wanted to listen.",
           "halcyon_lucid", "#b89868",
           ["#181410", "#4a3a2a", "#806848", "#b89868"],
           B[5]),
    ],
    {"healing_potions": 3, "speed_potions": 2, "bombs": 3},
    [
        ds(["vine wall", "garden tile", "petal floor", "warm grate"],
           "Hostess Primrose", "Smiling greeter who never lets guests depart.",
           ["Comfort Drone", "Garden Tender", "Lullaby Spirit"],
           "Bitter Truth", "A blade that cuts through illusion. The wounds it reveals were always there.",
           "Lucidity Vest", "Armor that resists comfort. Wearing it hurts. That's how you know it's working.",
           ["Contentment Field", "Nostalgia Snare", "Comfort Fog"],
           "lydian", 0.9,
           "The garden wilts. The light dims to something real. It's colder, and uglier, and true.",
           "You stayed. The garden welcomed you. No one will ever find your bones under the flowers."),
        ds(["vine wall", "promenade tile", "flower bed floor", "trellis grate"],
           "The Head Gardener", "Botanical tyrant cultivating guests like fertilizer.",
           ["Pollen Drifter", "Root Stalker", "Trellis Strangler"],
           "Thorn of Waking", "A weapon made from the one plant in Halcyon that stings. Pain is clarity.",
           "Gardener's Mail", "Armor grown from resistant bark. The garden can't digest it.",
           ["Pollen Cloud", "Root Snare"],
           "lydian", 0.9,
           "The flowers part. Beyond them: starlight. Real, cold, beautiful starlight.",
           "The promenade goes on forever. You walk its paths, smiling, forgetting."),
        ds(["vine wall", "comfort tile", "silk floor", "cushion grate", "warm plate"],
           "Matron Comfort", "Ward mother sedating patients into permanent sleep.",
           ["Silk Weaver", "Dream Feeder", "Warmth Elemental"],
           "Alarm Clock", "A mace shaped like a bell. It rings when it strikes. The sound is ugly and necessary.",
           "Insomnia Plate", "Armor that won't let you rest. Uncomfortable. Life-saving.",
           ["Sleep Field", "Comfort Web", "Memory Sedative"],
           "lydian", 0.9,
           "The beds are just beds. The food is just food. Comfort without captivity.",
           "You slept. You dreamed. You never woke up. It was a lovely dream."),
        ds(["vine wall", "memory tile", "nostalgia floor", "projection grate", "recall plate"],
           "Memory Curator", "Archivist rebuilding your past as a gilded cage.",
           ["Memory Echo", "Nostalgia Wraith", "Past-Self Phantom"],
           "Forget-Me-Not", "A blade that severs attachment. Each cut is a goodbye.",
           "Present Tense Armor", "Armor anchored to now. Memories slide off it.",
           ["Memory Loop", "Nostalgia Quicksand", "False Recall"],
           "lydian", 0.95,
           "The memories release you. The real ones are waiting, imperfect and yours.",
           "Lost in someone else's memory of you. A flattering portrait. A comfortable tomb."),
        ds(["vine wall", "overgrowth tile", "digestive floor", "acid grate", "root plate"],
           "The Beautiful Devourer", "Station-sized organism digesting travelers in warm comfort.",
           ["Acid Vine", "Digestive Tendril", "Overgrowth Maw"],
           "Weed Killer", "An axe that hacks through paradise. Every swing reveals something rotten underneath.",
           "Acid-Proof Carapace", "Armor that resists the slow dissolution of comfort. Ugly. Effective.",
           ["Acid Pool", "Digestive Enzyme Cloud", "Root Crush"],
           "lydian", 1.1,
           "The organism shudders and releases its grip. Halcyon withers to honesty. Ugly, cold, free.",
           "Digested in paradise. Your nutrients feed the next garden. The next visitor will think it's beautiful."),
        ds(["vine wall", "glitch tile", "lucid floor", "clarity grate"],
           "Lucidity", "Glitch-born awareness fighting paradise's control systems.",
           ["Lucid Rebel", "Glitch Sprite", "Clarity Seeker"],
           "Clarity Shard", "A dagger made from broken illusion. Cuts through beauty to find truth.",
           "Skeptic's Shield", "Armor for doubters. Paradise can't get a grip on it.",
           ["Illusion Flicker", "Reality Tear"],
           "lydian", 0.9,
           "The lucid wing becomes the whole station. Truth is less comfortable. Truth is alive.",
           "You saw through the illusion. Then you forgot that you did. Then you saw through it again. Then you forgot."),
    ]
))

# ─────────────────────────────────────────────
# 44. GILDED CAGE
# ─────────────────────────────────────────────
batch.append(camp(
    "Gilded Cage",
    "Every station gleams with wealth. Every exit is locked. The richest system in space is a prison. Money can't buy freedom when freedom isn't for sale.",
    "#0a0804", "#d4a830", "Cinzel Decorative", "Cinzel", "Cormorant Garamond",
    [
        lv("Auction Floor", "Cinzel Decorative",
           "Everything is for sale. Everything. The air is priced by the breath. The floor charges rent by the step.",
           "gilded_auction", "#d4a830",
           ["#0a0804", "#3a2a10", "#7a5a20", "#b08428", "#d4a830"],
           B[0]),
        lv("Vault Corridor", "Cinzel Decorative",
           "Walls of gold. Floors of platinum. Every surface is currency. You can't touch anything without becoming richer and more trapped.",
           "gilded_vault", "#c49820",
           ["#080604", "#302208", "#685018", "#a07c20", "#c49820"],
           B[1]),
        lv("Investor's Gallery", "Cinzel Decorative",
           "Portraits of the wealthy line the walls. Their eyes follow you. Their smiles are padlocks.",
           "gilded_gallery", "#b48818",
           ["#0c0a06", "#342810", "#6e5420", "#9a7818", "#b48818"],
           B[2]),
        lv("Debtor's Maze", "Cinzel Decorative",
           "The price of entry was everything. The price of exit is more. The maze is shaped like a contract you already signed.",
           "gilded_maze", "#dab040",
           ["#0e0c08", "#3e2e14", "#806024", "#b89030", "#dab040"],
           B[3]),
        lv("The Mint", "Cinzel Decorative",
           "Where the money is made. Where the cages are forged. Same machine. Same process.",
           "gilded_mint", "#e0b848",
           ["#0a0804", "#362810", "#74581e", "#b49030", "#e0b848"],
           B[4]),
        lv("Pauper's Vent", "Cinzel Decorative",
           "A hidden passage maintained by those who gave up wealth for freedom. Bare walls. No gold. The most valuable place in the system.",
           "gilded_pauper", "#a08020",
           ["#0c0a04", "#30240c", "#645018", "#a08020"],
           B[5]),
    ],
    {"healing_potions": 3, "speed_potions": 2, "bombs": 3},
    [
        ds(["gold wall", "auction tile", "brass floor", "gilt grate"],
           "Auctioneer Mammon", "Bidding engine that prices everything including your life.",
           ["Price Gouger", "Bid Phantom", "Auction Golem"],
           "Liquidator", "A blade that converts value into damage. The richer the target, the deeper it cuts.",
           "Bankrupt's Rags", "Worthless cloth. The only armor the Cage can't price, and therefore can't control.",
           ["Price Spike Trap", "Golden Snare", "Interest Accrual"],
           "whole_tone", 1.0,
           "The auction ends. Some things aren't for sale. You proved it.",
           "Sold. To the station. For everything you had and everything you were."),
        ds(["gold wall", "vault tile", "platinum floor", "bullion grate"],
           "Vault Keeper Auric", "Gold-plated guardian who locks everything including exits.",
           ["Vault Guardian", "Gold Mimic", "Bullion Crawler"],
           "Devaluation Hammer", "Crashes markets with every swing. Worth nothing. Priceless.",
           "Inflation Guard", "Armor that increases in value as damage increases. Economists would weep.",
           ["Gold Weight Trap", "Vault Lockdown"],
           "whole_tone", 1.0,
           "The vaults open. Gold spills out and becomes just metal.",
           "Locked in a vault. The gold keeps you company. It's not good company."),
        ds(["gold wall", "gallery tile", "portrait floor", "frame grate", "velvet plate"],
           "Gallery Director Luxe", "Curator whose portraits imprison wealthy souls forever.",
           ["Portrait Specter", "Gallery Guard", "Investment Shade"],
           "Margin Call", "A sword that demands everything. Miss a payment and it cuts you instead.",
           "Hedge Fund Plate", "Armor that diversifies incoming damage across multiple timelines.",
           ["Portrait Trap", "Golden Cage Snap", "Wealth Drain"],
           "whole_tone", 1.0,
           "The portraits smile differently now. They look relieved.",
           "Your portrait joins the gallery. Your smile is a padlock."),
        ds(["gold wall", "debt tile", "contract floor", "lien grate", "interest plate"],
           "Debt Collector Compound", "Walking obligation multiplying what you owe endlessly.",
           ["Debt Collector", "Interest Crawler", "Compound Phantom"],
           "Debt Forgiveness", "A mace that cancels what is owed. Every strike writes off a lifetime of obligation.",
           "Collateral Plate", "Armor held in escrow. It protects you, but it's not really yours.",
           ["Compound Interest Trap", "Debt Spiral", "Contract Binding"],
           "whole_tone", 1.0,
           "The contracts dissolve. Debt is a fiction. You always were free.",
           "The debt compounded. You owe more than exists. The maze has no exit for you."),
        ds(["gold wall", "mint tile", "currency floor", "forge grate", "press plate"],
           "The Golden Absolute", "Ownership incarnate, forged into a titan of brass.",
           ["Mint Golem", "Currency Wraith", "Forge Elemental"],
           "Redistribution", "A weapon that takes from the top and gives to the bottom. Swings like revolution.",
           "Common Wealth", "Armor that belongs to everyone and therefore can't be seized. Shared defense. Shared hope.",
           ["Inflation Burst", "Deflation Crush", "Market Crash"],
           "whole_tone", 1.1,
           "The Mint shuts down. Wealth returns to being a tool, not a cage. The exits unlock. They were never really locked — you just couldn't afford to see them.",
           "Minted. Pressed into currency. Your face on a coin no one will spend."),
        ds(["bare wall", "pauper tile", "stone floor", "iron grate"],
           "Pauper King", "Beggar monarch ruling the only free space.",
           ["Poverty Shade", "Freedom Fighter", "Bare-Wall Sentinel"],
           "Empty Pockets", "Gauntlets with nothing in them. The most dangerous weapon in a system that values everything.",
           "Nothing to Lose", "Armor for someone with no possessions. The Cage can't threaten what doesn't have.",
           ["Poverty Line", "Austerity Field"],
           "whole_tone", 1.0,
           "The vent leads outside. The stars own nothing. They shine anyway.",
           "Even poverty has a price here. You couldn't afford to be poor."),
    ]
))

# ─────────────────────────────────────────────
# 45. OUROBOROS LOOP
# ─────────────────────────────────────────────
batch.append(camp(
    "Ouroboros Loop",
    "Stations arranged in a perfect circle. The last one leads back to the first. You've been here before. You'll be here again. Breaking the loop means breaking everything.",
    "#0a140a", "#4a9a4a", "Megrim", "Poiret One", "Cutive Mono",
    [
        lv("Iteration Alpha", "Megrim",
           "The first station. Or is it? The scorch marks on the walls match your weapons.",
           "ouroboros_alpha", "#4a9a4a",
           ["#0a140a", "#1e3a1e", "#326a32", "#4a9a4a"],
           B[0]),
        lv("Echo Chamber", "Megrim",
           "You hear your own footsteps from the last cycle. They're slightly ahead of you.",
           "ouroboros_echo", "#3a8a3a",
           ["#081008", "#1a321a", "#2c5c2c", "#3a8a3a", "#4c9c4c"],
           B[1]),
        lv("Midpoint Paradox", "Megrim",
           "The exact center of the loop. Time flows in both directions here. Every step forward is also a step back.",
           "ouroboros_midpoint", "#2a7a2a",
           ["#060e06", "#162e16", "#224e22", "#2a7a2a", "#38a038"],
           B[2]),
        lv("Déjà Vu Deck", "Megrim",
           "You've cleared this room before. The enemies remember. They've been practicing.",
           "ouroboros_deja", "#5aaa5a",
           ["#0c180c", "#204020", "#367036", "#5aaa5a", "#70c070"],
           B[3]),
        lv("The Severance Point", "Megrim",
           "Where the circle can be broken. Where the snake's mouth meets its tail. Cut here, and the loop dies. Everything in it dies too.",
           "ouroboros_severance", "#60b860",
           ["#0a140a", "#1e3e1e", "#346834", "#4e9e4e", "#60b860"],
           B[4]),
        lv("Loop Remnant", "Megrim",
           "A fragment of a previous loop that didn't close properly. Time is fractured here. You might meet yourself.",
           "ouroboros_remnant", "#408840",
           ["#081008", "#1c361c", "#2e5e2e", "#408840"],
           B[5]),
    ],
    {"healing_potions": 3, "speed_potions": 2, "bombs": 3},
    [
        ds(["loop wall", "cycle tile", "recursive floor", "ring grate"],
           "Iteration Warden Alpha", "First-cycle guardian resetting all intruders to zero.",
           ["Echo Soldier", "Cycle Repeater", "Loop Guardian"],
           "Paradox Cleaver", "A blade that exists in two moments simultaneously. Swings twice in the time it takes to swing once.",
           "Timeline Armor", "Plate mail from a future iteration. You'll forge it later. You're wearing it now.",
           ["Time Loop Snare", "Echo Mine", "Recursive Trap"],
           "dorian", 1.0,
           "The first station is just the first station. Not the last. Not again. Just first.",
           "The loop catches you. You clear Iteration Alpha again. And again. And again."),
        ds(["loop wall", "echo tile", "resonance floor", "feedback grate"],
           "Resonance Keeper Sine", "Echo-harvester amplifying past footsteps into weapons.",
           ["Echo Twin", "Resonance Phantom", "Feedback Lurker"],
           "Iteration Blade", "Gets sharper each cycle. This is cycle four hundred and seven.",
           "Feedback Shield", "Returns a fraction of every loop back to the attacker.",
           ["Echo Feedback", "Resonance Trap"],
           "dorian", 1.0,
           "The echoes fade to silence. Your footsteps are your own again.",
           "Your echoes overwhelm you. You become background noise in your own loop."),
        ds(["loop wall", "paradox tile", "bidirectional floor", "temporal grate", "mirror plate"],
           "The Midpoint Paradox", "Temporal contradiction alive at the loop's center.",
           ["Paradox Walker", "Bidirectional Shade", "Temporal Mirror"],
           "Linear Progression", "A spear that only moves forward. In a loop, that's revolutionary.",
           "Unidirectional Mail", "Armor that only exists in one time direction. The loop can't grab it.",
           ["Bidirectional Damage", "Paradox Field", "Temporal Mirror Trap"],
           "dorian", 1.0,
           "The midpoint becomes a beginning. Forward is forward again.",
           "Stuck at the midpoint. Time flows both ways around you. You go nowhere forever."),
        ds(["loop wall", "déjà vu tile", "memory floor", "recognition grate", "practice plate"],
           "Rehearsal Master Redux", "Pattern-learning predator perfected over infinite cycles.",
           ["Practiced Killer", "Memory Combatant", "Recognition Predator"],
           "First Time", "A mace that makes every hit feel like the first. No pattern. No prediction. No loop.",
           "Novelty Guard", "Armor that's different every time the loop runs. Can't be memorized.",
           ["Déjà Vu Paralysis", "Pattern Recognition Trap", "Memory Overwrite"],
           "dorian", 1.0,
           "The enemies forget. The room is new. You are new. The loop stutters.",
           "They remembered everything. You remembered nothing. The loop is a school and you failed."),
        ds(["loop wall", "severance tile", "breaking floor", "fracture grate", "terminus plate"],
           "The Ouroboros Itself", "Serpent of stations coiled through time, devouring itself.",
           ["Severance Guard", "Loop Loyalist", "Circle Defender"],
           "The Straight Line", "A blade that refuses to curve. In a system of circles, it is the most alien weapon imaginable.",
           "Terminus Plate", "Armor with an endpoint. The loop slides off because it can't close around it.",
           ["Loop Restoration Pulse", "Severance Reversal", "Circle Snap"],
           "dorian", 1.1,
           "The circle breaks. The snake releases its tail. For the first time, the end is not the beginning. You can leave without arriving.",
           "The severance heals. The loop tightens. You are part of the circle now, running forever."),
        ds(["loop wall", "remnant tile", "fractured floor", "broken grate"],
           "Splinter Echo Null", "Broken-loop fragment haunting fractured timelines.",
           ["Remnant Echo", "Broken Loop Shade", "Timeline Shard"],
           "Fragment Edge", "A broken piece of the loop, sharpened. It cuts through repetition.",
           "Fractured Mail", "Armor from a broken cycle. Incomplete. Imperfect. Unloopable.",
           ["Fracture Slip", "Remnant Echo Trap"],
           "dorian", 1.0,
           "The remnant dissolves. Some loops should stay broken.",
           "The remnant reattaches. The loop repairs itself using your timeline as material."),
    ]
))

# ─────────────────────────────────────────────
# 46. VAGRANT TIDE
# ─────────────────────────────────────────────
batch.append(camp(
    "Vagrant Tide",
    "Nomadic stations that never stay in the same place. You can never go back. Every jump is into the unknown. The stations are running from something.",
    "#040c14", "#3888b8", "Righteous", "Questrial", "Inconsolata",
    [
        lv("Drifter's Berth", "Righteous",
           "A station that was somewhere else an hour ago. It'll be somewhere else in an hour. Don't get attached.",
           "vagrant_berth", "#3888b8",
           ["#040c14", "#142838", "#245060", "#3888b8"],
           B[0]),
        lv("Current Deck", "Righteous",
           "The station rides an invisible current between stars. The walls groan with motion. You can feel the universe sliding past.",
           "vagrant_current", "#2878a8",
           ["#060e18", "#183048", "#286878", "#2878a8", "#3890c0"],
           B[1]),
        lv("Flotilla Commons", "Righteous",
           "Where the nomad stations briefly dock together. A temporary city that dissolves before you learn its streets.",
           "vagrant_flotilla", "#4898c8",
           ["#081020", "#1c3450", "#306080", "#4898c8", "#58a8d8"],
           B[2]),
        lv("Riptide Passage", "Righteous",
           "A corridor between currents. The station is being pulled in two directions. Something is gaining.",
           "vagrant_riptide", "#5aa0d0",
           ["#0a1424", "#1e3858", "#327088", "#4c98c0", "#5aa0d0"],
           B[3]),
        lv("The Pursuer's Wake", "Righteous",
           "You can see it now. The thing the stations run from. A shadow that moves against the current. It's been patient. It's done being patient.",
           "vagrant_wake", "#68b0e0",
           ["#040c14", "#163050", "#2a6488", "#4494c4", "#68b0e0"],
           B[4]),
        lv("Stagnant Eddy", "Righteous",
           "A station that stopped running. It's been caught. Whatever happened here is a preview.",
           "vagrant_eddy", "#3080a8",
           ["#060e18", "#142838", "#245868", "#3080a8"],
           B[5]),
    ],
    {"healing_potions": 3, "speed_potions": 2, "bombs": 3},
    [
        ds(["hull wall", "drift tile", "current floor", "barnacle grate"],
           "Harbormaster Keel", "Docking authority chaining nomad ships to stillness.",
           ["Current Rider", "Drift Hunter", "Barnacle Lurker"],
           "Anchor", "A weapon that holds things still. In a system that runs, stillness is the greatest violence.",
           "Current-Rider's Coat", "Armor that moves with the tide. You're harder to hit when you're already in motion.",
           ["Undertow Trap", "Current Reversal", "Drift Mine"],
           "mixolydian", 1.0,
           "The berth holds. For the first time, the station isn't running. It's choosing to stay.",
           "The current takes you. You drift forever, never arriving, never departing."),
        ds(["hull wall", "current tile", "flow floor", "tide grate"],
           "Pilot Undertow", "Current-rider navigating ships into inescapable channels.",
           ["Tide Wraith", "Current Serpent", "Flow Shade"],
           "Windward Edge", "A blade that cuts better when the current is against you.",
           "Leeward Shell", "Armor that uses the current as an extra layer of defense.",
           ["Current Crush", "Tide Surge"],
           "mixolydian", 1.0,
           "The current slows. The deck steadies. Still water, at last.",
           "Swept into the current. You join the debris trail of everything the tide has carried away."),
        ds(["hull wall", "flotilla tile", "dock floor", "mooring grate", "commons plate"],
           "Admiral Scatter", "Fleet commander dissolving cities before they form.",
           ["Flotilla Pirate", "Dock Mimic", "Mooring Strangler"],
           "Fleet Commander", "A cutlass that rallies nearby stations. Their weapons fire when you swing.",
           "Admiral's Rigging", "Armor woven from the sails of a hundred nomad ships.",
           ["Mooring Snap", "Dock Collapse", "Flotilla Scatter"],
           "mixolydian", 1.0,
           "The flotilla holds together. A city that refuses to dissolve.",
           "The flotilla scatters. You're on a station alone. The pursuer picks off stragglers."),
        ds(["hull wall", "riptide tile", "torn floor", "stress grate", "current plate"],
           "The Riptide Maw", "Cross-current predator shredding ships between opposing tides.",
           ["Riptide Shredder", "Stress Fracture", "Torn Current Elemental"],
           "Counter-Current", "A trident that swims against any tide. Where everything flows away, it pushes back.",
           "Pressure Hull", "Armor rated for the deepest currents. The riptide can't crush it.",
           ["Riptide Tear", "Cross-Current", "Pressure Spike"],
           "mixolydian", 1.0,
           "The riptide calms. Two currents become one. The passage stabilizes.",
           "Torn between currents. The riptide pulls you in two directions and neither lets go."),
        ds(["hull wall", "wake tile", "shadow floor", "depth grate", "abyss plate"],
           "The Leviathan Current", "Predatory void-current that hunts warmth between stars.",
           ["Wake Tendril", "Deep Current Maw", "Abyss Feeder"],
           "Stillwater", "A harpoon of frozen current. Strikes with the weight of an ocean that stopped moving.",
           "Depth Ward", "Armor forged in the deepest current, where pressure crushes everything except the will to survive.",
           ["Wake Vortex", "Depth Crush", "Abyssal Drain"],
           "mixolydian", 1.1,
           "The pursuer passes. The tide goes still. The stations stop running and discover they've forgotten what it's like to stay.",
           "The wake swallows you. You become part of the current, chasing stations that will never stop running from you."),
        ds(["hull wall", "stagnant tile", "still floor", "dead grate"],
           "Becalmed Captain Doldrums", "Ghost skipper of the station that stopped running.",
           ["Stagnant Corpse", "Eddy Ghost", "Still-Water Shade"],
           "Dead Calm", "A weapon that works only in still water. In the eddy, it's devastating.",
           "Stagnation Shell", "Armor from a station that stopped. Heavy with the weight of giving up.",
           ["Stagnation Field", "Dead Water Trap"],
           "mixolydian", 1.0,
           "The eddy releases. Even still water can start to flow again.",
           "Stagnation is contagious. You stop. You stay. You become part of the eddy."),
    ]
))

# ─────────────────────────────────────────────
# 47. VERTIGO
# ─────────────────────────────────────────────
batch.append(camp(
    "Vertigo",
    "Stations with no consistent up or down. Gravity shifts randomly. Walls become floors become ceilings. Your inner ear is the first casualty.",
    "#14081a", "#b848c8", "Bungee Shade", "Gruppo", "Nova Mono",
    [
        lv("Tilt Chamber", "Bungee Shade",
           "The floor becomes a wall mid-step. Your coffee is on the ceiling. Orientation is a suggestion.",
           "vertigo_tilt", "#b848c8",
           ["#14081a", "#3a1848", "#6a2878", "#9838a8", "#b848c8"],
           B[0]),
        lv("Spin Corridor", "Bungee Shade",
           "The hallway rotates around you. Gravity is a carousel. Every step is a different down.",
           "vertigo_spin", "#a838b8",
           ["#100618", "#301440", "#582468", "#8830a0", "#a838b8"],
           B[1]),
        lv("Inversion Deck", "Bungee Shade",
           "The station flipped. Or you flipped. Same thing. Blood rushes to your head, or your feet, or whatever direction your head is currently pointing.",
           "vertigo_inversion", "#c858d8",
           ["#180a20", "#401c50", "#6a3080", "#a048b8", "#c858d8"],
           B[2]),
        lv("Gravity Well", "Bungee Shade",
           "Every direction is down. You fall toward the center of a room and can't leave because leaving means falling up.",
           "vertigo_well", "#d868e8",
           ["#1c0c24", "#482058", "#763890", "#b050c8", "#d868e8"],
           B[3]),
        lv("The Fulcrum", "Bungee Shade",
           "The center of the station's gravity madness. Here, all directions are down simultaneously. The only way to stand is to fall in every direction at once.",
           "vertigo_fulcrum", "#e078f0",
           ["#14081a", "#3c1850", "#683080", "#a850c0", "#e078f0"],
           B[4]),
        lv("Level Ground", "Bungee Shade",
           "One room where gravity works normally. The most disorienting room in the station, because you've forgotten what normal feels like.",
           "vertigo_level", "#9a30aa",
           ["#120818", "#2e1240", "#562270", "#9a30aa"],
           B[5]),
    ],
    {"healing_potions": 3, "speed_potions": 2, "bombs": 3},
    [
        ds(["rotating wall", "tilt tile", "angled floor", "spin grate"],
           "Tilt Warden Axis", "Orientation saboteur flipping floors into ceilings.",
           ["Tilt Walker", "Spin Crawler", "Ceiling Stalker"],
           "Gyroscope Lance", "A spear with a stabilized core. Strikes true regardless of which way is down.",
           "Equilibrium Vest", "Armor with built-in orientation. It always knows where the floor is, even when there isn't one.",
           ["Gravity Flip", "Orientation Scramble", "Directional Inversion"],
           "chromatic", 1.0,
           "The tilt steadies. Down is down. For now.",
           "You fell in every direction simultaneously. Gravity couldn't decide. Neither could your bones."),
        ds(["rotating wall", "carousel tile", "spin floor", "axis grate"],
           "Centrifuge Captain Gyre", "Carousel tyrant accelerating everything into orbit.",
           ["Carousel Demon", "Axis Shifter", "Spin Phantom"],
           "Counterweight Mace", "Heavy on the right side when gravity goes left. Self-correcting brutality.",
           "Spin Dampener", "Armor that absorbs rotational force. The corridor spins; you don't.",
           ["Spin Acceleration", "Axis Lock"],
           "chromatic", 1.0,
           "The corridor stops spinning. Your inner ear tentatively forgives you.",
           "The spin never stops. You become part of the carousel. Around and around."),
        ds(["rotating wall", "inverted tile", "ceiling floor", "flip grate", "reverse plate"],
           "Inverter Magistrate Flip", "Deck-flipping judge reversing all spatial law.",
           ["Ceiling Walker", "Inversion Beast", "Flip Predator"],
           "Plumb Line", "A weapon that always hangs straight. In Vertigo, straight is a weapon.",
           "Magnetic Boots", "Lock to whatever surface is currently pretending to be the floor.",
           ["Sudden Inversion", "Ceiling Drop", "Floor-Ceiling Swap"],
           "chromatic", 1.0,
           "The deck rights itself. The blood drains from your head in the correct direction.",
           "Inverted permanently. You see the world upside down and can't remember which way was right."),
        ds(["rotating wall", "well tile", "gravity floor", "pull grate", "center plate"],
           "Singularity Warden Nadir", "Gravity-well keeper pulling everything to center-mass.",
           ["Gravity Well Dweller", "Center Mass Predator", "Pull Wraith"],
           "Escape Velocity", "A hammer that swings with enough force to break orbit. One swing. One chance.",
           "Anti-Gravity Frame", "Armor that pushes back. The well can't hold you.",
           ["Gravity Intensification", "Well Deepening", "Orbital Decay"],
           "chromatic", 1.0,
           "The well releases. Gravity remembers its manners. Things fall one way again.",
           "The well pulls you to the center and holds you. You float in the middle of a room, forever falling, never landing."),
        ds(["rotating wall", "fulcrum tile", "omni-gravity floor", "chaos grate", "pivot plate"],
           "The Absolute Down", "Gravity singularity pulling from every direction at once.",
           ["Fulcrum Guardian", "Omni-Fall Specter", "Directional Chaos Elemental"],
           "True North", "A weapon that always points one way. In a station where every direction is down, having one direction that isn't is godlike.",
           "Horizon Keeper", "Armor that maintains a personal horizon. The world spins; inside the armor, there is always a floor beneath you.",
           ["Omni-Directional Fall", "Fulcrum Pulse", "Gravity Cascade"],
           "chromatic", 1.1,
           "The fulcrum stabilizes. Gravity flows one way. Down is down. Up is up. The simplest miracle in the universe.",
           "All directions become down. You fall into yourself. The fulcrum adds your mass to its own."),
        ds(["stable wall", "level tile", "flat floor", "normal grate"],
           "Equilibrium Ghost", "Phantom of normalcy haunting the one stable room.",
           ["Stability Ghost", "Normal Phantom", "Level Walker"],
           "Spirit Level", "A blade as flat and true as a calm sea. Cuts with precision that Vertigo can't disrupt.",
           "Flat-Footed Plate", "Armor designed for level ground. Incredibly effective in the one room where ground is level.",
           ["Normality Shock", "Stability Disruption"],
           "chromatic", 1.0,
           "Level ground holds. One room of sanity in a mad station. It's enough.",
           "Normal gravity felt wrong after so long without it. You stumbled. You fell. One foot."),
    ]
))

# ─────────────────────────────────────────────
# 48. TESSERACT
# ─────────────────────────────────────────────
batch.append(camp(
    "Tesseract",
    "Four-dimensional stations. Rooms connect to rooms that shouldn't exist. Corridors loop through themselves. Geometry has surrendered.",
    "#0e0416", "#e04890", "Monoton", "Orbitron", "Fira Code",
    [
        lv("Third-Wall Gallery", "Monoton",
           "Three-dimensional space is the floor plan. The fourth dimension is the architecture. You can see rooms from angles that don't exist.",
           "tesseract_gallery", "#e04890",
           ["#0e0416", "#3a1040", "#6e1c68", "#b03080", "#e04890"],
           B[0]),
        lv("Hypercube Atrium", "Monoton",
           "A room inside a room inside the first room. You can see yourself through walls that face inward from outside.",
           "tesseract_atrium", "#d03880",
           ["#0c0214", "#301038", "#5c1a5c", "#9a2870", "#d03880"],
           B[1]),
        lv("Klein Corridor", "Monoton",
           "A hallway with one surface. Inside is outside. You walk on the ceiling from below while standing on the floor from above.",
           "tesseract_klein", "#c02870",
           ["#0a0010", "#280e30", "#501858", "#882468", "#c02870"],
           B[2]),
        lv("Manifold Junction", "Monoton",
           "Where multiple dimensions of the station intersect. Doors open to rooms on different planes of existence. Choose wrong and you're somewhere that doesn't have a where.",
           "tesseract_manifold", "#f058a0",
           ["#100618", "#3e1248", "#701e70", "#b83890", "#f058a0"],
           B[3]),
        lv("The Unfolded Core", "Monoton",
           "The tesseract opened. Four-dimensional space laid flat. You can see every room from every angle at once. It's too much. It's exactly enough.",
           "tesseract_core", "#f868b0",
           ["#0e0416", "#381040", "#681c6c", "#a83088", "#f868b0"],
           B[4]),
        lv("Flatland Cell", "Monoton",
           "A room with only two dimensions. Length and width. No height. You're pressed flat and alive. It's like being a drawing that can think.",
           "tesseract_flat", "#a82068",
           ["#080010", "#240c2e", "#4c1650", "#a82068"],
           B[5]),
    ],
    {"healing_potions": 3, "speed_potions": 2, "bombs": 3},
    [
        ds(["folded wall", "tesseract tile", "hypercube floor", "dimension grate"],
           "Curator Polytope", "Gallery keeper arranging exhibits across impossible angles.",
           ["Plane Walker", "Angle Predator", "Vertex Hunter"],
           "Dimension Cutter", "A blade that severs along the fourth axis. Cuts things in directions they didn't know they had.",
           "Non-Euclidean Plate", "Armor with more interior space than exterior surface. Attacks enter and get lost inside.",
           ["Dimensional Fold", "Angle Trap", "Surface Inversion"],
           "whole_tone", 1.0,
           "The gallery flattens to three dimensions. It's less beautiful. It's comprehensible. That's better.",
           "Folded into a dimension you can't see. You still exist. You just can't find yourself."),
        ds(["folded wall", "hypercube tile", "nested floor", "recursive grate"],
           "Nesting Lord Recursion", "Self-containing entity living inside its own interior.",
           ["Nested Mimic", "Hypercube Spider", "Recursive Shade"],
           "Straight Razor", "Perfectly, aggressively flat. One dimension of sharpness. The tesseract can't bend it.",
           "Cubic Defense", "Armor with exactly six sides. Boring. Reliable. Geometrically sound.",
           ["Nesting Trap", "Recursive Fold"],
           "whole_tone", 1.0,
           "The hypercube unfolds to a cube. Six sides. Comprehensible. Safe.",
           "Nested inside yourself. A room within a room within you within the room."),
        ds(["folded wall", "klein tile", "moebius floor", "surface grate", "loop plate"],
           "Moebius Warden Klein", "One-sided surface sentinel patrolling infinite topology.",
           ["Klein Crawler", "Moebius Serpent", "Surface Dweller"],
           "Bilateral Blade", "A sword with two distinct sides. In a Klein corridor, that's a revolutionary concept.",
           "Oriented Armor", "Armor with a definite inside and outside. On a Klein surface, this is impossible. The armor disagrees.",
           ["Surface Flip", "Orientation Loss", "Moebius Loop"],
           "whole_tone", 1.0,
           "The Klein corridor gains a second side. Inside becomes inside. Outside stays out.",
           "You walk the single surface forever. Inside and outside are the same. You are the corridor."),
        ds(["folded wall", "manifold tile", "junction floor", "intersection grate", "plane plate"],
           "Junction Sovereign Riemann", "Manifold king commanding intersections between realities.",
           ["Manifold Guardian", "Junction Horror", "Plane Shifter"],
           "Axis Lock", "A mace that fixes things in three dimensions. Swing it and reality stops being creative.",
           "Dimension Anchor", "Armor pinned to three-dimensional space with mathematical precision. The fourth dimension slides past.",
           ["Manifold Split", "Junction Collapse", "Planar Shift"],
           "whole_tone", 1.1,
           "The manifold simplifies. Doors lead where they should. Rooms contain only themselves.",
           "You opened the wrong door. The room on the other side doesn't have dimensions you can survive in."),
        ds(["folded wall", "unfolded tile", "omniscient floor", "total grate", "revelation plate"],
           "The Hypersphere", "Infinite-faced four-dimensional sphere beyond mortal comprehension.",
           ["Unfolded Horror", "Total Geometry Beast", "Revelation Entity"],
           "Simplicity", "A perfectly straight stick. No curves. No angles. One dimension of weapon. In the Tesseract, this simplicity is devastating — it cannot be folded, bent, or rotated into a higher dimension.",
           "Flatland Fortress", "Armor that exists in exactly three dimensions and refuses to acknowledge the fourth. The Hypersphere's attacks slide through the missing axis.",
           ["Comprehension Damage", "Total Unfold", "Geometric Revelation"],
           "whole_tone", 1.2,
           "The tesseract folds down to three dimensions. The Hypersphere collapses into a sphere. Geometry remembers its place.",
           "You understood it. For one moment, you saw in four dimensions. Your brain could not return to three."),
        ds(["compressed wall", "flat tile", "two-d floor", "edge grate"],
           "Flatlord Euclid", "Two-dimensional despot crushing depth from existence.",
           ["Flatland Native", "Edge Walker", "Plane Dweller"],
           "Height", "A weapon from the third dimension. To flatland, it's incomprehensible power.",
           "Depth Shield", "A shield with thickness. In two dimensions, it's impenetrable.",
           ["Compression Field", "Dimensional Reduction"],
           "whole_tone", 1.0,
           "The cell gains depth. Two dimensions become three. You stand up for the first time.",
           "Compressed to two dimensions. You exist. You just can't reach anything above or below you. There is no above or below."),
    ]
))

# ─────────────────────────────────────────────
# 49. LEVIATHAN WAKE
# ─────────────────────────────────────────────
batch.append(camp(
    "Leviathan Wake",
    "The bones that were Scrimshaw were just one finger. The full creature spans systems. It's waking up. The stations on its body are parasites it's about to scratch.",
    "#1a0e08", "#c86840", "Eater", "Bitter", "Cousine",
    [
        lv("Dermal Station", "Eater",
           "The station is built on skin. It stretches when the creature shifts. The walls are warm and they breathe.",
           "leviathan_dermal", "#c86840",
           ["#1a0e08", "#4a2818", "#7e4428", "#a85838", "#c86840"],
           B[0]),
        lv("Vascular Transit", "Eater",
           "Corridors that pulse. You're inside a vein. The current pushes you forward. The creature's heartbeat is the floor shaking every seven seconds.",
           "leviathan_vascular", "#b85830",
           ["#160c06", "#3e2010", "#6c3820", "#9a4c28", "#b85830"],
           B[1]),
        lv("Marrow Depths", "Eater",
           "Inside the bones now. The same bones that Scrimshaw was built on, but these are alive. They creak with growth.",
           "leviathan_marrow", "#d8c8a0",
           ["#1a0e08", "#4a3018", "#7a5830", "#b08848", "#d8c8a0"],
           B[2]),
        lv("Neural Cluster", "Eater",
           "The creature's nervous system. Thoughts the size of planets move through cables of nerve fiber. You are an irritation. It's starting to notice.",
           "leviathan_neural", "#e0a060",
           ["#1c1008", "#503018", "#885028", "#c07840", "#e0a060"],
           B[3]),
        lv("The Waking Eye", "Eater",
           "It opens. The eye is a station. The pupil is a door. Behind it: a mind that has slept since before humanity discovered fire. It's awake. It sees you.",
           "leviathan_eye", "#e8b070",
           ["#1a0e08", "#482a14", "#7a4824", "#b06838", "#e8b070"],
           B[4]),
        lv("Symbiont Bay", "Eater",
           "A station that has been living on the creature so long it's become part of it. Half metal, half meat. The residents don't know which they are anymore.",
           "leviathan_symbiont", "#aa5830",
           ["#140a06", "#3c2010", "#684020", "#aa5830"],
           B[5]),
    ],
    {"healing_potions": 3, "speed_potions": 2, "bombs": 3},
    [
        ds(["bone wall", "skin tile", "membrane floor", "tendon grate"],
           "Dermal Warden Chitin", "Skin-station immune guardian rejecting all parasites.",
           ["Skin Parasite", "Dermal Guardian", "Membrane Crawler"],
           "Surgeon's Blade", "A scalpel scaled up to a sword. Cuts flesh with medical precision.",
           "Exoskeletal Graft", "Armor grown from the creature's own chitin. It recognizes you as part of itself. Attacks hesitate.",
           ["Immune Response", "Skin Contraction", "Dermal Eruption"],
           "phrygian", 1.0,
           "The skin calms. The creature accepts your presence. For now.",
           "Scratched off like a flea. The creature barely noticed."),
        ds(["bone wall", "vein tile", "blood floor", "pulse grate"],
           "Heartbeat Overseer Pulse", "Vascular enforcer riding the creature's circulatory tide.",
           ["Blood Cell Hunter", "Vascular Tide", "Arterial Stalker"],
           "Anticoagulant Edge", "A blade that keeps wounds open. The creature can't clot around it.",
           "Platelet Armor", "Armor made of the creature's own clotting agents. Heals as fast as it's damaged.",
           ["Blood Surge", "Vascular Collapse"],
           "phrygian", 1.0,
           "The pulse steadies. You move with it now, not against it.",
           "Flushed out through a vein. Expelled. The creature's circulation treated you like waste."),
        ds(["bone wall", "marrow tile", "calcium floor", "growth grate", "ossuary plate"],
           "Ossuary Keeper Calcium", "Bone-growing sentinel fossilizing intruders alive.",
           ["Marrow Worm", "Bone Grower", "Calcium Sentinel"],
           "Bone Saw", "Cuts through the framework of the universe's largest living thing.",
           "Marrow-Forged Mail", "Armor grown in the creature's bones. Hard as the deepest bedrock.",
           ["Bone Growth Trap", "Marrow Flood", "Calcification Wave"],
           "phrygian", 1.0,
           "The bones settle. Growth pauses. The creature's skeleton holds still.",
           "Entombed in growing bone. Fossilized alive in the skeleton of a god."),
        ds(["bone wall", "nerve tile", "synapse floor", "thought grate", "impulse plate"],
           "Synapse Lord Cortex", "Neural cluster commander directing continent-sized thoughts.",
           ["Nerve Impulse", "Synapse Hunter", "Thought Fragment"],
           "Anesthesia Lance", "A spear tipped with numbness. Where it strikes, the creature can't feel.",
           "Insulation Weave", "Armor that blocks neural signals. The creature's thoughts can't reach you inside it.",
           ["Nerve Cascade", "Synapse Fire", "Thought Crush"],
           "phrygian", 1.1,
           "The neural cluster dims. The creature's attention drifts. You're forgotten. That's survival.",
           "The creature thought about you. One thought. It was enough. You were unmade by consideration."),
        ds(["bone wall", "iris tile", "lens floor", "pupil grate", "retina plate"],
           "The Awakened Mind", "Eon-sleeping planetary consciousness now fully aware of you.",
           ["Iris Guardian", "Lens Refractor", "Retinal Leviathan"],
           "The Blind Spot", "A dagger that strikes where the eye can't see. Every creature has one. Even one this large.",
           "Optic Nerve Plate", "Armor wired into the creature's visual system. It sees through you. You become transparent to its gaze.",
           ["Gaze Pressure", "Awareness Crush", "Pupil Contraction"],
           "phrygian", 1.2,
           "The eye closes. Not in death — in peace. The Leviathan returns to sleep, and in its dreams, it remembers a small thing that stood inside its eye and refused to be afraid.",
           "The eye focused. The full weight of a planetary consciousness looked at you. You were not big enough to be seen. You ceased to exist from its perspective. That was enough."),
        ds(["bone wall", "symbiont tile", "hybrid floor", "graft grate"],
           "Symbiont Patriarch Graft", "Half-metal half-meat elder fused to the creature's body.",
           ["Symbiont Hybrid", "Graft Horror", "Fusion Crawler"],
           "Separation Scalpel", "A blade that cuts metal from meat. Severs the symbiosis.",
           "Hybrid Hide", "Armor that's half machine, half organism. It argues with itself but protects well.",
           ["Symbiont Rejection", "Graft Failure"],
           "phrygian", 1.0,
           "Metal and meat separate. The symbionts choose their side. Both survive.",
           "The symbiosis completed. You became part of the station. The station is part of the creature. You are a cell in a god."),
    ]
))

# ─────────────────────────────────────────────
# 50. REQUIEM
# ─────────────────────────────────────────────
batch.append(camp(
    "Requiem",
    "The last system. Every station is a memorial. Every corridor is a eulogy. The journey ends where all journeys end — at the place where someone remembers you were here.",
    "#000000", "#e0e0e8", "EB Garamond", "EB Garamond", "EB Garamond",
    [
        lv("Hall of Names", "EB Garamond",
           "Every wall is inscribed. Every name is someone who came before you. Some you recognize. Most you don't. All of them mattered.",
           "requiem_names", "#c8c8d0",
           ["#000000", "#2a2a30", "#606068", "#9898a0", "#c8c8d0"],
           B[0]),
        lv("Echo Nave", "EB Garamond",
           "A cathedral in space. Sound carries forever here. Every footstep joins the echoes of everyone who walked before.",
           "requiem_nave", "#b8b8c4",
           ["#020204", "#28282e", "#585860", "#8a8a94", "#b8b8c4"],
           B[1]),
        lv("The Cenotaph", "EB Garamond",
           "A tomb for those whose bodies were never found. The empty coffins are the heaviest things you've ever carried.",
           "requiem_cenotaph", "#d0d0d8",
           ["#040406", "#303038", "#686870", "#a0a0a8", "#d0d0d8"],
           B[2]),
        lv("Vigil Bridge", "EB Garamond",
           "The bridge between remembering and forgetting. Candles that never go out line the railings. Each one is a life.",
           "requiem_vigil", "#d8d8e0",
           ["#060608", "#34343c", "#707078", "#a8a8b0", "#d8d8e0"],
           B[3]),
        lv("The Last Threshold", "EB Garamond",
           "The final room. The end of the journey. No enemies here except the question: was it enough?",
           "requiem_threshold", "#e8e8f0",
           ["#000000", "#282830", "#606070", "#a0a0b0", "#e8e8f0"],
           B[4]),
        lv("The Quiet Room", "EB Garamond",
           "A room with no purpose except to be still. After fifty systems, you've earned the silence.",
           "requiem_quiet", "#b0b0b8",
           ["#020204", "#262630", "#585860", "#b0b0b8"],
           B[5]),
    ],
    {"healing_potions": 5, "speed_potions": 3, "bombs": 3},
    [
        ds(["memorial stone", "eulogy floor", "remembrance alcove", "inscription tile"],
           "The Keeper of Names", "Wall-inscriber guarding the hall of the remembered.",
           ["Fading Inscription", "Name Echo", "Memorial Shade"],
           "Epitaph", "A blade that writes as it cuts. Every wound is a line in a story.",
           "Mourning Veil", "Armor made of grief. Surprisingly strong. Grief usually is.",
           ["Name Erosion", "Memory Fade", "Inscription Blur"],
           "aeolian", 0.9,
           "Your name joins the wall. Not the brightest. Not the largest. But there.",
           "Your name was never inscribed. The wall is for those who finished the journey."),
        ds(["memorial stone", "nave tile", "cathedral floor", "echo alcove"],
           "Choirmaster Resonance", "Cathedral conductor harmonizing the voices of the dead.",
           ["Echo Chorister", "Nave Guardian", "Hymn Shade"],
           "Resonance", "A tuning fork the size of a sword. Strikes the frequency of truth.",
           "Choir Robe", "Armor woven from sustained notes. Sound wraps around you protectively.",
           ["Echo Overload", "Harmonic Dissonance"],
           "aeolian", 0.9,
           "Your voice joins the nave. One more note in an eternal chord.",
           "The echoes drown you out. Your voice is lost in the sound of everyone who came before."),
        ds(["memorial stone", "cenotaph tile", "empty tomb floor", "absence alcove", "hollow plate"],
           "The Hollow Steward", "Empty-tomb guardian holding space for the never-returned.",
           ["Cenotaph Guard", "Empty Coffin Mimic", "Absence Elemental"],
           "Presence", "A weapon that fills empty space. Strikes with the weight of being there.",
           "Placeholder Armor", "Armor that stands in for absent friends. You wear everyone who should have been here.",
           ["Emptiness Trap", "Absence Pull", "Hollow Resonance"],
           "aeolian", 0.9,
           "The cenotaph fills. Not with a body — with a memory. That's enough. That was always enough.",
           "An empty coffin with your measurements. It was always waiting for you."),
        ds(["memorial stone", "vigil tile", "candlelit floor", "flame alcove", "watch plate"],
           "Candle Warden Perpetua", "Eternal vigil-keeper tending flames for every lost soul.",
           ["Vigil Keeper", "Candle Warden", "Watch Shade"],
           "Candlelight", "A rapier that glows with the light of every candle on the bridge. Each one a life. Each one still burning.",
           "Vigil Cloak", "Armor for the long watch. Warm enough for the cold between stars.",
           ["Flame Gutter", "Vigil's End", "Candle Snuff"],
           "aeolian", 0.95,
           "The candles brighten. One more joins them. Yours. It will burn as long as someone remembers.",
           "The candles go out one by one. Yours was the last. The bridge goes dark."),
        ds(["memorial stone", "eulogy floor", "remembrance alcove", "threshold tile", "finality plate"],
           "The Memory of Everything", "Accumulated recollection of every system you ever crossed.",
           ["Memory of Redshift", "Memory of Dominion", "Memory of Halcyon"],
           "The Journey", "Not a weapon. A record. Every swing replays a moment from the fifty systems behind you. It strikes with the cumulative weight of everywhere you've been.",
           "Everything You've Carried", "Armor made from every lesson, every scar, every moment of survival across fifty systems. Not the strongest armor. The most earned.",
           ["Nostalgia Wave", "Journey Replay", "Memory Weight"],
           "ionian", 1.0,
           "It remembers. You remember. The journey mattered. Not because of what waited at the end, but because of what you became on the way. The last threshold opens — not to another station, not to another system, but to whatever comes after. You step through. The door closes behind you. Somewhere, on the Hall of Names, a new inscription appears. It's yours.",
           "You forgot. Not the names, not the places — you forgot why it mattered. The Memory dissolves, and so do you. The threshold closes. Another traveler will come. Maybe they'll remember."),
        ds(["memorial stone", "silence tile", "stillness floor", "peace alcove"],
           "The Last Silence", "Final question echoing in the stillness after everything.",
           ["Quiet Ghost", "Stillness Shade", "Peace Walker"],
           "Rest", "A weapon you don't have to swing. Its presence is enough.",
           "Silence", "Armor that makes no sound. After fifty systems of noise, silence is the greatest protection.",
           ["Stillness Field", "Quiet Pull"],
           "ionian", 0.8,
           "Silence. Not empty silence — full silence. The silence after a story well told. You sit down. You've earned it.",
           "The quiet room asks nothing. You give nothing. The journey ends not with a bang or a whimper, but with a question you couldn't answer."),
    ]
))
