# Phase 1: The Frontier (Systems 1-10)
# You're a salvager on the edge of known space. Local problems.
B = [125, 165, 195, 235, 275, 140]
batch = []

# ─────────────────────────────────────────────
# 1. SARGASSO DRIFT
# Dead calm region where engines fail and ships accumulate
# ─────────────────────────────────────────────
batch.append(camp(
    name="Sargasso Drift",
    desc="A dead calm region where engines fail and ships pile up in a graveyard of becalmed vessels. Stations are lashed-together hulks drifting in silence.",
    bg="#0a0d12",
    text="#c4b89a",
    font="Special Elite",
    dfont="Share Tech Mono",
    lfont="Rajdhani",
    levels=[
        lv("The Lashing", "Rajdhani",
           "A makeshift dock of cables and welded gangplanks connecting dead freighters.",
           "derelict cargo ships bound together with fraying cables, dim emergency lighting, floating debris",
           "#8a7e6b", ["#1a1510", "#3d3528", "#6b5e47", "#a89878", "#d4c8a0"], B[0]),
        lv("Hull 17", "Rajdhani",
           "A hollowed-out colony ship repurposed as a trading post. The locals don't ask questions.",
           "gutted colony ship interior, improvised market stalls, smuggler alcoves, stripped bulkheads",
           "#9e8c6a", ["#12100a", "#2e2a1e", "#5c5238", "#8a7e5c", "#bfaf80"], B[1]),
        lv("The Doldrums", "Rajdhani",
           "The innermost ring of becalmed ships. Nothing moves here. The air tastes stale and wrong.",
           "motionless ship graveyard, thick dust coating every surface, dead instrument panels, eerie stillness",
           "#7a8a7e", ["#0d100e", "#252e28", "#4a5c50", "#708a78", "#9ab8a0"], B[2]),
        lv("Engine Tomb", "Rajdhani",
           "A massive engineering bay where mechanics try to restart dead drives. None have succeeded.",
           "cavernous engine room, failed reactor cores, scattered tools, desperate repair attempts",
           "#8a6a5a", ["#100c0a", "#2e221a", "#5c4438", "#8a6658", "#b88878"], B[3]),
        lv("The Becalmer", "Rajdhani",
           "The oldest ship in the drift. Something aboard it is generating the dead zone.",
           "ancient vessel bridge, alien dampening field generators, pulsing unknown energy, warped hull plating",
           "#6a7a9e", ["#0a0c14", "#1e2236", "#3a4468", "#5a6a92", "#7e90be"], B[4]),
        lv("Scavenger's Cache", "Rajdhani",
           "A hidden compartment deep in the drift where the best salvage is hoarded.",
           "secret cargo hold, valuable salvage, booby traps, a collector's obsession",
           "#9a8a6a", ["#100e08", "#2e2a18", "#5a5238", "#887a58", "#b8a878"], B[5]),
    ],
    store={"healing_potions": 4, "speed_potions": 2, "bombs": 2},
    designs=[
        ds(
            tiles=[
                {"name": "welded hull plate", "walkable": False, "color": "#2a2520"},
                {"name": "cable-lashed gangway", "walkable": True, "color": "#4a4030"},
                {"name": "rusted deck grating", "walkable": True, "color": "#3a3225"},
                {"name": "cargo netting floor", "walkable": True, "color": "#352e20"},
            ],
            boss="Dockmaster Hale",
            boss_desc="Charges tolls in blood. Rope-scarred hands.",
            mons=["Drift Rat", "Cable Snapper", "Hull Creeper"],
            weapon="Grappling Spike",
            weapon_desc="A dock hook sharpened to a killing point.",
            armor="Lashed Plate Vest",
            armor_desc="Hull scraps wired together. Heavy but reliable.",
            traps=["Frayed Cable Snap", "Loose Hull Plate", "Debris Slide"],
            root="D", scale="dorian",
            vic="The cables go slack. The lashing drifts apart.",
            defeat="You hang from the cables like another piece of salvage.",
        ),
        ds(
            tiles=[
                {"name": "stripped bulkhead", "walkable": False, "color": "#282218"},
                {"name": "market planking", "walkable": True, "color": "#3e3828"},
                {"name": "smuggler's grate", "walkable": True, "color": "#35301e"},
                {"name": "stall counter", "walkable": True, "color": "#4a4230"},
            ],
            boss="Madame Carrion",
            boss_desc="Runs the black market. Poisoned fingernails.",
            mons=["Grift Shade", "Pickpocket Drone", "Hulljacker"],
            weapon="Shiv of Commerce",
            weapon_desc="A broken credit chip honed to slice.",
            armor="Trader's Longcoat",
            armor_desc="Lined with stolen hull composite. Surprisingly tough.",
            traps=["Rigged Scale", "Collapsing Stall", "Poison Dust Trap"],
            root="A", scale="aeolian",
            vic="The market falls silent. Madame Carrion's ledger closes.",
            defeat="Your name is added to the debtor's wall. Permanently.",
        ),
        ds(
            tiles=[
                {"name": "dust-caked partition", "walkable": False, "color": "#1e1e18"},
                {"name": "silted deck", "walkable": True, "color": "#2e2e24"},
                {"name": "stagnant pool", "walkable": True, "color": "#2a3028"},
                {"name": "dead console", "walkable": True, "color": "#222018"},
            ],
            boss="The Stillborn",
            boss_desc="A fused navigator. Hasn't moved in years.",
            mons=["Dust Wraith", "Stagnation Mite", "Silence Crawler"],
            weapon="Petrified Baton",
            weapon_desc="A calcified control rod. Hits like stone.",
            armor="Dust Cocoon",
            armor_desc="Layered dust compressed into crude armor.",
            traps=["Dust Pocket Collapse", "Stale Air Zone", "Static Discharge"],
            root="E", scale="phrygian",
            vic="A breeze stirs for the first time in decades.",
            defeat="You settle into the dust. Nothing moves again.",
        ),
        ds(
            tiles=[
                {"name": "seized engine casing", "walkable": False, "color": "#201a18"},
                {"name": "oil-slick floor", "walkable": True, "color": "#2a2420"},
                {"name": "tool-scattered deck", "walkable": True, "color": "#302a22"},
                {"name": "coolant channel", "walkable": True, "color": "#1a2028"},
            ],
            boss="Chief Ratchet",
            boss_desc="Won't stop trying. Wrench fused to hand.",
            mons=["Spark Ghost", "Seized Piston", "Runaway Turbine"],
            weapon="Plasma Torque Wrench",
            weapon_desc="Meant for engines. Works on skulls.",
            armor="Mechanic's Blast Apron",
            armor_desc="Scorched, oil-stained, practically indestructible.",
            traps=["Coolant Burst", "Piston Slam", "Arc Flash"],
            root="G", scale="mixolydian",
            vic="The engine coughs once. Then silence. Then ignition.",
            defeat="The engine stays dead. So do you.",
        ),
        ds(
            tiles=[
                {"name": "alien alloy wall", "walkable": False, "color": "#141828"},
                {"name": "resonance floor", "walkable": True, "color": "#1e2438"},
                {"name": "dampening node", "walkable": True, "color": "#222840"},
                {"name": "pulse conduit", "walkable": True, "color": "#182035"},
            ],
            boss="The Dampener",
            boss_desc="Not a person. A field given hunger.",
            mons=["Null Wisp", "Inertia Phantom", "Entropy Leech"],
            weapon="Momentum Lance",
            weapon_desc="Stores kinetic energy. Releases it all at once.",
            armor="Faraday Shroud",
            armor_desc="Woven conductive mesh. Grounds energy attacks.",
            traps=["Dampening Pulse", "Gravity Well", "Inertia Lock"],
            root="F#", scale="locrian",
            vic="The dead zone collapses. Engines roar to life across the drift.",
            defeat="Your momentum stops. You float, forever still.",
        ),
        ds(
            tiles=[
                {"name": "reinforced vault wall", "walkable": False, "color": "#1a1810"},
                {"name": "hoarded deck plate", "walkable": True, "color": "#2e2a1a"},
                {"name": "salvage pile", "walkable": True, "color": "#3a3420"},
                {"name": "trapped floor panel", "walkable": True, "color": "#282214"},
            ],
            boss="Old Magpie",
            boss_desc="Hoards everything. Trusts nothing. Shotgun loaded.",
            mons=["Junk Golem", "Nest Drone", "Scrap Sentinel"],
            weapon="Magpie's Scattergun",
            weapon_desc="Fires salvaged ball bearings. Messy but effective.",
            armor="Patchwork Carapace",
            armor_desc="Every piece from a different ship. Ugly. Works.",
            traps=["Bear Trap", "Tripwire Alarm", "Collapsing Pile"],
            root="C", scale="pentatonic_minor",
            vic="The cache is open. Enough salvage to buy passage anywhere.",
            defeat="Old Magpie adds your gear to the collection.",
        ),
    ],
))

# ─────────────────────────────────────────────
# 2. KEPLER'S REACH
# Binary star research system. Prismatic interference.
# ─────────────────────────────────────────────
batch.append(camp(
    name="Kepler's Reach",
    desc="Binary star research platforms orbiting twin suns. Prismatic interference paints everything in shifting spectra. Gravitational tides pull at the stations.",
    bg="#0c0a14",
    text="#d4c0e8",
    font="Orbitron",
    dfont="Exo 2",
    lfont="Electrolize",
    levels=[
        lv("Parallax Observatory", "Electrolize",
           "The outermost research platform. Telescopes track the twin suns' dance.",
           "observatory dome, refracted starlight, humming telescopes, prismatic lens arrays",
           "#9a80c0", ["#0e0a18", "#2a2040", "#4e3a70", "#7a60a0", "#a888d0"], B[0]),
        lv("Spectral Lab", "Electrolize",
           "Light analysis facility. Every surface refracts. Researchers went strange.",
           "prism-filled corridors, rainbow caustics on walls, humming spectrometers, shattered lenses",
           "#c0a0d8", ["#100c1a", "#2e2244", "#54407a", "#8060b0", "#b088e0"], B[1]),
        lv("Tidal Lock Station", "Electrolize",
           "Gravity research platform caught between both stars. Everything slides.",
           "tilting corridors, sliding furniture, gravity flux zones, magnetic clamps on every surface",
           "#80a0c0", ["#0a0c14", "#1e2438", "#3a4868", "#5a7098", "#80a0cc"], B[2]),
        lv("Corona Bridge", "Electrolize",
           "A shielded walkway passing through the binary stars' shared corona. Blinding heat.",
           "heat-shielded tunnel, plasma viewing ports, melting insulation, solar wind vibration",
           "#d0a060", ["#141008", "#382a14", "#685020", "#a07830", "#d8a848"], B[3]),
        lv("Barycenter Core", "Electrolize",
           "The exact gravitational center between both suns. Reality bends here.",
           "warped geometry, light bending around corners, temporal echoes, gravitational lensing",
           "#b0a0d0", ["#0c0a16", "#22183a", "#402e68", "#6648a0", "#9068d8"], B[4]),
        lv("Dark Companion", "Electrolize",
           "A hidden third body orbiting the binary pair. It absorbs all spectra.",
           "lightless corridors, absorption surfaces, spectrum-eating walls, inverse prisms",
           "#607080", ["#08090c", "#181c24", "#303840", "#485860", "#607880"], B[5]),
    ],
    store={"healing_potions": 4, "speed_potions": 2, "bombs": 2},
    designs=[
        ds(
            tiles=[
                {"name": "observatory housing", "walkable": False, "color": "#1e1830"},
                {"name": "lens-polished floor", "walkable": True, "color": "#2a2240"},
                {"name": "refraction grating", "walkable": True, "color": "#322a48"},
                {"name": "star chart table", "walkable": True, "color": "#2e2644"},
            ],
            boss="Dr. Lux Parallax",
            boss_desc="Stared into both suns. Sees too much.",
            mons=["Lens Flare", "Spectrum Moth", "Parallax Shadow"],
            weapon="Focused Beam Emitter",
            weapon_desc="Concentrated starlight channeled through crystal.",
            armor="Anti-Glare Suit",
            armor_desc="Polarized mesh. Dims incoming light attacks.",
            traps=["Blinding Reflection", "Lens Burn", "Prism Trap"],
            root="Bb", scale="lydian",
            vic="The telescopes go dark. Some things aren't meant to be watched.",
            defeat="Both suns fill your vision. Then nothing.",
        ),
        ds(
            tiles=[
                {"name": "crystal partition", "walkable": False, "color": "#201838"},
                {"name": "prismatic tile", "walkable": True, "color": "#2e2448"},
                {"name": "spectral residue", "walkable": True, "color": "#382a50"},
                {"name": "shattered lens bed", "walkable": True, "color": "#281e40"},
            ],
            boss="The Refractionalist",
            boss_desc="Split into seven selves. Each a color.",
            mons=["Chromatic Wisp", "Ultraviolet Stalker", "Infrared Creeper"],
            weapon="Prism Shard Blade",
            weapon_desc="Cuts along spectral lines. Wounds shimmer.",
            armor="Spectral Dampener Coat",
            armor_desc="Absorbs stray wavelengths. Looks dull. Saves lives.",
            traps=["Rainbow Snare", "UV Burn Zone", "Spectral Overload"],
            root="E", scale="whole_tone",
            vic="The spectrum collapses to white. The lab goes quiet.",
            defeat="You refract. Seven pieces. None viable.",
        ),
        ds(
            tiles=[
                {"name": "magnetic clamp wall", "walkable": False, "color": "#141828"},
                {"name": "sliding deck plate", "walkable": True, "color": "#202838"},
                {"name": "gravity flux zone", "walkable": True, "color": "#1a2434"},
                {"name": "mag-locked walkway", "walkable": True, "color": "#1e2a3a"},
            ],
            boss="Tidecaller Voss",
            boss_desc="Controls local gravity. Walks on ceilings.",
            mons=["Drift Body", "Tidal Pulse", "Gravity Leech"],
            weapon="Grav-Hammer",
            weapon_desc="Multiplies its own weight on impact.",
            armor="Mag-Lock Boots",
            armor_desc="Stay grounded when everything else floats.",
            traps=["Gravity Reversal", "Tidal Surge", "Mag-Lock Failure"],
            root="F", scale="dorian",
            vic="Gravity normalizes. Things stop sliding. Your stomach settles.",
            defeat="You float into the tidal zone. Pulled apart gently.",
        ),
        ds(
            tiles=[
                {"name": "heat shield wall", "walkable": False, "color": "#281a08"},
                {"name": "scorched walkway", "walkable": True, "color": "#3a2810"},
                {"name": "plasma viewing deck", "walkable": True, "color": "#443014"},
                {"name": "melting insulation", "walkable": True, "color": "#322210"},
            ],
            boss="Solarch Krin",
            boss_desc="Burns from within. Former station commander.",
            mons=["Corona Sprite", "Heat Mirage", "Solar Wind Runner"],
            weapon="Sunspot Lance",
            weapon_desc="A rod of captured solar plasma. Brief but brutal.",
            armor="Ablative Corona Shield",
            armor_desc="Sheds layers to survive heat. Gets thinner.",
            traps=["Solar Flare Burst", "Heat Shield Failure", "Plasma Vent"],
            root="A", scale="phrygian",
            vic="The corona recedes. Temperature drops to merely unbearable.",
            defeat="The bridge melts around you. A new sunspot.",
        ),
        ds(
            tiles=[
                {"name": "warped bulkhead", "walkable": False, "color": "#18142a"},
                {"name": "bent floor plate", "walkable": True, "color": "#24203e"},
                {"name": "lensing corridor", "walkable": True, "color": "#2a2444"},
                {"name": "temporal echo tile", "walkable": True, "color": "#201c38"},
            ],
            boss="The Barycenter",
            boss_desc="Not a person. A gravitational singularity. Aware.",
            mons=["Lensing Phantom", "Time-Smeared Shade", "Gravity Knot"],
            weapon="Singularity Spike",
            weapon_desc="A point of collapsed matter. Impossibly heavy.",
            armor="Geodesic Frame",
            armor_desc="Bends space around you. Attacks curve away.",
            traps=["Spacetime Fold", "Gravitational Lens", "Tidal Shear"],
            root="F#", scale="locrian",
            vic="The center holds. Both suns resume their ancient dance.",
            defeat="You orbit the barycenter forever. A new satellite.",
        ),
        ds(
            tiles=[
                {"name": "absorption wall", "walkable": False, "color": "#0c0e14"},
                {"name": "lightless deck", "walkable": True, "color": "#14181e"},
                {"name": "null spectrum zone", "walkable": True, "color": "#101418"},
                {"name": "inverse prism floor", "walkable": True, "color": "#121620"},
            ],
            boss="The Umbra",
            boss_desc="Living darkness. Eats wavelengths. Whispers remain.",
            mons=["Void Mote", "Dark Feeder", "Absence"],
            weapon="Blacklight Razor",
            weapon_desc="Cuts with frequencies no eye can see.",
            armor="Emission Suit",
            armor_desc="Generates its own light. The darkness hates it.",
            traps=["Total Absorption", "Light Drain", "Spectral Void"],
            root="B", scale="blues",
            vic="Light returns. The dark companion shrinks. Color floods back.",
            defeat="The last photon in your suit goes out.",
        ),
    ],
))

# ─────────────────────────────────────────────
# 3. DUSTBOWL
# Exhausted mining system. Ghost towns, desperate holdouts.
# ─────────────────────────────────────────────
batch.append(camp(
    name="Dustbowl",
    desc="An exhausted mining system picked clean decades ago. Ghost stations, desperate holdouts, and claim jumpers fighting over scraps in the dust.",
    bg="#0e0c08",
    text="#c8b890",
    font="Special Elite",
    dfont="Saira",
    lfont="Rajdhani",
    levels=[
        lv("Assay Office", "Rajdhani",
           "The old claims office. Deeds to worthless rock. Someone's still filing.",
           "dusty filing cabinets, faded mineral surveys, cracked assay scales, yellowed claim deeds",
           "#a89870", ["#14100a", "#302a18", "#584e30", "#887848", "#b8a868"], B[0]),
        lv("Shaft 9", "Rajdhani",
           "A played-out mine. The holdouts say there's one vein left. They're lying to themselves.",
           "collapsed tunnels, abandoned drills, empty ore carts, dust-choked air vents",
           "#8a7a58", ["#100e08", "#282418", "#4a4430", "#706848", "#988c62"], B[1]),
        lv("Boomtown Remnant", "Rajdhani",
           "Main street of a dead mining town. Saloon still serves. Nothing else does.",
           "abandoned storefronts, swinging doors, dusty bar, broken neon signs",
           "#a08848", ["#12100a", "#2c2818", "#50482a", "#7a6c3a", "#a89450"], B[2]),
        lv("The Sluice", "Rajdhani",
           "Mineral processing plant. Vast empty hoppers. The machinery still runs, crushing nothing.",
           "enormous empty hoppers, grinding machinery, conveyor belts to nowhere, mineral dust coating everything",
           "#7a7058", ["#0e0c08", "#242018", "#403a28", "#605840", "#807860"], B[3]),
        lv("Motherlode Myth", "Rajdhani",
           "The deepest shaft. Legend says something's down here. Legend is half right.",
           "deep vertical shaft, strange mineral formations, pressure-cracked walls, faint glow from below",
           "#908060", ["#100c08", "#282018", "#483a28", "#685840", "#907860"], B[4]),
        lv("Jumper's Hideout", "Rajdhani",
           "Where claim jumpers stash their stolen hauls. Guarded by paranoia and buckshot.",
           "hidden cave, stolen equipment, improvised fortifications, trip-wired passages",
           "#a09060", ["#100e08", "#2a2618", "#4e4628", "#786a3a", "#a89450"], B[5]),
    ],
    store={"healing_potions": 3, "speed_potions": 1, "bombs": 2},
    designs=[
        ds(
            tiles=[
                {"name": "filing cabinet wall", "walkable": False, "color": "#1e1a10"},
                {"name": "dusty floorboard", "walkable": True, "color": "#2e2818"},
                {"name": "claim counter", "walkable": True, "color": "#362e1e"},
                {"name": "faded carpet", "walkable": True, "color": "#2a2414"},
            ],
            boss="Registrar Peck",
            boss_desc="Files claims for the dead. Stamps everything.",
            mons=["Dust Devil", "Paper Wasp Drone", "Claim Ghost"],
            weapon="Stamp Press",
            weapon_desc="Iron claim stamp. Leaves a mark on flesh.",
            armor="Ledger-Bound Vest",
            armor_desc="Wrapped in old claim deeds. Paper-thick protection.",
            traps=["Filing Avalanche", "Ink Trap", "Collapsing Shelf"],
            root="D", scale="mixolydian",
            vic="The last claim is filed. The office can finally close.",
            defeat="DENIED stamped across your forehead. In red.",
        ),
        ds(
            tiles=[
                {"name": "mine shaft timber", "walkable": False, "color": "#1a1408"},
                {"name": "gravel floor", "walkable": True, "color": "#2a2414"},
                {"name": "ore cart track", "walkable": True, "color": "#322a18"},
                {"name": "dust pile", "walkable": True, "color": "#242010"},
            ],
            boss="Foreman Silt",
            boss_desc="Won't leave the shaft. Pickaxe never stops.",
            mons=["Tunnel Borer", "Dust Lung", "Canary Shade"],
            weapon="Depleted Pickaxe",
            weapon_desc="Worn thin from decades of nothing. Still sharp.",
            armor="Miner's Hard Shell",
            armor_desc="Dented helmet and reinforced overalls. Classic.",
            traps=["Cave-In", "Dust Pocket", "Rotten Timber"],
            root="G", scale="aeolian",
            vic="The last support beam holds. Daylight above.",
            defeat="The shaft collapses. Another unmarked grave.",
        ),
        ds(
            tiles=[
                {"name": "saloon wall", "walkable": False, "color": "#1e1810"},
                {"name": "wooden boardwalk", "walkable": True, "color": "#302818"},
                {"name": "bar floor sawdust", "walkable": True, "color": "#282014"},
                {"name": "broken window frame", "walkable": True, "color": "#342c1c"},
            ],
            boss="One-Shot Mercer",
            boss_desc="Last bartender standing. One bullet left. Maybe.",
            mons=["Tumbleweed Wraith", "Dust Stalker", "Barfly Specter"],
            weapon="Rusty Lever-Action",
            weapon_desc="Jams every third shot. Hits hard when it works.",
            armor="Bartender's Apron",
            armor_desc="Leather and spite. Stained with everything.",
            traps=["Loose Floorboard", "Swinging Door", "Broken Glass"],
            root="E", scale="blues",
            vic="Last call. The saloon doors stop swinging.",
            defeat="Face down on the bar. Tab unpaid.",
        ),
        ds(
            tiles=[
                {"name": "hopper wall", "walkable": False, "color": "#181410"},
                {"name": "conveyor belt", "walkable": True, "color": "#242018"},
                {"name": "crusher grating", "walkable": True, "color": "#2e2820"},
                {"name": "mineral dust floor", "walkable": True, "color": "#201c14"},
            ],
            boss="Mill Hag Grinder",
            boss_desc="Fused with the machinery. Feeds it bodies.",
            mons=["Conveyor Lurker", "Crusher Jaw", "Hopper Mimic"],
            weapon="Grinding Wheel Fragment",
            weapon_desc="A shard of industrial diamond. Shreds anything.",
            armor="Sluice Operator's Rig",
            armor_desc="Built to survive industrial accidents. Mostly.",
            traps=["Conveyor Pull", "Crusher Slam", "Dust Explosion"],
            root="C", scale="dorian",
            vic="The machinery shudders and stops. Real silence at last.",
            defeat="The conveyor carries you to the crusher. It's patient.",
        ),
        ds(
            tiles=[
                {"name": "deep rock face", "walkable": False, "color": "#141008"},
                {"name": "crystal-veined floor", "walkable": True, "color": "#221c10"},
                {"name": "pressure crack", "walkable": True, "color": "#1a1408"},
                {"name": "glowing seam", "walkable": True, "color": "#282014"},
            ],
            boss="The Motherlode",
            boss_desc="Living mineral vein. Grew teeth. Grew hunger.",
            mons=["Crystal Biter", "Vein Crawler", "Seam Ripper"],
            weapon="Core Sample Spear",
            weapon_desc="Diamond-tipped drill bit on a shaft. Penetrates.",
            armor="Geological Survey Suit",
            armor_desc="Rated for pressure and heat. Not for teeth.",
            traps=["Seam Collapse", "Crystal Shatter", "Gas Pocket"],
            root="F#", scale="phrygian",
            vic="The motherlode splits open. It was real after all.",
            defeat="The vein grows over you. A new inclusion.",
        ),
        ds(
            tiles=[
                {"name": "barricade wall", "walkable": False, "color": "#1a1610"},
                {"name": "stash floor", "walkable": True, "color": "#282218"},
                {"name": "trip-wire alley", "walkable": True, "color": "#2e2820"},
                {"name": "stolen crate", "walkable": True, "color": "#322a1e"},
            ],
            boss="Rattlesnake Fenn",
            boss_desc="Fastest draw in the system. Twitchy. Paranoid.",
            mons=["Claim Jumper", "Booby Trap", "Lookout Drone"],
            weapon="Stolen Sidearm",
            weapon_desc="Serial number filed off. Kicks like a mule.",
            armor="Scavenged Flak Jacket",
            armor_desc="Three different sizes stitched together. Functional.",
            traps=["Tripwire Blast", "Pitfall", "Shotgun Trap"],
            root="A", scale="pentatonic_minor",
            vic="Fenn's stash is yours. Enough to get off this rock.",
            defeat="Fenn was right to be paranoid. You proved it.",
        ),
    ],
))

# ─────────────────────────────────────────────
# 4. NYX NEBULA
# Dark nebula. Exotic matter mining. Something ancient.
# ─────────────────────────────────────────────
batch.append(camp(
    name="Nyx Nebula",
    desc="A dark nebula where no starlight penetrates. Mining crews extract exotic matter from the void. Something ancient stirs in the core, dreaming of light it consumed eons ago.",
    bg="#06060a",
    text="#a0a8c0",
    font="Megrim",
    dfont="Share Tech Mono",
    lfont="Poiret One",
    levels=[
        lv("Lamplight Station", "Poiret One",
           "The outermost platform. Floodlights carve a sphere of visibility into absolute dark.",
           "powerful floodlights, absolute darkness beyond, moths drawn to the light, humming generators",
           "#7080a0", ["#08080e", "#181c28", "#303848", "#4c5870", "#6c80a0"], B[0]),
        lv("The Blind Dig", "Poiret One",
           "Miners extract exotic matter by touch and sonar. Headlamps fail within minutes.",
           "sonar equipment, tactile markers, dead headlamps, exotic matter veins glowing faintly",
           "#6070a0", ["#060810", "#141a2a", "#283048", "#404a6a", "#5a6890"], B[1]),
        lv("Echo Chamber", "Poiret One",
           "A hollow space in the nebula where sound carries for miles. The miners hear things.",
           "vast acoustic chamber, resonating walls, whisper networks, sound-absorbing panels failing",
           "#5868a0", ["#06080e", "#141820", "#283040", "#404860", "#5a6888"], B[2]),
        lv("The Sunken Archive", "Poiret One",
           "Pre-human ruins. Something built this deep in the dark, long before we came.",
           "alien architecture, non-euclidean corridors, glyphs that hurt to read, preserved atmosphere",
           "#8070b0", ["#0a0810", "#1e1828", "#362e48", "#524870", "#706898"], B[3]),
        lv("The Sleeper's Throat", "Poiret One",
           "The nebula's core. Something breathes here. The walls pulse.",
           "organic-looking walls, rhythmic pulsing, warm air, bioluminescent veins, vast scale",
           "#6060a8", ["#060610", "#121228", "#222244", "#363668", "#4e4e90"], B[4]),
        lv("Photon Trap", "Poiret One",
           "Where light goes to die. Captured photons swirl in a prison of dark matter.",
           "swirling captured light, dark matter lattice, photon decay, strange beauty in the dark",
           "#8090a0", ["#080a0e", "#181e28", "#303a48", "#4c5a70", "#6c809e"], B[5]),
    ],
    store={"healing_potions": 5, "speed_potions": 3, "bombs": 3},
    designs=[
        ds(
            tiles=[
                {"name": "floodlight housing", "walkable": False, "color": "#10121a"},
                {"name": "illuminated deck", "walkable": True, "color": "#1c2030"},
                {"name": "shadow fringe", "walkable": True, "color": "#141828"},
                {"name": "moth-clustered panel", "walkable": True, "color": "#1e222e"},
            ],
            boss="Keeper Noctis",
            boss_desc="Tends the lights. Hasn't slept in months.",
            mons=["Void Moth", "Shadow Feeder", "Lamp Phantom"],
            weapon="Floodlight Rod",
            weapon_desc="A portable sun. Blinds and burns.",
            armor="Lamplighter's Cloak",
            armor_desc="Reflective lining. Bounces darkness away.",
            traps=["Bulb Burst", "Shadow Pool", "Generator Failure"],
            root="D", scale="aeolian",
            vic="The floodlights hold. The dark stays outside. For now.",
            defeat="The last bulb pops. The dark rushes in.",
        ),
        ds(
            tiles=[
                {"name": "sonar-mapped wall", "walkable": False, "color": "#0c0e18"},
                {"name": "tactile-marked floor", "walkable": True, "color": "#161a28"},
                {"name": "exotic matter seam", "walkable": True, "color": "#1a1e30"},
                {"name": "dead headlamp zone", "walkable": True, "color": "#101420"},
            ],
            boss="Blindside Krug",
            boss_desc="Lost eyes years ago. Fights by hearing.",
            mons=["Bore Worm", "Echo Hunter", "Matter Leech"],
            weapon="Sonar Pickaxe",
            weapon_desc="Pings on impact. You hear what you hit.",
            armor="Tactile Mesh Suit",
            armor_desc="Vibrates on contact. You feel attacks coming.",
            traps=["Sonar Blackout", "Matter Flare", "Blind Drop"],
            root="F", scale="phrygian",
            vic="The dig yields its treasure. You can almost see it glow.",
            defeat="You stop hearing. The dark takes the rest.",
        ),
        ds(
            tiles=[
                {"name": "resonating wall", "walkable": False, "color": "#0e1018"},
                {"name": "acoustic tile", "walkable": True, "color": "#181c28"},
                {"name": "whisper channel", "walkable": True, "color": "#141820"},
                {"name": "dampened alcove", "walkable": True, "color": "#1a1e2a"},
            ],
            boss="The Echo",
            boss_desc="Your own voice. Weeks delayed. Angry now.",
            mons=["Resonance Fiend", "Whisper Stalker", "Sound Worm"],
            weapon="Tuning Fork Mace",
            weapon_desc="Vibrates at lethal frequency on impact.",
            armor="Acoustic Dampener Vest",
            armor_desc="Deadens sound. Makes you harder to find.",
            traps=["Sonic Burst", "Echo Loop", "Resonance Shatter"],
            root="B", scale="dorian",
            vic="The chamber falls silent. Your echoes stop answering.",
            defeat="Your scream echoes forever. A new voice in the chamber.",
        ),
        ds(
            tiles=[
                {"name": "alien stonework", "walkable": False, "color": "#12101e"},
                {"name": "glyph-carved floor", "walkable": True, "color": "#1e1a30"},
                {"name": "preserved corridor", "walkable": True, "color": "#1a1628"},
                {"name": "rune-lit path", "walkable": True, "color": "#221e34"},
            ],
            boss="Curator Void",
            boss_desc="Librarian of dead gods. Reads from skin-books.",
            mons=["Glyph Golem", "Archive Shade", "Rune Crawler"],
            weapon="Inscribed Bone Blade",
            weapon_desc="Pre-human. The glyphs still burn.",
            armor="Archive Keeper's Robe",
            armor_desc="Alien fabric. Absorbs knowledge and damage.",
            traps=["Glyph Trigger", "Archive Collapse", "Mind Snare"],
            root="E", scale="locrian",
            vic="The archive seals itself. Some knowledge stays buried.",
            defeat="The glyphs write themselves on your skin. You become a page.",
        ),
        ds(
            tiles=[
                {"name": "organic membrane wall", "walkable": False, "color": "#0c0a14"},
                {"name": "pulsing floor tissue", "walkable": True, "color": "#161422"},
                {"name": "bioluminescent vein", "walkable": True, "color": "#1a162a"},
                {"name": "breathing passage", "walkable": True, "color": "#14121e"},
            ],
            boss="The Sleeper",
            boss_desc="Ancient. Nebula-sized. You're inside its dream.",
            mons=["Dream Parasite", "Neural Spark", "Subconscious Tendril"],
            weapon="Nightmare Spike",
            weapon_desc="Forged from a bad dream. Wounds don't heal.",
            armor="Lucid Shell",
            armor_desc="Keeps you awake inside the dream. Barely.",
            traps=["Sleep Pulse", "Dream Collapse", "Neural Shock"],
            root="F#", scale="whole_tone",
            vic="The Sleeper rolls over. The nebula shifts. It doesn't wake.",
            defeat="You become part of the dream. You were always part of the dream.",
        ),
        ds(
            tiles=[
                {"name": "dark matter lattice", "walkable": False, "color": "#0a0c14"},
                {"name": "photon swirl floor", "walkable": True, "color": "#141822"},
                {"name": "light decay zone", "walkable": True, "color": "#10141c"},
                {"name": "captured spectrum", "walkable": True, "color": "#181c28"},
            ],
            boss="Warden Null",
            boss_desc="Guards the trapped light. Made of absence.",
            mons=["Photon Eater", "Dark Lattice Node", "Decay Sprite"],
            weapon="Liberated Photon Whip",
            weapon_desc="Freed light. Angry light. Burns hot.",
            armor="Null-Resistant Plating",
            armor_desc="Refuses to be negated. Stubbornly exists.",
            traps=["Light Drain Well", "Dark Matter Snare", "Photon Collapse"],
            root="G", scale="pentatonic_minor",
            vic="The trapped light escapes. A brief new star in the dark.",
            defeat="Your light joins the collection. Swirling. Fading.",
        ),
    ],
))

# ─────────────────────────────────────────────
# 5. FERRO CASCADE
# Molten iron waterfalls. Industrial hellscape.
# ─────────────────────────────────────────────
batch.append(camp(
    name="Ferro Cascade",
    desc="A waterfall of molten iron pours between stations welded to asteroid walls. Forges glow, smelters roar, and the air tastes of burning metal.",
    bg="#100804",
    text="#e8c0a0",
    font="Audiowide",
    dfont="Exo 2",
    lfont="Saira",
    levels=[
        lv("Ingot Landing", "Saira",
           "Where the raw iron is caught in massive crucibles. Sparks rain constantly.",
           "enormous crucibles, spark showers, conveyor systems, molten splash guards",
           "#c08040", ["#180c04", "#3a2010", "#6a4020", "#a06030", "#d08848"], B[0]),
        lv("The Foundry Floor", "Saira",
           "Casting hall. Rivers of liquid metal in channels cut into the floor.",
           "casting channels of molten iron, mold racks, pouring stations, heat shimmer",
           "#d09050", ["#1a0e06", "#3e2412", "#6e4824", "#a06e38", "#d09850"], B[1]),
        lv("Slag Heap", "Saira",
           "Where the waste goes. Mountains of cooling slag. Things live in the warm spots.",
           "cooling slag mountains, glowing crevices, toxic fumes, scavenger shelters",
           "#a07040", ["#140a04", "#30180c", "#5a3418", "#885028", "#b87040"], B[2]),
        lv("The Hammer Hall", "Saira",
           "Forge proper. Massive pneumatic hammers shape station hull plates. Deafening.",
           "giant pneumatic hammers, anvil stations, shaping dies, sparks and steam",
           "#e0a060", ["#1c1008", "#402810", "#704820", "#a87038", "#e09850"], B[3]),
        lv("Cascade Core", "Saira",
           "The source of the iron river. A ruptured asteroid vein pouring since before anyone arrived.",
           "ruptured asteroid wall, endless iron flow, ancient mining equipment, the roar of liquid metal",
           "#c07030", ["#140804", "#301808", "#5a3010", "#884820", "#b86830"], B[4]),
        lv("The Quench Tank", "Saira",
           "Cooling reservoir. Steam clouds reduce visibility to nothing. Shapes move in the fog.",
           "massive cooling tanks, steam clouds, quenched metal hissing, condensation everywhere",
           "#8090a0", ["#0a0c10", "#1a2028", "#2e3a48", "#485868", "#687888"], B[5]),
    ],
    store={"healing_potions": 3, "speed_potions": 1, "bombs": 2},
    designs=[
        ds(
            tiles=[
                {"name": "crucible wall", "walkable": False, "color": "#2a1408"},
                {"name": "spark-scarred floor", "walkable": True, "color": "#3a2410"},
                {"name": "splash guard", "walkable": True, "color": "#302014"},
                {"name": "cooling channel", "walkable": True, "color": "#281a0c"},
            ],
            boss="Crucible Master Varn",
            boss_desc="Pours iron by hand. Skin like cast metal.",
            mons=["Spark Swarm", "Crucible Crawler", "Slag Hound"],
            weapon="Casting Ladle",
            weapon_desc="Full of molten iron. Flings on swing.",
            armor="Fireproof Smock",
            armor_desc="Asbestos-woven. Blocks heat. Probably toxic.",
            traps=["Molten Splash", "Spark Shower", "Crucible Overflow"],
            root="C", scale="mixolydian",
            vic="The crucibles cool. Sparks settle like dying fireflies.",
            defeat="You fall into the crucible. A brief impurity.",
        ),
        ds(
            tiles=[
                {"name": "casting mold wall", "walkable": False, "color": "#241208"},
                {"name": "channel-cut floor", "walkable": True, "color": "#342010"},
                {"name": "iron river bank", "walkable": True, "color": "#2e1c0e"},
                {"name": "pouring platform", "walkable": True, "color": "#3a2614"},
            ],
            boss="Riveter Skarn",
            boss_desc="Drives rivets through anything. Including people.",
            mons=["Iron Serpent", "Casting Flash", "Mold Mimic"],
            weapon="Rivet Gun",
            weapon_desc="Industrial grade. Punches through hull plate.",
            armor="Foundry Worker's Shell",
            armor_desc="Cast iron plates over leather. Heavy. Proven.",
            traps=["Iron River Splash", "Mold Collapse", "Steam Burn"],
            root="A", scale="phrygian",
            vic="The rivers cool to solid roads. Safe to walk.",
            defeat="The iron river finds a new channel. Through you.",
        ),
        ds(
            tiles=[
                {"name": "slag crust", "walkable": False, "color": "#1e1008"},
                {"name": "warm ash path", "walkable": True, "color": "#2a1a0e"},
                {"name": "glowing crevice", "walkable": True, "color": "#301e0c"},
                {"name": "cooled slag plate", "walkable": True, "color": "#241610"},
            ],
            boss="Slag Queen Pyra",
            boss_desc="Lives in the heat. Breeds things in slag.",
            mons=["Slag Beetle", "Ash Crawler", "Ember Mite"],
            weapon="Slag Hammer",
            weapon_desc="Crude slag on a pipe. Shatters on impact. Both ways.",
            armor="Slag Crust Plate",
            armor_desc="Cooled slag shaped to fit. Brittle but thick.",
            traps=["Crust Collapse", "Slag Vent", "Ember Burst"],
            root="F", scale="dorian",
            vic="The heap cools to silence. The queen's brood goes still.",
            defeat="The slag closes over you. Warm burial.",
        ),
        ds(
            tiles=[
                {"name": "hammer housing", "walkable": False, "color": "#201008"},
                {"name": "anvil floor", "walkable": True, "color": "#2e1c10"},
                {"name": "shaping die", "walkable": True, "color": "#342214"},
                {"name": "steam vent grate", "walkable": True, "color": "#281810"},
            ],
            boss="Hammersworn Kael",
            boss_desc="Rhythmic. Relentless. Hammers never stop swinging.",
            mons=["Pneumatic Striker", "Forge Sprite", "Anvil Shade"],
            weapon="Drop Hammer Fist",
            weapon_desc="Pneumatic gauntlet. One punch shapes steel.",
            armor="Anvil-Born Plate",
            armor_desc="Hammered to fit your body exactly. Perfect defense.",
            traps=["Hammer Drop", "Steam Blast", "Die Press"],
            root="G", scale="aeolian",
            vic="The hammers fall silent. The ringing in your ears doesn't.",
            defeat="The hammer shapes you flat. Another hull plate.",
        ),
        ds(
            tiles=[
                {"name": "asteroid wall", "walkable": False, "color": "#1a0c04"},
                {"name": "iron-flow channel", "walkable": True, "color": "#2a1808"},
                {"name": "ruptured vein floor", "walkable": True, "color": "#221208"},
                {"name": "ancient scaffold", "walkable": True, "color": "#301c0c"},
            ],
            boss="The Cascade",
            boss_desc="Not a person. The iron flow itself. Angry.",
            mons=["Iron Elemental", "Flow Tendril", "Vein Parasite"],
            weapon="Magnetite Core Lance",
            weapon_desc="Pulls iron toward it. Or away. Your choice.",
            armor="Ferromagnetic Shell",
            armor_desc="Controls nearby iron. Deflects molten attacks.",
            traps=["Iron Surge", "Vein Rupture", "Magnetic Reversal"],
            root="Bb", scale="locrian",
            vic="The cascade freezes mid-pour. Silence in the forge.",
            defeat="The iron river swallows you. Another mineral in the flow.",
        ),
        ds(
            tiles=[
                {"name": "tank wall", "walkable": False, "color": "#141820"},
                {"name": "wet grating", "walkable": True, "color": "#1e2830"},
                {"name": "steam pocket", "walkable": True, "color": "#222e38"},
                {"name": "condensation pool", "walkable": True, "color": "#1a2028"},
            ],
            boss="Quencher Haze",
            boss_desc="Steam given form. Scalds on contact. Everywhere.",
            mons=["Steam Phantom", "Condensation Creeper", "Quench Sprite"],
            weapon="Pressure Release Valve",
            weapon_desc="Vents superheated steam in a lethal jet.",
            armor="Coolant Suit",
            armor_desc="Circulates cold water. Keeps you from cooking.",
            traps=["Steam Geyser", "Scalding Pool", "Pressure Burst"],
            root="E", scale="blues",
            vic="The steam clears. Cool air rushes in. You can see again.",
            defeat="The steam finds every gap in your suit.",
        ),
    ],
))

# ─────────────────────────────────────────────
# 6. ACHERON DEEP
# Submarine stations on a volcanic ocean moon.
# ─────────────────────────────────────────────
batch.append(camp(
    name="Acheron Deep",
    desc="Submarine stations on a volcanic ocean moon. Hydrothermal vents light the abyss. Bioluminescent predators circle in the dark water. Pressure never lets you forget where you are.",
    bg="#04080c",
    text="#80c8d8",
    font="Michroma",
    dfont="Rajdhani",
    lfont="Gruppo",
    levels=[
        lv("Docking Submersible", "Gruppo",
           "The entry sub. Cramped, leaking, and descending into darkness.",
           "cramped submarine interior, leaking seals, depth gauge climbing, porthole views of darkness",
           "#4090a0", ["#040a0e", "#0e1e28", "#1e3848", "#305868", "#487890"], B[0]),
        lv("Vent Colony", "Gruppo",
           "A cluster of habitats around a hydrothermal vent. The warmth keeps the pressure seals soft.",
           "hydrothermal vent glow, mineral chimneys, warm water currents, bacterial mats",
           "#40a088", ["#040e0a", "#0e281e", "#1e4838", "#306850", "#488870"], B[1]),
        lv("The Anglerway", "Gruppo",
           "A pressurized tunnel lit by bioluminescent creatures trapped in the walls.",
           "bioluminescent wall panels, pressure-groaning tunnel, trapped light organisms, deep current vibrations",
           "#3088a8", ["#040810", "#0e1c2a", "#1e3448", "#305068", "#487090"], B[2]),
        lv("Magma Vent Station", "Gruppo",
           "Research platform built directly over an underwater volcano. The floor is warm.",
           "volcanic glass viewports, magma glow from below, heat exchangers, geological sensors",
           "#c06030", ["#140804", "#301808", "#583010", "#884820", "#b86830"], B[3]),
        lv("The Trench Throne", "Gruppo",
           "The deepest point. Something enormous lives here and has been worshipped by the colonists.",
           "abyssal depth, massive bioluminescent organism, pressure-warped architecture, devotional carvings",
           "#3060a0", ["#04060e", "#0e1428", "#1e2848", "#304068", "#485c90"], B[4]),
        lv("Flooded Lab", "Gruppo",
           "Marine biology station. Containment breach. The specimens are loose.",
           "shattered aquarium tanks, flooded corridors, escaped specimens, sparking electronics",
           "#4088a0", ["#04080e", "#0e1c28", "#1e3448", "#305068", "#487088"], B[5]),
    ],
    store={"healing_potions": 4, "speed_potions": 2, "bombs": 2},
    designs=[
        ds(
            tiles=[
                {"name": "pressure hull", "walkable": False, "color": "#0c1820"},
                {"name": "deck grating", "walkable": True, "color": "#142430"},
                {"name": "leaking seal", "walkable": True, "color": "#102028"},
                {"name": "porthole alcove", "walkable": True, "color": "#182a38"},
            ],
            boss="Captain Brine",
            boss_desc="Goes down with every ship. Keeps surviving.",
            mons=["Pressure Sprite", "Bilge Creeper", "Seal Breach"],
            weapon="Depth Charge Pistol",
            weapon_desc="Fires miniature implosion charges. Messy.",
            armor="Dive Suit",
            armor_desc="Rated to 200 atmospheres. You're at 180.",
            traps=["Hull Breach", "Pressure Spike", "Flooding Compartment"],
            root="D", scale="dorian",
            vic="The sub stabilizes. Ascent is possible. Maybe.",
            defeat="The hull groans once. Then collapses inward.",
        ),
        ds(
            tiles=[
                {"name": "mineral chimney", "walkable": False, "color": "#0a1818"},
                {"name": "bacterial mat floor", "walkable": True, "color": "#142828"},
                {"name": "vent-warmed tile", "walkable": True, "color": "#183028"},
                {"name": "thermal channel", "walkable": True, "color": "#102420"},
            ],
            boss="Thermarch Kelda",
            boss_desc="Adapted to boiling water. Skin like lobster shell.",
            mons=["Vent Shrimp Swarm", "Thermal Worm", "Sulfur Ghost"],
            weapon="Thermal Lance",
            weapon_desc="Heats water to plasma. Cuts through anything wet.",
            armor="Thermal Regulation Suit",
            armor_desc="Keeps your core temp stable in boiling currents.",
            traps=["Boiling Vent", "Sulfur Cloud", "Chimney Collapse"],
            root="G", scale="mixolydian",
            vic="The vent cools. The colony shivers for the first time.",
            defeat="The vent boils you. A quick reduction.",
        ),
        ds(
            tiles=[
                {"name": "pressure-groaning wall", "walkable": False, "color": "#081420"},
                {"name": "bioluminescent panel", "walkable": True, "color": "#102030"},
                {"name": "tunnel grating", "walkable": True, "color": "#0e1c2a"},
                {"name": "organism alcove", "walkable": True, "color": "#142434"},
            ],
            boss="Anglerqueen Maw",
            boss_desc="Largest bioluminescent predator. Lure looks friendly.",
            mons=["Lure Fish", "Tunnel Eel", "Pressure Crab"],
            weapon="Harpoon Gun",
            weapon_desc="Pneumatic. One shot. Make it count.",
            armor="Anti-Bite Mesh",
            armor_desc="Chainmail for the deep. Teeth slide off.",
            traps=["Lure Trap", "Tunnel Flood", "Pressure Crush"],
            root="Bb", scale="aeolian",
            vic="The anglerway goes dark. Then real light returns.",
            defeat="You follow the pretty light. Everyone follows the pretty light.",
        ),
        ds(
            tiles=[
                {"name": "volcanic glass wall", "walkable": False, "color": "#1a0c08"},
                {"name": "heat exchanger floor", "walkable": True, "color": "#2a1810"},
                {"name": "magma viewport", "walkable": True, "color": "#221410"},
                {"name": "sensor platform", "walkable": True, "color": "#2e1c14"},
            ],
            boss="Vulcanist Pyre",
            boss_desc="Worships the volcano. Wants to open it.",
            mons=["Magma Sprite", "Basalt Crawler", "Vent Worm"],
            weapon="Obsidian Blade",
            weapon_desc="Volcanic glass edge. Sharper than steel.",
            armor="Basalt Fiber Suit",
            armor_desc="Woven from volcanic rock fiber. Fireproof.",
            traps=["Magma Fissure", "Glass Shatter", "Heat Surge"],
            root="F#", scale="phrygian",
            vic="The volcano settles. The ocean stops boiling. Barely.",
            defeat="The magma rises. The station melts from below.",
        ),
        ds(
            tiles=[
                {"name": "abyssal wall", "walkable": False, "color": "#060a14"},
                {"name": "devotional floor", "walkable": True, "color": "#0e1424"},
                {"name": "bioluminescent carpet", "walkable": True, "color": "#121a2c"},
                {"name": "carved offering niche", "walkable": True, "color": "#101828"},
            ],
            boss="The Benthic Sovereign",
            boss_desc="Kraken-scale organism. Worshipped as god. Might be.",
            mons=["Devotee Diver", "Tentacle Tip", "Abyssal Acolyte"],
            weapon="Trident of the Deep",
            weapon_desc="Carved from the Sovereign's shed tooth. Ironic.",
            armor="Abyssal Pressure Suit",
            armor_desc="Maximum depth rating. Beyond it, faith.",
            traps=["Crushing Depth", "Tentacle Grab", "Devotion Snare"],
            root="E", scale="locrian",
            vic="The Sovereign sinks deeper. The worship ends. The pressure eases.",
            defeat="You kneel. The pressure makes it permanent.",
        ),
        ds(
            tiles=[
                {"name": "shattered tank wall", "walkable": False, "color": "#081418"},
                {"name": "flooded floor", "walkable": True, "color": "#102028"},
                {"name": "sparking console", "walkable": True, "color": "#142430"},
                {"name": "specimen debris", "walkable": True, "color": "#0e1c24"},
            ],
            boss="Specimen Omega",
            boss_desc="The prize catch. Broke containment. Adapts instantly.",
            mons=["Escaped Polyp", "Lab Lamprey", "Tank Fragment"],
            weapon="Specimen Prod",
            weapon_desc="Electrified handling tool. High voltage now.",
            armor="Lab Hazmat Suit",
            armor_desc="Rated for biological threats. Not for this.",
            traps=["Electrified Water", "Tank Burst", "Specimen Ambush"],
            root="A", scale="blues",
            vic="Specimen Omega goes still. Containment can be rebuilt.",
            defeat="You become the next specimen. Omega adapts you too.",
        ),
    ],
))

# ─────────────────────────────────────────────
# 7. NIGHTJAR
# Camouflaged stations. Pirates, smugglers, the hidden.
# ─────────────────────────────────────────────
batch.append(camp(
    name="Nightjar",
    desc="Camouflaged stations hidden in a dense asteroid field. Pirates, smugglers, and people who don't want to be found. Every approach vector is a death trap.",
    bg="#0a0a08",
    text="#b8b0a0",
    font="Pirata One",
    dfont="Share Tech Mono",
    lfont="Nova Square",
    levels=[
        lv("The Approach", "Nova Square",
           "A maze of rigged asteroids. Wrong turn means mines. Right turn means guns.",
           "asteroid corridors, hidden mines, camouflaged gun emplacements, debris-choked passages",
           "#8a8070", ["#0e0c08", "#222018", "#3e3a28", "#5e5840", "#807860"], B[0]),
        lv("Smuggler's Berth", "Nova Square",
           "Hidden docking bay. Ships with fake transponders. Cargo that doesn't exist on paper.",
           "concealed docking clamps, false-hulled ships, contraband containers, scanner jammers",
           "#908878", ["#0c0c08", "#20201a", "#3a382e", "#585648", "#787668"], B[1]),
        lv("The Blind Bazaar", "Nova Square",
           "Market where faces are hidden and names are lies. Everything is for sale.",
           "masked vendors, hooded alcoves, anonymous transaction terminals, blackout curtains",
           "#a09880", ["#100e0a", "#28261e", "#44403a", "#646050", "#888470"], B[2]),
        lv("Pirate King's Gallery", "Nova Square",
           "Trophy hall of a pirate fleet commander. Ship nameplates line the walls.",
           "stolen ship nameplates, trophy cases, captured flags, a throne of navigation consoles",
           "#a08858", ["#100c06", "#282012", "#483820", "#685430", "#907448"], B[3]),
        lv("The Vault", "Nova Square",
           "Where Nightjar keeps its real treasure. Behind every lock ever invented.",
           "layered security doors, biometric locks, laser grids, the hum of magnetic containment",
           "#708090", ["#080a0e", "#181e28", "#2e3848", "#485868", "#647888"], B[4]),
        lv("Rat Run", "Nova Square",
           "Escape tunnels through the asteroid. For when the law finally comes.",
           "narrow escape tunnels, emergency airlocks, stashed getaway pods, booby-trapped dead ends",
           "#8a8070", ["#0c0a08", "#201e16", "#383628", "#545040", "#706c5c"], B[5]),
    ],
    store={"healing_potions": 3, "speed_potions": 1, "bombs": 2},
    designs=[
        ds(
            tiles=[
                {"name": "rigged asteroid", "walkable": False, "color": "#181410"},
                {"name": "mine-cleared path", "walkable": True, "color": "#242018"},
                {"name": "gun emplacement", "walkable": True, "color": "#2a2420"},
                {"name": "debris channel", "walkable": True, "color": "#1e1a14"},
            ],
            boss="Sweeper Jacks",
            boss_desc="Clears the mines. Plants new ones behind you.",
            mons=["Proximity Drone", "Camouflaged Turret", "Rock Lurker"],
            weapon="Mine Clicker",
            weapon_desc="Remote detonator. Point and click.",
            armor="Blast-Resistant Jacket",
            armor_desc="Designed for mine clearance. Tested frequently.",
            traps=["Proximity Mine", "Rigged Asteroid", "Hidden Turret"],
            root="D", scale="phrygian",
            vic="The approach clears. Safe passage. Until they re-mine it.",
            defeat="Click. You hear it before you feel it.",
        ),
        ds(
            tiles=[
                {"name": "concealed dock wall", "walkable": False, "color": "#141410"},
                {"name": "loading bay floor", "walkable": True, "color": "#22221a"},
                {"name": "contraband crate", "walkable": True, "color": "#282620"},
                {"name": "jammer platform", "walkable": True, "color": "#1e1e16"},
            ],
            boss="Dockhand Whisper",
            boss_desc="Knows every secret cargo. Silence costs extra.",
            mons=["Cargo Mimic", "Scanner Jammer Bug", "Berth Rat"],
            weapon="Smuggler's Compact",
            weapon_desc="Tiny, hidden, lethal. Like its owner.",
            armor="False-Bottom Vest",
            armor_desc="Hidden armor panels. Looks like a jacket.",
            traps=["Falling Cargo", "Jammer Pulse", "Airlock Cycle"],
            root="A", scale="dorian",
            vic="The berth empties. Every ship runs dark. Whisper talks.",
            defeat="Sealed in a cargo container. Destination unknown.",
        ),
        ds(
            tiles=[
                {"name": "blackout curtain", "walkable": False, "color": "#121010"},
                {"name": "market tile", "walkable": True, "color": "#201e18"},
                {"name": "hooded alcove", "walkable": True, "color": "#1a1814"},
                {"name": "transaction terminal", "walkable": True, "color": "#241e1a"},
            ],
            boss="The Broker",
            boss_desc="No face. No name. Knows yours. Knows everything.",
            mons=["Masked Enforcer", "Pickpocket Ghost", "Deal Breaker"],
            weapon="Poisoned Coin",
            weapon_desc="Currency that cuts. Contact toxin on the edge.",
            armor="Anonymity Cloak",
            armor_desc="Face-scrambling fabric. Can't be identified or targeted.",
            traps=["Rigged Transaction", "Identity Trap", "Blackout Zone"],
            root="F", scale="aeolian",
            vic="The Broker's mask falls. Just a person underneath. Scared.",
            defeat="Your identity is sold. You stop existing on paper.",
        ),
        ds(
            tiles=[
                {"name": "trophy wall", "walkable": False, "color": "#1a1408"},
                {"name": "gallery floor", "walkable": True, "color": "#282010"},
                {"name": "display case", "walkable": True, "color": "#2e2614"},
                {"name": "throne platform", "walkable": True, "color": "#322a18"},
            ],
            boss="Pirate King Corsair",
            boss_desc="Stole a fleet. Stole a station. Wants more.",
            mons=["Corsair Guard", "Trophy Hunter", "Nameplate Specter"],
            weapon="Captain's Cutlass",
            weapon_desc="Taken from a navy admiral. Ceremonial. Sharp.",
            armor="Stolen Officer's Coat",
            armor_desc="Ballistic weave. The original owner didn't need it anymore.",
            traps=["Collapsing Trophy Case", "Throne Trap", "Guard Alert"],
            root="G", scale="mixolydian",
            vic="The king's crown rolls across the floor. The fleet scatters.",
            defeat="Your nameplate joins the gallery. Another trophy.",
        ),
        ds(
            tiles=[
                {"name": "vault door", "walkable": False, "color": "#101420"},
                {"name": "security grid floor", "walkable": True, "color": "#1a2030"},
                {"name": "laser grid zone", "walkable": True, "color": "#1e2438"},
                {"name": "containment field", "walkable": True, "color": "#141c28"},
            ],
            boss="Locksmith Zero",
            boss_desc="Built every lock here. Knows every bypass. Almost.",
            mons=["Security Drone", "Laser Grid Node", "Vault Guardian"],
            weapon="Bypass Key",
            weapon_desc="Opens any lock. Also stabs. Multi-purpose.",
            armor="EMP-Hardened Suit",
            armor_desc="Security systems can't touch you. Mostly.",
            traps=["Laser Grid", "Vault Seal", "EMP Pulse"],
            root="B", scale="lydian",
            vic="The vault opens. Everything Nightjar stole. Now yours.",
            defeat="Locked inside the vault. No one coming to open it.",
        ),
        ds(
            tiles=[
                {"name": "tunnel rock", "walkable": False, "color": "#141210"},
                {"name": "escape passage", "walkable": True, "color": "#201e18"},
                {"name": "airlock junction", "walkable": True, "color": "#1c1a14"},
                {"name": "stashed pod bay", "walkable": True, "color": "#24221c"},
            ],
            boss="Ratcatcher Vex",
            boss_desc="Guards the exits. No one leaves without paying.",
            mons=["Tunnel Rat", "Booby Trap Bot", "Dead-End Ghost"],
            weapon="Escape Pod Launcher",
            weapon_desc="Fires pod components. Improvised but painful.",
            armor="Tunnel Runner's Gear",
            armor_desc="Light, flexible, fireproof. Made for running.",
            traps=["Dead End Collapse", "Airlock Trap", "Stashed Explosive"],
            root="C", scale="pentatonic_minor",
            vic="The rat run leads out. Open space. Freedom.",
            defeat="Every tunnel ends the same way. Sealed.",
        ),
    ],
))

# ─────────────────────────────────────────────
# 8. FROSTBITE
# Ice giant's frozen moons. Buried alien artifacts.
# ─────────────────────────────────────────────
batch.append(camp(
    name="Frostbite",
    desc="Stations carved into the frozen moons of an ice giant. Glaciers crack overhead, alien artifacts surface from the thaw, and the cold seeps into everything.",
    bg="#06090e",
    text="#b0d0e0",
    font="Poiret One",
    dfont="Electrolize",
    lfont="Gruppo",
    levels=[
        lv("Glacier Gate", "Gruppo",
           "Entry carved into a glacier face. Ice walls glow pale blue. The cold is immediate.",
           "glacial entrance, pale blue ice walls, frozen breath, cracking sounds overhead",
           "#6090b0", ["#060a10", "#141e2e", "#28384e", "#405870", "#5a7898"], B[0]),
        lv("The Permafrost Lab", "Gruppo",
           "Research station studying ancient ice cores. Some cores have things inside them.",
           "ice core samples, microscope stations, frozen specimens, slowly thawing containment",
           "#70a0c0", ["#080c14", "#18222e", "#2c3e50", "#445c72", "#607e98"], B[1]),
        lv("Crevasse Town", "Gruppo",
           "A settlement built in a massive ice crevasse. Bridges span the gap. Don't look down.",
           "ice bridges, crevasse walls, suspended platforms, howling wind from below",
           "#5088a8", ["#060810", "#141c28", "#283444", "#405060", "#5a7080"], B[2]),
        lv("The Thaw Chamber", "Gruppo",
           "Where the alien artifacts are thawed. Some of them wake up.",
           "heated thaw bays, alien artifacts mid-emergence, monitoring equipment, containment cells",
           "#80a0b0", ["#080c10", "#1a2430", "#303e50", "#4a5c70", "#687e98"], B[3]),
        lv("Absolute Zero Core", "Gruppo",
           "The moon's frozen heart. Temperature approaches absolute zero. The artifacts lead here.",
           "crystalline ice formations, near-zero temperatures, alien machinery frozen in ice, reality warping cold",
           "#4878a8", ["#04080e", "#101c2e", "#203048", "#304868", "#486088"], B[4]),
        lv("Hot Spring Grotto", "Gruppo",
           "A geothermal pocket in the ice. Warm water, alien flora, and things that shouldn't grow here.",
           "steaming pools, alien plant growth, warm mist, ice ceiling dripping, impossible garden",
           "#60a090", ["#040e0a", "#102820", "#204838", "#386850", "#508870"], B[5]),
    ],
    store={"healing_potions": 4, "speed_potions": 2, "bombs": 2},
    designs=[
        ds(
            tiles=[
                {"name": "glacial wall", "walkable": False, "color": "#0c1824"},
                {"name": "ice floor", "walkable": True, "color": "#142430"},
                {"name": "frozen grating", "walkable": True, "color": "#182838"},
                {"name": "frost-rimed deck", "walkable": True, "color": "#10202c"},
            ],
            boss="Gatekeeper Sleet",
            boss_desc="Frozen to his post. Still fights. Icicle arms.",
            mons=["Frost Mite", "Ice Bore", "Glacier Creeper"],
            weapon="Icicle Javelin",
            weapon_desc="Supercooled. Shatters inside the wound.",
            armor="Thermal Undersuit",
            armor_desc="Heated filaments. Battery lasts four hours.",
            traps=["Ice Crack", "Falling Icicle", "Flash Freeze"],
            root="E", scale="dorian",
            vic="The gate thaws enough to seal. Warmth behind you.",
            defeat="You freeze mid-step. A new ice sculpture.",
        ),
        ds(
            tiles=[
                {"name": "ice core rack", "walkable": False, "color": "#0c1420"},
                {"name": "lab floor tile", "walkable": True, "color": "#18222e"},
                {"name": "thawing specimen", "walkable": True, "color": "#142028"},
                {"name": "sample table", "walkable": True, "color": "#1c2634"},
            ],
            boss="Dr. Permafrost",
            boss_desc="Infected by a thawed specimen. Spreads ice.",
            mons=["Thawed Specimen", "Core Worm", "Frost Spore"],
            weapon="Core Drill Bit",
            weapon_desc="Diamond-tipped. Meant for ice. Works on flesh.",
            armor="Cryo-Resistant Lab Coat",
            armor_desc="Insulated research gear. Rated for extreme cold.",
            traps=["Specimen Burst", "Cryo Leak", "Ice Core Shatter"],
            root="A", scale="aeolian",
            vic="Containment holds. The specimens refreeze. Science can wait.",
            defeat="You become the next specimen. Perfectly preserved.",
        ),
        ds(
            tiles=[
                {"name": "crevasse wall", "walkable": False, "color": "#081018"},
                {"name": "ice bridge", "walkable": True, "color": "#141e2a"},
                {"name": "suspended platform", "walkable": True, "color": "#182430"},
                {"name": "wind-scoured path", "walkable": True, "color": "#101c24"},
            ],
            boss="Bridgemaster Rime",
            boss_desc="Cuts bridge ropes behind you. Collects the falls.",
            mons=["Wind Howler", "Bridge Gnawer", "Crevasse Bat"],
            weapon="Piton Hammer",
            weapon_desc="Drives climbing spikes. Also drives into skulls.",
            armor="Climbing Harness",
            armor_desc="Catches you when you fall. If the rope holds.",
            traps=["Bridge Collapse", "Wind Gust", "Ice Calving"],
            root="F", scale="phrygian",
            vic="The last bridge holds. You cross. Don't look down.",
            defeat="The bridge snaps. The fall is long. The stop is short.",
        ),
        ds(
            tiles=[
                {"name": "thaw bay wall", "walkable": False, "color": "#0e1420"},
                {"name": "heated floor panel", "walkable": True, "color": "#1a242e"},
                {"name": "containment cell", "walkable": True, "color": "#162028"},
                {"name": "artifact pedestal", "walkable": True, "color": "#1e2834"},
            ],
            boss="Artifact Seven",
            boss_desc="Thawed alien device. Walks now. Learns fast.",
            mons=["Thaw Golem", "Artifact Shard", "Containment Breach"],
            weapon="Thermal Cutter",
            weapon_desc="Melts through ice and metal. And artifact shells.",
            armor="Containment Suit",
            armor_desc="Designed to handle alien materials. Hopefully enough.",
            traps=["Artifact Pulse", "Containment Failure", "Thaw Surge"],
            root="Bb", scale="whole_tone",
            vic="Artifact Seven powers down. The thaw chamber goes quiet.",
            defeat="Artifact Seven adds you to its collection. A new component.",
        ),
        ds(
            tiles=[
                {"name": "crystalline ice", "walkable": False, "color": "#081220"},
                {"name": "zero-kelvin floor", "walkable": True, "color": "#101e30"},
                {"name": "frozen machinery", "walkable": True, "color": "#142438"},
                {"name": "reality-warped tile", "walkable": True, "color": "#0c1a2a"},
            ],
            boss="The Cold Itself",
            boss_desc="Entropy given will. Wants all motion stopped.",
            mons=["Entropy Wisp", "Absolute Shade", "Zero-Point Crawler"],
            weapon="Entropy Reversal Rod",
            weapon_desc="Locally reverses entropy. Things come apart.",
            armor="Motion-Preservation Field",
            armor_desc="Keeps your atoms moving. Refuses to stop.",
            traps=["Absolute Zero Zone", "Entropy Drain", "Motion Lock"],
            root="F#", scale="locrian",
            vic="Temperature rises one degree. It's enough. Motion resumes.",
            defeat="Your atoms stop. Perfect stillness. Perfect cold.",
        ),
        ds(
            tiles=[
                {"name": "grotto wall", "walkable": False, "color": "#0a1410"},
                {"name": "warm stone floor", "walkable": True, "color": "#142820"},
                {"name": "hot spring edge", "walkable": True, "color": "#183028"},
                {"name": "alien moss bed", "walkable": True, "color": "#102418"},
            ],
            boss="Bloomkeeper Thaw",
            boss_desc="Tends the alien garden. Plants obey her.",
            mons=["Spore Drifter", "Root Stalker", "Hot Spring Eel"],
            weapon="Thorned Vine Whip",
            weapon_desc="Alien plant. Wraps and constricts. Alive.",
            armor="Moss-Woven Cloak",
            armor_desc="Living alien moss. Repairs itself. Warm.",
            traps=["Root Snare", "Scalding Spring", "Spore Cloud"],
            root="G", scale="lydian",
            vic="The garden sleeps. The hot springs cool to bearable.",
            defeat="The roots pull you under. Fertilizer for the garden.",
        ),
    ],
))

# ─────────────────────────────────────────────
# 9. CASSINI RINGS
# Stations orbiting within gas giant rings.
# ─────────────────────────────────────────────
batch.append(camp(
    name="Cassini Rings",
    desc="Stations suspended within the rings of a massive gas giant. Ice chunks drift past viewports, ring shepherds maintain orbital mechanics, and the view is spectacular until it kills you.",
    bg="#08060e",
    text="#c0b8d8",
    font="Orbitron",
    dfont="Saira",
    lfont="Electrolize",
    levels=[
        lv("Ring Skimmer", "Electrolize",
           "A fast-moving station that surfs the outer ring edge. Ice impacts are constant.",
           "streamlined hull, ice impact dents, particle shields, ring material streaming past viewports",
           "#8878b0", ["#0c0a14", "#201a30", "#3a3050", "#584a74", "#78689a"], B[0]),
        lv("Shepherd Platform", "Electrolize",
           "Gravitational shepherd station keeping the ring gaps clear. Powerful tidal forces.",
           "gravity generators, ring gap views, tidal stress monitors, stabilization gyroscopes",
           "#7080b8", ["#080a14", "#181c30", "#2c3450", "#444e74", "#60709c"], B[1]),
        lv("Ice Quarry", "Electrolize",
           "Mining station harvesting ring ice for water and fuel. Chunks bigger than buildings.",
           "massive ice chunks, harvesting lasers, meltwater channels, ice processing equipment",
           "#90a0c0", ["#080a10", "#181e2c", "#303a50", "#4c5874", "#6c7c9c"], B[2]),
        lv("The Gap Station", "Electrolize",
           "Floating in a ring gap. Nothing above, nothing below. Vertigo in every direction.",
           "transparent floor panels, ring walls on either side, vertigo-inducing views, minimal structure",
           "#a090c0", ["#0a0814", "#201a30", "#3a3050", "#584a74", "#7a689c"], B[3]),
        lv("Resonance Engine", "Electrolize",
           "The station that keeps the rings stable. Someone is trying to destabilize them.",
           "massive harmonic generators, orbital mathematics displays, sabotaged equipment, countdown timer",
           "#7060a0", ["#08060e", "#18142a", "#302a4a", "#4c4270", "#6a5c98"], B[4]),
        lv("Moonlet Outpost", "Electrolize",
           "Tiny station on a ring moonlet. The moonlet is slowly breaking apart.",
           "crumbling moonlet surface, fragile structures, ring material bombardment, escape pods ready",
           "#8890a8", ["#080a0e", "#1a1e28", "#303844", "#4a5464", "#687488"], B[5]),
    ],
    store={"healing_potions": 5, "speed_potions": 3, "bombs": 3},
    designs=[
        ds(
            tiles=[
                {"name": "impact-dented hull", "walkable": False, "color": "#141020"},
                {"name": "skimmer deck", "walkable": True, "color": "#1e182e"},
                {"name": "particle shield panel", "walkable": True, "color": "#221c34"},
                {"name": "viewport alcove", "walkable": True, "color": "#1a1428"},
            ],
            boss="Skimmer Ace Drift",
            boss_desc="Surfs the ring edge. Thinks speed is armor.",
            mons=["Ice Shard Sprite", "Ring Particle Swarm", "Hull Barnacle"],
            weapon="Ice Shard Launcher",
            weapon_desc="Fires harvested ring ice at lethal velocity.",
            armor="Impact Dampening Suit",
            armor_desc="Absorbs collision energy. Tested by ice storms.",
            traps=["Ice Impact", "Particle Storm", "Hull Breach"],
            root="Bb", scale="lydian",
            vic="The skimmer steadies. The ring edge smooths. You slow down.",
            defeat="An ice chunk the size of a house. No time to dodge.",
        ),
        ds(
            tiles=[
                {"name": "gravity generator housing", "walkable": False, "color": "#10101e"},
                {"name": "tidal stress floor", "walkable": True, "color": "#1a1c2e"},
                {"name": "stabilization platform", "walkable": True, "color": "#1e2034"},
                {"name": "ring gap viewport", "walkable": True, "color": "#141628"},
            ],
            boss="Shepherd Tycho",
            boss_desc="Controls local gravity. Plays with weight like toys.",
            mons=["Tidal Phantom", "Gravity Louse", "Gap Runner"],
            weapon="Tidal Disruptor",
            weapon_desc="Creates local gravity spikes. Bones bend.",
            armor="Anti-Tidal Harness",
            armor_desc="Compensates for gravity shifts. Keeps you grounded.",
            traps=["Gravity Spike", "Tidal Shear", "Stabilizer Failure"],
            root="D", scale="dorian",
            vic="Gravity normalizes. Your inner ear finally agrees with your eyes.",
            defeat="Gravity pulls you in two directions at once.",
        ),
        ds(
            tiles=[
                {"name": "ice quarry wall", "walkable": False, "color": "#0e1018"},
                {"name": "meltwater channel", "walkable": True, "color": "#181c28"},
                {"name": "harvester platform", "walkable": True, "color": "#1c2030"},
                {"name": "ice processing floor", "walkable": True, "color": "#141a24"},
            ],
            boss="Quarrymaster Floe",
            boss_desc="Rides ice chunks. Commands the harvesting lasers.",
            mons=["Ice Harvester Drone", "Meltwater Elemental", "Quarry Crawler"],
            weapon="Harvesting Laser Rifle",
            weapon_desc="Meant for ice. Melts other things too.",
            armor="Quarry Worker's Exosuit",
            armor_desc="Powered frame for heavy ice work. Tough.",
            traps=["Ice Chunk Impact", "Laser Misfire", "Meltwater Flood"],
            root="G", scale="aeolian",
            vic="The quarry goes quiet. Ice drifts past peacefully.",
            defeat="Buried under a chunk of ring ice. Cold and permanent.",
        ),
        ds(
            tiles=[
                {"name": "transparent wall", "walkable": False, "color": "#120e1c"},
                {"name": "glass floor panel", "walkable": True, "color": "#1c182a"},
                {"name": "vertigo zone", "walkable": True, "color": "#201a30"},
                {"name": "minimal walkway", "walkable": True, "color": "#161224"},
            ],
            boss="Commander Abyss",
            boss_desc="Embraced the vertigo. Fights on transparent floors.",
            mons=["Vertigo Phantom", "Gap Drifter", "Ring Shadow"],
            weapon="Void Gaze Projector",
            weapon_desc="Forces targets to look down. Most can't fight after.",
            armor="Vertigo Suppression Helm",
            armor_desc="Blocks the view below. Sanity preservation.",
            traps=["Floor Transparency", "Vertigo Pulse", "Gap Wind"],
            root="E", scale="phrygian",
            vic="The floors opaque. The view is hidden. Your stomach settles.",
            defeat="You look down. You keep falling in your mind forever.",
        ),
        ds(
            tiles=[
                {"name": "harmonic generator", "walkable": False, "color": "#100c1a"},
                {"name": "resonance floor", "walkable": True, "color": "#1a1628"},
                {"name": "sabotaged panel", "walkable": True, "color": "#1e1a30"},
                {"name": "countdown display", "walkable": True, "color": "#141024"},
            ],
            boss="Dissonance",
            boss_desc="Wants the rings to collapse. Believes in entropy.",
            mons=["Harmonic Wraith", "Saboteur Drone", "Resonance Ghost"],
            weapon="Harmonic Stabilizer Lance",
            weapon_desc="Restores frequency balance. Also a big stick.",
            armor="Resonance-Tuned Plate",
            armor_desc="Vibrates at the rings' frequency. Attacks phase through.",
            traps=["Harmonic Overload", "Resonance Shatter", "Frequency Lock"],
            root="F#", scale="locrian",
            vic="The engine hums true. The rings hold. Beauty survives.",
            defeat="The rings collapse inward. A billion years of beauty gone.",
        ),
        ds(
            tiles=[
                {"name": "crumbling moonlet", "walkable": False, "color": "#0e1014"},
                {"name": "fragile floor", "walkable": True, "color": "#181c22"},
                {"name": "bombardment shelter", "walkable": True, "color": "#1c2028"},
                {"name": "escape pod bay", "walkable": True, "color": "#14181e"},
            ],
            boss="Last Watch Orla",
            boss_desc="Won't evacuate. The moonlet is her home.",
            mons=["Moonlet Tremor", "Ring Debris", "Crumble Mite"],
            weapon="Emergency Flare Gun",
            weapon_desc="Signal flare. Burns magnesium hot.",
            armor="Evacuation Suit",
            armor_desc="Built for emergency escape. Light and sealed.",
            traps=["Moonlet Quake", "Debris Rain", "Floor Collapse"],
            root="C", scale="blues",
            vic="The moonlet holds together. Orla finally considers leaving.",
            defeat="The moonlet breaks apart. You break with it.",
        ),
    ],
))

# ─────────────────────────────────────────────
# 10. EREBUS STATION
# Ghost ship graveyard. An organism welds them together.
# ─────────────────────────────────────────────
batch.append(camp(
    name="Erebus Station",
    desc="Ships drift into this region of space but nothing drifts out. An organism is welding them together into something vast. The graveyard grows. It has a purpose.",
    bg="#0a0608",
    text="#d0b8c0",
    font="Creepster",
    dfont="Share Tech Mono",
    lfont="Megrim",
    levels=[
        lv("The Accretion", "Megrim",
           "The outermost layer. Recently captured ships still have power. Some have crew.",
           "recently trapped ships, flickering power, panicked distress signals, organic welding spreading",
           "#a07080", ["#100810", "#281820", "#483038", "#684850", "#886470"], B[0]),
        lv("The Digestion", "Megrim",
           "Deeper in. Ships are being broken down. Walls are half-metal, half-organic.",
           "dissolving hull plates, organic growth consuming metal, acid pools, hybrid architecture",
           "#90607a", ["#0e060c", "#241420", "#40283a", "#604054", "#805a70"], B[1]),
        lv("The Nervous System", "Megrim",
           "Signal cables repurposed as nerves. The organism can feel you moving through it.",
           "repurposed wiring, nerve-like cable bundles, twitching conduits, reactive walls",
           "#806088", ["#0c060e", "#20141e", "#382838", "#544054", "#705a72"], B[2]),
        lv("The Immune Response", "Megrim",
           "The organism knows you're hostile. It's sending everything it has.",
           "aggressive organic defenses, antibody-like entities, narrowing passages, rejection reactions",
           "#a05060", ["#100608", "#281018", "#481e2e", "#683448", "#884c62"], B[3]),
        lv("The Core Mind", "Megrim",
           "The brain. A fusion of a hundred ship computers and something else entirely.",
           "fused computer banks, organic neural tissue, flickering screens showing alien thoughts, the heartbeat",
           "#7050a0", ["#0a0610", "#1a1224", "#2e223e", "#46385c", "#60507e"], B[4]),
        lv("The Stillborn Wing", "Megrim",
           "A section that died. The organism's failed experiment. Necrotic but harvestable.",
           "dead organic tissue, non-functional hybrid systems, preserved ship sections, useful salvage",
           "#807070", ["#0c0a0a", "#201c1c", "#383232", "#544a4a", "#706464"], B[5]),
    ],
    store={"healing_potions": 3, "speed_potions": 1, "bombs": 2},
    designs=[
        ds(
            tiles=[
                {"name": "organic weld seam", "walkable": False, "color": "#1a1014"},
                {"name": "captured deck", "walkable": True, "color": "#261820"},
                {"name": "spreading growth", "walkable": True, "color": "#221418"},
                {"name": "distress beacon", "walkable": True, "color": "#2a1c24"},
            ],
            boss="Captain Last Signal",
            boss_desc="Still broadcasting. Half-fused to the hull. Begging.",
            mons=["Fused Crewmember", "Organic Welder", "Hull Barnacle"],
            weapon="Distress Beacon Mace",
            weapon_desc="Still transmitting. Every hit sends a signal.",
            armor="Hull Graft Plate",
            armor_desc="Organic metal hybrid. Grows to fit. Unsettling.",
            traps=["Organic Weld Snare", "Hull Absorption", "Gravity Shift"],
            root="D", scale="phrygian",
            vic="The accretion layer cracks. Fresh vacuum rushes in.",
            defeat="The organism welds you to the hull. You join the broadcast.",
        ),
        ds(
            tiles=[
                {"name": "dissolving bulkhead", "walkable": False, "color": "#180c10"},
                {"name": "acid-etched floor", "walkable": True, "color": "#24141c"},
                {"name": "organic membrane", "walkable": True, "color": "#201018"},
                {"name": "hybrid corridor", "walkable": True, "color": "#281820"},
            ],
            boss="The Gastric Node",
            boss_desc="Digests metal into tissue. Stomach of the beast.",
            mons=["Acid Tendril", "Digestion Mite", "Dissolved Crew"],
            weapon="Caustic Sprayer",
            weapon_desc="The organism's own acid. Turned against it.",
            armor="Acid-Proof Liner",
            armor_desc="Ceramic coating. Dissolves slower than you.",
            traps=["Acid Pool", "Digestion Chamber", "Membrane Trap"],
            root="F", scale="aeolian",
            vic="The digestion stops. The organism retches. Metal holds.",
            defeat="Dissolved slowly. The organism is patient.",
        ),
        ds(
            tiles=[
                {"name": "nerve bundle wall", "walkable": False, "color": "#140c14"},
                {"name": "signal cable floor", "walkable": True, "color": "#1e141e"},
                {"name": "twitching conduit", "walkable": True, "color": "#221822"},
                {"name": "reactive panel", "walkable": True, "color": "#1a1018"},
            ],
            boss="Synapse Major",
            boss_desc="The organism's relay node. Feels everything. Screams.",
            mons=["Neural Spark", "Signal Crawler", "Nerve Cluster"],
            weapon="Signal Disruptor",
            weapon_desc="Scrambles organic signals. Causes seizures.",
            armor="Insulated Nerve Suit",
            armor_desc="Blocks the organism from sensing you. Stealth layer.",
            traps=["Neural Shock", "Signal Overload", "Reactive Wall Slam"],
            root="B", scale="dorian",
            vic="The nerves go silent. The organism loses feeling in this sector.",
            defeat="You become a signal. Transmitted endlessly through the nerves.",
        ),
        ds(
            tiles=[
                {"name": "immune membrane", "walkable": False, "color": "#180a10"},
                {"name": "rejection zone floor", "walkable": True, "color": "#24121a"},
                {"name": "antibody cluster", "walkable": True, "color": "#201018"},
                {"name": "narrowing passage", "walkable": True, "color": "#2a1620"},
            ],
            boss="The White Cell",
            boss_desc="Massive immune response. Envelops and dissolves threats.",
            mons=["Antibody Drone", "Rejection Pulse", "Immune Swarm"],
            weapon="Immunosuppressant Injector",
            weapon_desc="Weakens the organism's defenses. Syringe on a stick.",
            armor="Camouflage Membrane",
            armor_desc="Coated in the organism's own cells. Disguise.",
            traps=["Immune Surge", "Passage Constriction", "Antibody Flood"],
            root="G", scale="blues",
            vic="The immune response fails. The organism accepts your presence.",
            defeat="Enveloped. Dissolved. Recycled. The organism heals.",
        ),
        ds(
            tiles=[
                {"name": "fused computer bank", "walkable": False, "color": "#10081a"},
                {"name": "neural tissue floor", "walkable": True, "color": "#1a1228"},
                {"name": "thought screen", "walkable": True, "color": "#1e1630"},
                {"name": "heartbeat chamber", "walkable": True, "color": "#141022"},
            ],
            boss="Erebus Prime",
            boss_desc="The mind. A hundred fused AIs dreaming together.",
            mons=["Dream Fragment", "Logic Parasite", "Fused AI Ghost"],
            weapon="Logic Bomb",
            weapon_desc="Contradictory code. Crashes organic processors.",
            armor="Firewall Exosuit",
            armor_desc="Mental shielding. Keeps the dreams out.",
            traps=["Dream Snare", "Logic Trap", "Heartbeat Stun"],
            root="F#", scale="whole_tone",
            vic="The mind fragments. A hundred AIs wake up alone. The welding stops.",
            defeat="You join the dream. A hundred and one minds now.",
        ),
        ds(
            tiles=[
                {"name": "necrotic wall", "walkable": False, "color": "#121010"},
                {"name": "dead tissue floor", "walkable": True, "color": "#1c1818"},
                {"name": "preserved ship section", "walkable": True, "color": "#201c1c"},
                {"name": "salvage cache", "walkable": True, "color": "#181414"},
            ],
            boss="Rot Warden Vex",
            boss_desc="Scavenges the dead wing. Protective of her corpse.",
            mons=["Necrotic Mite", "Dead Nerve", "Decay Drone"],
            weapon="Bone Saw",
            weapon_desc="Surgical. Cuts dead tissue and live flesh alike.",
            armor="Necrotic-Resistant Wrap",
            armor_desc="Prevents infection from dead organic material.",
            traps=["Tissue Collapse", "Necrotic Gas", "Dead Drop"],
            root="A", scale="pentatonic_minor",
            vic="The dead wing yields its treasures. Nothing follows you out.",
            defeat="The dead wing isn't quite dead. It was waiting.",
        ),
    ],
))
