use crate::game::*;
use serde::{Deserialize, Serialize};
use std::collections::{HashMap, HashSet};

// ── Phase 1: Universe (title, description, font, colors, tile_defs) ──

#[derive(Serialize, Deserialize, Clone)]
pub struct Phase1Result {
    pub title: String,
    pub description: String,
    pub font: Option<String>,
    pub tile_defs: HashMap<String, TileDefRaw>,
}

#[derive(Serialize, Deserialize, Clone)]
pub struct TileDefRaw {
    pub name: String,
    pub color: String,
    pub walkable: bool,
    #[serde(default)]
    pub char: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
}

// ── Phase 2: Objects (boss, monsters, weapon, armor, traps, budget) ──

#[derive(Serialize, Deserialize, Clone)]
pub struct TileDefSlim {
    pub name: String,
    #[serde(default)]
    pub char: Option<String>,
    /// Base64-encoded tile image (generated by image API)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
}

#[derive(Serialize, Deserialize, Clone)]
pub struct Phase2Result {
    pub tile_defs: Vec<TileDefSlim>,
    pub boss: MonsterRaw,
    pub monster_types: Vec<MonsterTemplateRaw>,
    pub weapon: ItemTemplateRaw,
    pub armor: ItemTemplateRaw,
    pub traps: Option<Vec<TrapRaw>>,
    #[allow(dead_code)]
    pub budget_spent: Option<serde_json::Value>,
    pub mode: Option<ModeRaw>,
    pub victory_message: Option<String>,
    pub defeat_message: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prebuilt_map: Option<crate::mapgen::MapGenResult>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub placed_entities: Option<PlacedEntities>,
}

#[derive(Serialize, Deserialize, Clone, Default)]
pub struct PlacedEntities {
    #[serde(default)]
    pub monsters: Vec<PlacedMonster>,
    #[serde(default)]
    pub items: Vec<PlacedItem>,
    #[serde(default)]
    pub traps: Vec<PlacedTrap>,
}

#[derive(Serialize, Deserialize, Clone)]
pub struct PlacedMonster {
    pub name: String,
    pub x: i32,
    pub y: i32,
}

#[derive(Serialize, Deserialize, Clone)]
pub struct PlacedItem {
    pub name: String,
    pub item_type: String, // "weapon", "armor", "potion", "gold", "key", "speed_potion", "bomb"
    pub x: i32,
    pub y: i32,
    #[serde(default)]
    pub value: Option<i32>,
}

#[derive(Serialize, Deserialize, Clone)]
pub struct PlacedTrap {
    pub name: String,
    pub x: i32,
    pub y: i32,
}

#[derive(Serialize, Deserialize, Clone)]
pub struct ModeRaw {
    pub root: String,
    pub scale: String,
}

#[derive(Serialize, Deserialize, Clone)]
#[allow(dead_code)]
pub struct MonsterRaw {
    pub name: String,
    #[serde(default)]
    pub hp: i32,
    #[serde(default)]
    pub attack: i32,
    pub defense: Option<i32>,
    pub xp_value: Option<i32>,
    pub description: Option<String>,
}

#[derive(Serialize, Deserialize, Clone)]
#[allow(dead_code)]
pub struct MonsterTemplateRaw {
    pub name: String,
    #[serde(default)]
    pub hp: i32,
    #[serde(default)]
    pub attack: i32,
    pub defense: Option<i32>,
    pub xp_value: Option<i32>,
    pub description: Option<String>,
}

#[derive(Serialize, Deserialize, Clone)]
pub struct ItemTemplateRaw {
    pub name: String,
    pub description: Option<String>,
}

#[derive(Serialize, Clone)]
#[allow(dead_code)]
pub struct TrapRaw {
    pub x: Option<i32>,
    pub y: Option<i32>,
    pub damage: Option<i32>,
    pub name: Option<String>,
}

impl<'de> Deserialize<'de> for TrapRaw {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        use serde::de;
        struct TrapVisitor;
        impl<'de> de::Visitor<'de> for TrapVisitor {
            type Value = TrapRaw;
            fn expecting(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
                write!(f, "a trap object or a trap name string")
            }
            fn visit_str<E: de::Error>(self, v: &str) -> Result<TrapRaw, E> {
                Ok(TrapRaw { x: None, y: None, damage: None, name: Some(v.to_string()) })
            }
            fn visit_map<M: de::MapAccess<'de>>(self, map: M) -> Result<TrapRaw, M::Error> {
                #[derive(Deserialize)]
                struct TrapObj {
                    x: Option<i32>, y: Option<i32>, damage: Option<i32>, name: Option<String>,
                }
                let obj = TrapObj::deserialize(de::value::MapAccessDeserializer::new(map))?;
                Ok(TrapRaw { x: obj.x, y: obj.y, damage: obj.damage, name: obj.name })
            }
        }
        deserializer.deserialize_any(TrapVisitor)
    }
}

// ── Overworld result ──

#[derive(Serialize, Deserialize, Clone)]
pub struct OverworldNodeRaw {
    pub name: String,
    pub font: Option<String>,
    pub description: String,
    pub theme: String,
    pub color: Option<String>,
    pub palette: Option<Vec<String>>,
    pub budget: i32,
}

#[derive(Serialize, Deserialize, Clone)]
pub struct OverworldResult {
    pub name: String,
    pub font: Option<String>,
    pub description_font: Option<String>,
    pub label_font: Option<String>,
    pub description: String,
    pub bg_color: Option<String>,
    pub text_color: Option<String>,
    pub levels: Vec<OverworldNodeRaw>,
    pub store: Option<StoreRaw>,
    /// Index of the boss level (completing it wins the campaign). If None, defaults to last main-path level.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub boss_level: Option<usize>,
    /// Explicit DAG edges as [from_node_id, to_node_id] pairs (e.g. ["start","level_0"], ["level_0","level_1"], ["level_2","store"])
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub connections: Option<Vec<[String; 2]>>,
}

#[derive(Serialize, Deserialize, Clone)]
pub struct StoreRaw {
    pub healing_potions: Option<i32>,
    pub speed_potions: Option<i32>,
    pub bombs: Option<i32>,
}

/// Config passed from overworld node to level generation
#[derive(Serialize, Deserialize, Clone)]
pub struct LevelConfig {
    pub title: String,
    pub font: String,
    pub description: String,
    pub theme: String,
    pub palette: Vec<String>,
    pub budget: i32,
    pub floor: i32,
    #[serde(default)]
    pub campaign_tier: i32,
}

// ── Phase status (sent to client) ──

#[derive(Clone, serde::Serialize)]
pub struct PhaseUpdate {
    pub phase: String,
    pub detail: String,
}

// ── Bundled campaign format ──

#[derive(Serialize, Deserialize)]
pub struct BundledCampaign {
    pub id: String,
    pub overworld: OverworldResult,
    pub designs: Vec<Phase2Result>,
    pub quality: CampaignQuality,
    #[serde(default)]
    pub settings: CampaignSettings,
    /// Campaign-level monster templates. If present, used instead of per-level monster_types.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub monster_templates: Option<Vec<MonsterTemplateRaw>>,
}

/// Per-campaign difficulty settings. Controls when mechanics appear within a campaign.
/// Level numbers are 1-indexed (level 1 = first station, level 5 = boss, level 6 = optional).
/// Set to 99 to disable a mechanic entirely for that campaign.
#[derive(Serialize, Deserialize, Clone)]
pub struct CampaignSettings {
    pub locked_doors_from_level: u8,
    pub traps_from_level: u8,
    pub damage_tiles_from_level: u8,
    pub damage_tile_damage: i32,
}

impl Default for CampaignSettings {
    fn default() -> Self {
        Self {
            locked_doors_from_level: 3,
            traps_from_level: 2,
            damage_tiles_from_level: 4,
            damage_tile_damage: 3,
        }
    }
}

#[derive(Serialize, Deserialize, Clone)]
pub struct CampaignQuality {
    pub score: u32,
    pub breakdown: QualityBreakdown,
}

#[derive(Serialize, Deserialize, Clone)]
pub struct QualityBreakdown {
    pub completeness: u32,
    pub tile_variety: u32,
    pub monster_variety: u32,
    pub color_quality: u32,
    pub name_quality: u32,
    pub description_quality: u32,
    pub mode_validity: u32,
    pub budget_distribution: u32,
    pub theme_coherence: u32,
}

/// A pack of campaigns in a single file, ready to ship.
#[derive(Serialize, Deserialize)]
pub struct BundledPack {
    pub theme: Option<String>,
    pub campaigns: Vec<BundledCampaign>,
    #[serde(default)]
    pub strings: PackStrings,
}

/// UI strings that change with the theme/setting.
#[derive(Serialize, Deserialize, Clone)]
pub struct PackStrings {
    pub title: String,
    pub subtitle: String,
    pub intro: Vec<String>,
    pub campaign_cleared: String,
    pub campaign_conquered: String, // "{name} conquered!" — {name} replaced at runtime
    pub prompt_first: String,
    pub prompt_next: String,
    pub prompt_resume: String,
    pub prompt_restart: String,
    pub prompt_after_clear: String,
}

impl Default for PackStrings {
    fn default() -> Self {
        Self {
            title: "SCAPEGRACE".into(),
            subtitle: "A journey through space".into(),
            intro: vec![
                "You are a spacefarer on the edge of known space.".into(),
                "Each star system is a chain of stations.".into(),
                "Clear them all, or die trying.".into(),
            ],
            campaign_cleared: "SYSTEM CLEARED".into(),
            campaign_conquered: "{name} conquered!".into(),
            prompt_first: "Press ENTER for the first star system".into(),
            prompt_next: "Press ENTER for the next star system".into(),
            prompt_resume: "Press ENTER to resume your journey".into(),
            prompt_restart: "Press ENTER to begin the journey again".into(),
            prompt_after_clear: "Press ENTER for next star system".into(),
        }
    }
}

// ── Bundled campaign loading ──

/// Parse campaign data from JSON string (supports BundledPack or bare array).
fn parse_campaign_data(content: &str) -> Option<Vec<BundledCampaign>> {
    // Try BundledPack format first
    if let Ok(pack) = serde_json::from_str::<BundledPack>(content) {
        return Some(pack.campaigns);
    }
    // Try bare array
    if let Ok(campaigns) = serde_json::from_str::<Vec<BundledCampaign>>(content) {
        return Some(campaigns);
    }
    None
}

/// Embedded campaigns — baked into the binary at compile time.
/// Generate with: cargo run --release --bin generate_campaigns -- -o campaigns.json
/// If the file doesn't exist at compile time, this is an empty string and we fall back to external files.
const EMBEDDED_CAMPAIGNS: &str = include_str!("../campaigns.json");

/// Load bundled campaigns. Priority:
/// 1. SCAPEGRACE_CAMPAIGNS env var (external file override)
/// 2. Embedded campaigns (compiled into binary)
/// 3. campaigns.json next to executable
/// 4. campaigns.json in macOS Resources bundle
/// 5. campaigns.json in cwd
pub fn load_bundled_pack() -> Option<BundledPack> {
    let campaigns = load_bundled_campaigns();
    if campaigns.is_empty() { return None; }

    // Try to get the full pack (with strings) from embedded data
    if !EMBEDDED_CAMPAIGNS.is_empty() {
        if let Ok(pack) = serde_json::from_str::<BundledPack>(EMBEDDED_CAMPAIGNS) {
            return Some(BundledPack { campaigns, ..pack });
        }
    }

    Some(BundledPack { theme: None, campaigns, strings: PackStrings::default() })
}

fn load_bundled_campaigns() -> Vec<BundledCampaign> {
    // Env var overrides everything (external file)
    if let Ok(path) = std::env::var("SCAPEGRACE_CAMPAIGNS") {
        if let Ok(content) = std::fs::read_to_string(&path) {
            if let Some(campaigns) = parse_campaign_data(&content) {
                eprintln!("Loaded {} campaigns from {} (env override)", campaigns.len(), path);
                return campaigns;
            }
        }
    }

    // Try embedded campaigns (compiled into binary)
    if !EMBEDDED_CAMPAIGNS.is_empty() {
        eprintln!("[campaigns] embedded data: {} bytes", EMBEDDED_CAMPAIGNS.len());
        match serde_json::from_str::<BundledPack>(EMBEDDED_CAMPAIGNS) {
            Ok(pack) => {
                eprintln!("Loaded {} embedded campaigns (batteries included)", pack.campaigns.len());
                return pack.campaigns;
            }
            Err(e) => eprintln!("[campaigns] pack parse failed: {}", e),
        }
        match serde_json::from_str::<Vec<BundledCampaign>>(EMBEDDED_CAMPAIGNS) {
            Ok(c) => {
                eprintln!("Loaded {} embedded campaigns (array)", c.len());
                return c;
            }
            Err(e) => eprintln!("[campaigns] array parse failed: {}", e),
        }
    } else {
        eprintln!("[campaigns] no embedded data");
    }

    // Fall back to external files
    let mut search_files = Vec::new();

    if let Ok(exe) = std::env::current_exe() {
        if let Some(exe_dir) = exe.parent() {
            search_files.push(exe_dir.join("campaigns.json"));
            // macOS .app bundle
            if let Some(contents) = exe_dir.parent() {
                search_files.push(contents.join("Resources").join("campaigns.json"));
            }
        }
    }
    search_files.push(std::path::PathBuf::from("campaigns.json"));

    // Try external pack files
    for path in &search_files {
        if !path.is_file() { continue; }
        if let Ok(content) = std::fs::read_to_string(path) {
            if let Some(campaigns) = parse_campaign_data(&content) {
                eprintln!("Loaded {} campaigns from {}", campaigns.len(), path.display());
                return campaigns;
            }
            eprintln!("Warning: {} exists but couldn't parse as campaign pack", path.display());
        }
    }

    // Legacy: campaigns/ directory with individual files
    let mut search_dirs = Vec::new();
    if let Ok(exe) = std::env::current_exe() {
        if let Some(exe_dir) = exe.parent() {
            search_dirs.push(exe_dir.join("campaigns"));
            if let Some(contents) = exe_dir.parent() {
                search_dirs.push(contents.join("Resources").join("campaigns"));
            }
        }
    }
    search_dirs.push(std::path::PathBuf::from("campaigns"));

    for dir in &search_dirs {
        if !dir.is_dir() { continue; }
        let mut entries: Vec<_> = std::fs::read_dir(dir)
            .into_iter()
            .flatten()
            .filter_map(|e| e.ok())
            .filter(|e| e.path().extension().map_or(false, |ext| ext == "json"))
            .filter(|e| e.file_name().to_str().map_or(false, |n| n.starts_with("campaign_")))
            .collect();
        entries.sort_by_key(|e| e.file_name());

        let mut campaigns = Vec::new();
        for entry in entries {
            match std::fs::read_to_string(entry.path()) {
                Ok(content) => {
                    match serde_json::from_str::<BundledCampaign>(&content) {
                        Ok(c) => campaigns.push(c),
                        Err(e) => eprintln!("Warning: failed to parse {}: {}", entry.path().display(), e),
                    }
                }
                Err(e) => eprintln!("Warning: failed to read {}: {}", entry.path().display(), e),
            }
        }

        if !campaigns.is_empty() {
            eprintln!("Loaded {} bundled campaigns from {}/", campaigns.len(), dir.display());
            return campaigns;
        }
    }

    Vec::new()
}

// ── LLM caller ──

pub fn llm_base_url() -> String {
    std::env::var("LLM_BASE_URL").unwrap_or_else(|_|
        std::env::var("OPENROUTER_API_KEY").map(|_| "https://openrouter.ai/api/v1".to_string())
            .unwrap_or_else(|_| "http://localhost:11434/v1".to_string())
    )
}

pub fn llm_api_key() -> String {
    std::env::var("LLM_API_KEY")
        .or_else(|_| std::env::var("OPENROUTER_API_KEY"))
        .unwrap_or_default()
}

pub fn llm_model() -> String {
    std::env::var("LLM_MODEL")
        .or_else(|_| std::env::var("ALLMUDDY_MODEL"))
        .unwrap_or_else(|_| "anthropic/claude-sonnet-4".into())
}

pub fn call_llm_streaming<F>(
    client: &reqwest::blocking::Client, api_key: &str, model: &str, prompt: &str,
    on_token: Option<F>,
) -> Result<String, String>
where F: Fn()
{
    use std::io::BufRead;

    let base_url = llm_base_url();
    let url = format!("{}/chat/completions", base_url.trim_end_matches('/'));

    let mut req = client.post(&url)
        .header("Content-Type", "application/json");

    if !api_key.is_empty() {
        req = req.header("Authorization", format!("Bearer {}", api_key));
    }

    let resp = req
        .json(&serde_json::json!({
            "model": model,
            "messages": [{"role": "user", "content": prompt}],
            "temperature": 0.9,
            "max_tokens": 8192,
            "stream": on_token.is_some(),
            "options": { "num_predict": 8192 },
        }))
        .timeout(std::time::Duration::from_secs(180))
        .send()
        .map_err(|e| format!("HTTP error: {}", e))?;

    if on_token.is_none() {
        // Non-streaming path
        let body: serde_json::Value = resp.json()
            .map_err(|e| format!("JSON parse error: {}", e))?;
        let content = body["choices"][0]["message"]["content"]
            .as_str()
            .ok_or("No content in response")?
            .trim()
            .to_string();
        return Ok(clean_llm_content(content));
    }

    // Streaming SSE path
    let on_token = on_token.unwrap();
    let reader = std::io::BufReader::new(resp);
    let mut content = String::new();

    for line in reader.lines() {
        let line = line.map_err(|e| format!("Stream read error: {}", e))?;
        if !line.starts_with("data: ") { continue; }
        let data = &line[6..];
        if data == "[DONE]" { break; }
        if let Ok(chunk) = serde_json::from_str::<serde_json::Value>(data) {
            if let Some(delta) = chunk["choices"][0]["delta"]["content"].as_str() {
                content.push_str(delta);
                on_token();
            }
        }
    }

    Ok(clean_llm_content(content))
}

pub fn clean_llm_content(mut content: String) -> String {
    if content.starts_with("```") {
        if let Some(rest) = content.split_once('\n') {
            content = rest.1.to_string();
        }
    }
    if content.ends_with("```") {
        content = content.rsplit_once("```")
            .map_or(content.clone(), |(before, _)| before.to_string());
    }
    content = content.trim().to_string();
    if !content.starts_with('{') {
        if let Some(start) = content.find('{') {
            if let Some(end) = content.rfind('}') {
                content = content[start..=end].to_string();
            }
        }
    }
    // Strip C-style comments (/* ... */ and // ...) that some models add
    // Remove block comments
    while let Some(start) = content.find("/*") {
        if let Some(end) = content[start..].find("*/") {
            content = format!("{}{}", &content[..start], &content[start + end + 2..]);
        } else {
            break;
        }
    }
    // Remove line comments (but not inside strings — simple heuristic: only if // is not preceded by :)
    let mut cleaned = String::new();
    let mut in_string = false;
    let mut chars = content.chars().peekable();
    while let Some(ch) = chars.next() {
        if ch == '"' { in_string = !in_string; }
        if !in_string && ch == '/' {
            if chars.peek() == Some(&'/') {
                // Skip until end of line
                for c in chars.by_ref() {
                    if c == '\n' { cleaned.push('\n'); break; }
                }
                continue;
            }
        }
        cleaned.push(ch);
    }
    cleaned
}

// ── Tile def expansion ──

/// Build full tile_defs from slim LLM output + palette colors.
/// First entry = wall (not walkable), rest = walkable. Colors assigned from palette.
pub fn expand_tile_defs(slim: &[TileDefSlim], palette: &[String]) -> HashMap<String, TileDefRaw> {
    let chars = ["#", ".", "~", "*", "+", "^"];
    let mut defs = HashMap::new();
    for (i, td) in slim.iter().enumerate() {
        let ch = chars.get(i).unwrap_or(&"?");
        let color = palette.get(i).cloned().unwrap_or_else(|| "#888888".into());
        defs.insert(ch.to_string(), TileDefRaw {
            name: td.name.clone(),
            color,
            walkable: i > 0, // first entry is wall
            char: td.char.clone(),
            image: td.image.clone(),
        });
    }
    // Ensure at least a wall and floor exist
    if defs.is_empty() {
        defs.insert("#".into(), TileDefRaw { name: "wall".into(), color: palette.first().cloned().unwrap_or("#444".into()), walkable: false, char: None, image: None });
        defs.insert(".".into(), TileDefRaw { name: "floor".into(), color: palette.get(1).cloned().unwrap_or("#888".into()), walkable: true, char: None, image: None });
    }
    defs
}

// ── Overworld layout ──

/// Position nodes for the linear-with-branch topology.
/// Main path follows a gentle sine wave, branch drops below the branch point.
/// `main_path_len` is passed from generate_overworld so layout knows exactly which
/// indices are on the main path (0..main_path_len) vs branch (main_path_len..).
fn layout_overworld(ow: &mut crate::game::Overworld, main_path_len: usize) {
    use rand::Rng;
    let mut rng = rand::thread_rng();

    let max_depth = main_path_len.max(2) - 1;

    // Pick a random curve style for the main path
    let curve: u32 = rng.gen_range(0..5);
    let amplitude = rng.gen_range(0.12..=0.22);
    let y_center = rng.gen_range(0.38..=0.52);
    // Branch goes opposite the curve direction at the branch point
    let branch_sign: f32;

    // Curve function: maps t (0..1) to a y-offset from center
    let curve_fn = |t: f32| -> f32 {
        match curve {
            0 => (t * std::f32::consts::PI).sin() * amplitude,             // arc up
            1 => -(t * std::f32::consts::PI).sin() * amplitude,            // arc down
            2 => (t * std::f32::consts::TAU).sin() * amplitude * 0.7,      // S-curve
            3 => -(t * std::f32::consts::TAU).sin() * amplitude * 0.7,     // reverse S-curve
            _ => (t * 0.8 - 0.4) * amplitude * 2.0,                        // diagonal
        }
    };

    // Determine branch direction: opposite of the curve's tendency at the midpoint
    let mid_offset = curve_fn(0.5);
    branch_sign = if mid_offset > 0.0 { 1.0 } else { -1.0 }; // branch away from the curve

    // Main path
    for i in 0..main_path_len {
        let t = i as f32 / max_depth as f32;
        let wave = curve_fn(t);
        let jitter_x = if i == 0 { 0.0 } else { rng.gen_range(-0.02..=0.02) };
        let jitter_y = if i == 0 { 0.0 } else { rng.gen_range(-0.03..=0.03) };
        ow.nodes[i].x = (t + jitter_x).clamp(0.02, 0.98);
        ow.nodes[i].y = (y_center - wave + jitter_y).clamp(0.08, 0.92);
    }

    // Branch nodes: offset perpendicular to the curve, away from main path
    // Find the branch point index and the next main node's x for spacing
    let bp_idx = ow.connections.iter()
        .find(|&&(a, b)| (a < main_path_len && b >= main_path_len) || (b < main_path_len && a >= main_path_len))
        .map(|&(a, b)| if a < main_path_len { a } else { b })
        .unwrap_or(1);
    let bp_x = ow.nodes[bp_idx].x;
    let bp_y = ow.nodes[bp_idx].y;
    // Branch x: midway toward the neighbor with more room (left or right)
    let prev_x = if bp_idx > 0 { ow.nodes[bp_idx - 1].x } else { 0.0 };
    let next_x = if bp_idx + 1 < main_path_len { ow.nodes[bp_idx + 1].x } else { 1.0 };
    let gap_left = bp_x - prev_x;
    let gap_right = next_x - bp_x;
    let base_branch_x = if gap_left > gap_right {
        (prev_x + bp_x) / 2.0  // more room to the left
    } else {
        (bp_x + next_x) / 2.0  // more room to the right
    };

    for i in main_path_len..ow.nodes.len() {
        let depth_in_branch = i - main_path_len;
        let jitter_x = rng.gen_range(-0.02..=0.02);
        let jitter_y = rng.gen_range(-0.02..=0.02);
        ow.nodes[i].x = (base_branch_x + 0.10 * depth_in_branch as f32 + jitter_x).clamp(0.02, 0.98);
        ow.nodes[i].y = (bp_y + branch_sign * (0.25 + 0.15 * depth_in_branch as f32) + jitter_y).clamp(0.08, 0.92);
    }

    // Vertically center the entire graph
    let min_y = ow.nodes.iter().map(|n| n.y).fold(f32::MAX, f32::min);
    let max_y = ow.nodes.iter().map(|n| n.y).fold(f32::MIN, f32::max);
    let mid_y = (min_y + max_y) / 2.0;
    let shift = 0.5 - mid_y;
    for node in &mut ow.nodes {
        node.y = (node.y + shift).clamp(0.08, 0.92);
    }
}

// ── Overworld generation ──

/// Build an Overworld from a pre-generated OverworldResult (no LLM call).
pub fn build_overworld_from_result(result: OverworldResult) -> Result<crate::game::Overworld, String> {
    if result.levels.len() < 5 || result.levels.len() > 7 {
        return Err(format!("Expected 5-7 levels, got {}", result.levels.len()));
    }

    let ow_font = result.font.clone().ok_or("No overworld font")?;

    build_overworld_inner(result, ow_font)
}

pub fn generate_overworld<F, T>(
    mut on_phase: F,
    on_token: T,
) -> Result<crate::game::Overworld, String>
where F: FnMut(PhaseUpdate) + Send, T: Fn() + Send
{
    let api_key = llm_api_key();
    let model = llm_model();
    let client = reqwest::blocking::Client::new();

    let prompt = build_overworld_prompt_themed(None);
    let content = call_llm_streaming(&client, &api_key, &model, &prompt, Some(on_token))?;
    let result: OverworldResult = serde_json::from_str(&content)
        .map_err(|e| format!("Overworld parse error: {}\n\nRaw: {}", e, &content[..content.len().min(500)]))?;

    if result.levels.len() < 5 || result.levels.len() > 7 {
        return Err(format!("Expected 5-7 levels, got {}", result.levels.len()));
    }

    let ow_font = result.font.clone().ok_or("LLM did not provide an overworld font")?;

    let overworld = build_overworld_inner(result, ow_font)?;

    on_phase(PhaseUpdate {
        phase: "overworld designed".into(),
        detail: format!("{} — {} levels", overworld.name, overworld.nodes.len()),
    });

    Ok(overworld)
}

fn build_overworld_inner(result: OverworldResult, ow_font: String) -> Result<crate::game::Overworld, String> {
    use crate::game::{NodeType, OverworldNode};
    use rand::Rng;

    // Split: first N-1 levels = main path, last level = optional branch
    let n = result.levels.len();
    let main_levels = &result.levels[..n - 1];
    let branch_level = &result.levels[n - 1];

    // Build nodes array:
    // [0: Start] [1..main_count: main path levels] [main_count: optional] [main_count+1: store]
    let mut nodes: Vec<OverworldNode> = Vec::new();

    // Start node
    nodes.push(OverworldNode {
        name: "Start".into(),
        font: ow_font.clone(),
        description: String::new(),
        theme: String::new(),
        palette: vec!["#888888".into()],
        budget: 0,
        x: 0.0, y: 0.5,
        completed: true,
        unlocked: true,
        is_final: false,
        node_type: NodeType::Start,
    });

    // Main path levels (last one is the boss)
    let main_count_levels = main_levels.len();
    for (i, lv) in main_levels.iter().enumerate() {
        nodes.push(OverworldNode {
            name: lv.name.clone(),
            font: lv.font.clone().unwrap_or_else(|| ow_font.clone()),
            description: lv.description.clone(),
            theme: lv.theme.clone(),
            palette: lv.palette.clone().or_else(|| lv.color.clone().map(|c| vec![c])).unwrap_or_else(|| vec!["#888888".into()]),
            budget: lv.budget,
            x: 0.0, y: 0.0,
            completed: false,
            unlocked: i == 0, // first main path level unlocked
            is_final: if let Some(bl) = result.boss_level { i == bl } else { i == main_count_levels - 1 },
            node_type: NodeType::Level,
        });
    }

    let main_path_end = nodes.len(); // index after last main path node
    let optional_idx = main_path_end;
    let store_idx = main_path_end + 1;

    // Optional branch level
    nodes.push(OverworldNode {
        name: branch_level.name.clone(),
        font: branch_level.font.clone().unwrap_or_else(|| ow_font.clone()),
        description: branch_level.description.clone(),
        theme: branch_level.theme.clone(),
        palette: branch_level.palette.clone().or_else(|| branch_level.color.clone().map(|c| vec![c])).unwrap_or_else(|| vec!["#888888".into()]),
        budget: branch_level.budget,
        x: 0.0, y: 0.0,
        completed: false,
        unlocked: false,
        is_final: false,
        node_type: NodeType::Level,
    });

    // Store node
    nodes.push(OverworldNode {
        name: "Store".into(),
        font: ow_font.clone(),
        description: "A merchant with rare supplies.".into(),
        theme: String::new(),
        palette: vec!["#ffd700".into(), "#aa8800".into(), "#665500".into()],
        budget: 0,
        x: 0.0, y: 0.0,
        completed: false,
        unlocked: false,
        is_final: false,
        node_type: NodeType::Store,
    });

    // Build connections: main chain + branch
    let mut connections: Vec<(usize, usize)> = Vec::new();

    // Main path: Start(0) → L1(1) → L2(2) → ... → Boss(main_path_end-1)
    for i in 0..main_path_end - 1 {
        connections.push((i, i + 1));
    }

    // Branch: random mid-path node → optional → store
    let mut rng = rand::thread_rng();
    // Branch off a main path level (indices 1..main_path_end-1, not Start or Boss)
    let branch_point = if main_path_end > 3 {
        rng.gen_range(1..main_path_end - 1)
    } else {
        1
    };
    connections.push((branch_point, optional_idx));
    connections.push((optional_idx, store_idx));

    eprintln!("Topology: {} main path nodes, branch at index {} → optional → store", main_path_end, branch_point);

    let desc_font = result.description_font.unwrap_or_else(|| ow_font.clone());
    let label_font = result.label_font.unwrap_or_else(|| ow_font.clone());
    let bg_color = result.bg_color.unwrap_or_else(|| "#0a0a0a".into());
    let text_color = result.text_color.unwrap_or_else(|| "#e0d5c0".into());

    // Build store stock from LLM allocation (with fallback defaults)
    let store_raw = result.store;
    let hp = store_raw.as_ref().and_then(|s| s.healing_potions).unwrap_or(3).max(0).min(10);
    let sp = store_raw.as_ref().and_then(|s| s.speed_potions).unwrap_or(2).max(0).min(5);
    let bo = store_raw.as_ref().and_then(|s| s.bombs).unwrap_or(2).max(0).min(5);
    let mut store_stock = vec![
        crate::game::StoreSlot { name: "Healing Potion".into(), description: "Heals 15-25% HP".into(), item_type: "potion".into(), price: 5, stock: hp, value: 1 },
        crate::game::StoreSlot { name: "Speed Potion".into(), description: "Monsters frozen 5 turns".into(), item_type: "speed_potion".into(), price: 25, stock: sp, value: 1 },
        crate::game::StoreSlot { name: "Bomb".into(), description: "Kills nearby monsters, heavy boss damage".into(), item_type: "bomb".into(), price: 30, stock: bo, value: 1 },
    ];
    // Potion capacity upgrade: 1 per campaign, expensive, caps at 30
    store_stock.push(crate::game::StoreSlot {
        name: "Potion Pouch".into(), description: "Carry 5 more potions (permanent, max 30)".into(),
        item_type: "potion_cap".into(), price: 300, stock: 1, value: 5,
    });
    // Max HP boost: 1 per campaign, always affordable
    store_stock.push(crate::game::StoreSlot {
        name: "Vitality Charm".into(), description: "+15 max HP (permanent)".into(),
        item_type: "max_hp".into(), price: 100, stock: 1, value: 15,
    });
    // Scout Map: reveals the entire next level
    store_stock.push(crate::game::StoreSlot {
        name: "Scout Map".into(), description: "Reveals entire map on next level".into(),
        item_type: "scout_map".into(), price: 40, stock: 2, value: 1,
    });
    // Antidote: immune to damage tiles for entire level
    store_stock.push(crate::game::StoreSlot {
        name: "Antidote".into(), description: "Immune to hazard tiles for 1 level".into(),
        item_type: "antidote".into(), price: 25, stock: 3, value: 1,
    });
    eprintln!("Store stock: {} healing, {} speed, {} bombs + pouch + charm", hp, sp, bo);

    let mut overworld = crate::game::Overworld {
        name: result.name,
        font: ow_font,
        description_font: desc_font,
        label_font,
        description: result.description,
        bg_color,
        text_color,
        connections,
        current_node: 0,
        nodes,
        store_stock,
    };

    layout_overworld(&mut overworld, main_path_end);

    Ok(overworld)
}

/// Build a level from a pre-generated design (no LLM call — just mapgen + assemble)
pub fn build_level_from_design(
    config: &LevelConfig,
    design: &Phase2Result,
) -> Result<(Level, [i32; 2], i32), String> {
    build_level_from_design_with_settings(config, design, &CampaignSettings::default(), None)
}

pub fn build_level_from_design_with_settings(
    config: &LevelConfig,
    design: &Phase2Result,
    settings: &CampaignSettings,
    campaign_monsters: Option<&[MonsterTemplateRaw]>,
) -> Result<(Level, [i32; 2], i32), String> {
    let floor = config.floor;
    let tier_scale = 1.0 + config.campaign_tier as f32 * 0.25;
    let budget = (config.budget as f32 * tier_scale).round() as i32;
    let level_num = floor as u8; // 1-indexed level number within campaign

    let full_defs = expand_tile_defs(&design.tile_defs, &config.palette);
    let p1 = Phase1Result {
        title: config.title.clone(),
        description: config.description.clone(),
        font: Some(config.font.clone()),
        tile_defs: full_defs.clone(),
    };

    let campaign_tier = config.campaign_tier;
    let skip_locked_door = level_num < settings.locked_doors_from_level;
    let map = if let Some(prebuilt) = &design.prebuilt_map {
        prebuilt.clone()
    } else {
        crate::mapgen::generate_map_with_options(&full_defs, skip_locked_door)
    };
    assemble_level_with_settings(floor, budget, &p1, design, &map, settings, campaign_monsters, campaign_tier)
}

// ── Three-phase generation (legacy, still used if no pre-generated design) ──

pub fn generate_level<F, T>(
    config: &LevelConfig, player: &Player,
    mut on_phase: F,
    on_token: T,
) -> Result<(Level, [i32; 2], i32), String>
where F: FnMut(PhaseUpdate) + Send, T: Fn() + Send
{
    let api_key = llm_api_key();
    let model = llm_model();
    let client = reqwest::blocking::Client::new();
    let theme = &config.theme;
    let floor = config.floor;
    let tier_scale = 1.0 + config.campaign_tier as f32 * 0.25;
    let budget = (config.budget as f32 * tier_scale).round() as i32;

    // ── Phase 1: Objects + tile_defs (single LLM call) ──
    on_phase(PhaseUpdate { phase: "designing level".into(), detail: String::new() });

    let p2_prompt = build_phase2_prompt(floor, player, budget, theme, &config.title, &config.description, &config.palette);
    let p2_content = call_llm_streaming(&client, &api_key, &model, &p2_prompt, Some(&on_token))?;
    let p2: Phase2Result = serde_json::from_str(&p2_content)
        .map_err(|e| format!("Phase 1 parse error: {}", e))?;

    // Build full tile_defs from slim LLM output + palette
    let full_defs = expand_tile_defs(&p2.tile_defs, &config.palette);
    let p1 = Phase1Result {
        title: config.title.clone(),
        description: config.description.clone(),
        font: Some(config.font.clone()),
        tile_defs: full_defs.clone(),
    };

    let trap_count = p2.traps.as_ref().map_or(0, |t| t.len());
    let mon_count = p2.monster_types.len();
    eprintln!("Phase 1: '{}' — boss '{}', {} monster types, {} traps, weapon '{}', armor '{}'",
        p1.title, p2.boss.name, mon_count, trap_count, p2.weapon.name, p2.armor.name);
    on_phase(PhaseUpdate {
        phase: "level designed".into(),
        detail: format!("boss: {} · {} monster types · {} traps · {} · {}",
            p2.boss.name, mon_count, trap_count, p2.weapon.name, p2.armor.name),
    });

    // ── Build world (procedural generation) ──
    on_phase(PhaseUpdate { phase: "building world".into(), detail: String::new() });

    let map = crate::mapgen::generate_map(&full_defs);
    let (level, start, remaining) = assemble_level(floor, budget, &p1, &p2, &map)?;

    on_phase(PhaseUpdate { phase: "world built".into(), detail: String::new() });
    Ok((level, start, remaining))
}

// ── Prompt builders ──

fn build_phase2_prompt(floor: i32, player: &Player, budget: i32, theme: &str, title: &str, description: &str, _palette: &[String]) -> String {
    let mut p = String::new();
    p.push_str(&format!("Generate the TILE DEFINITIONS and OBJECTS for level {} of a roguelike game.\n\n", floor));
    p.push_str(&format!("Theme: {} — \"{}\"\n", theme, title));
    p.push_str(&format!("{}\n\n", description));

    p.push_str("You are ADVERSARIAL — your goal is to kill the player.\n");
    p.push_str(&format!("Player: level {}, {}/{} HP, ATK {}, DEF {}, weapon '{}' (+{}), armor '{}' (+{}), {} potions.\n\n",
        player.level, player.hp, player.max_hp,
        player.attack + player.weapon_damage, player.defense + player.armor_defense,
        player.weapon, player.weapon_damage, player.armor, player.armor_defense, player.potions));

    p.push_str(&format!("BUDGET: {} scapebux.\n", budget));
    p.push_str("  Spend: Boss 25, Monster 10 each, Trap 6 each.\n");
    p.push_str("  Earn back: Weapon +15, Armor +10, Potion +5, Gold +3.\n");
    p.push_str("  Unspent carries over to the next level.\n\n");

    p.push_str("Return a JSON object with:\n");
    p.push_str("- tile_defs: array of {name, char (display char or empty)}. First entry is the wall tile, rest are walkable. Include 3-5 tiles total (wall, floor, and 1-3 thematic). Colors are assigned by the engine from the palette.\n");
    p.push_str("- boss: {name, description (max 10 words)}. Stats are computed by the engine.\n");
    p.push_str("- monster_types: array of 2-3 templates {name, description (max 10 words)}.\n");
    p.push_str("- weapon: {name, description (max 10 words)}\n");
    p.push_str("- armor: {name, description (max 10 words)}\n");
    p.push_str("- traps: array of {name}. The engine decides count and damage from budget.\n");
    p.push_str("- mode: {root, scale} — a musical mode for the level's ambient sound. root is a note name (e.g. \"C\", \"F#\", \"Bb\"), scale is one of: \"ionian\", \"dorian\", \"phrygian\", \"lydian\", \"mixolydian\", \"aeolian\", \"locrian\", \"pentatonic_major\", \"pentatonic_minor\", \"blues\", \"whole_tone\", \"chromatic\". Choose a mode that fits the level's mood.\n");
    p.push_str("- victory_message: one short atmospheric sentence shown when the player beats this level\n- defeat_message: one short atmospheric sentence shown when the player dies in this level\n\n");
    p.push_str("Respond in ENGLISH ONLY. Return ONLY valid JSON, no commentary.");
    p
}

pub fn build_single_level_design_prompt(
    campaign_name: &str, campaign_desc: &str, config: &LevelConfig,
) -> String {
    build_single_level_design_prompt_themed(campaign_name, campaign_desc, config, None)
}

pub fn build_single_level_design_prompt_themed(
    campaign_name: &str, campaign_desc: &str, config: &LevelConfig, theme: Option<&str>,
) -> String {
    let mut p = String::new();
    p.push_str(&format!("Generate TILE DEFINITIONS and OBJECTS for one level of a roguelike campaign.\n\n"));
    p.push_str(&format!("Campaign: \"{}\"\n{}\n\n", campaign_name, campaign_desc));
    p.push_str(&format!("Level: \"{}\" (theme: {}, budget: {})\n", config.title, config.theme, config.budget));
    p.push_str(&format!("{}\nPalette: {}\n\n", config.description, config.palette.join(", ")));
    if let Some(theme) = theme {
        p.push_str(&format!("MANDATORY: All names MUST reference \"{}\".\n", theme));
        p.push_str("Boss, monsters, weapon, armor, traps — name them after specific characters, items, or concepts from the source material. A fan should immediately recognize the references.\n");
        p.push_str("DO NOT use generic fantasy/sci-fi names like \"Shadow Beast\" or \"Dark Blade\".\n\n");
    }
    p.push_str("You are ADVERSARIAL — your goal is to kill the player.\n\n");
    p.push_str("Return a JSON object with:\n");
    p.push_str("- tile_defs: array of {name, char (display char or empty)}. First entry is the wall tile, rest are walkable. Include 3-5 tiles total (wall, floor, and 1-3 thematic). Colors are assigned by the engine from the palette.\n");
    p.push_str("- boss: {name, description (max 10 words)}. Stats are computed by the engine.\n");
    p.push_str("- monster_types: array of 2-3 templates {name, description (max 10 words)}.\n");
    p.push_str("- weapon: {name, description (max 10 words)}\n");
    p.push_str("- armor: {name, description (max 10 words)}\n");
    p.push_str("- traps: array of {name}. The engine decides count and damage from budget.\n");
    p.push_str("- mode: {root, scale} — musical mode. root = note name, scale = one of: ionian, dorian, phrygian, lydian, mixolydian, aeolian, locrian\n");
    p.push_str("- victory_message: one short atmospheric sentence shown when the player beats this level\n- defeat_message: one short atmospheric sentence shown when the player dies in this level\n\n");
    p.push_str("Respond in ENGLISH ONLY. Return ONLY valid JSON, no commentary.");
    p
}

pub fn call_llm_for_design<F: Fn()>(
    client: &reqwest::blocking::Client, api_key: &str, model: &str, prompt: &str,
    on_token: Option<F>,
) -> Result<Phase2Result, String> {
    let content = call_llm_streaming(client, api_key, model, prompt, on_token)?;
    serde_json::from_str(&content)
        .map_err(|e| format!("Design parse error: {}\n\nRaw: {}", e, &content[..content.len().min(500)]))
}

pub fn build_overworld_prompt_themed(theme: Option<&str>) -> String {
    let mut p = String::new();
    p.push_str("Design a CAMPAIGN for a roguelike game.\n\n");
    if let Some(theme) = theme {
        p.push_str(&format!("CRITICAL — MANDATORY THEME: \"{}\"\n\n", theme));
        p.push_str("EVERY element of this campaign MUST be directly inspired by this source material.\n");
        p.push_str("- Campaign name: reference or pun from the source\n");
        p.push_str("- Level names: named after specific locations, events, or concepts from the source\n");
        p.push_str("- Level themes: describe scenarios using characters, places, and lore from the source\n");
        p.push_str("- Descriptions: written in the tone and style of the source material\n\n");
        p.push_str("DO NOT use generic sci-fi/fantasy names. USE specific names, places, and references that a fan would recognize.\n");
        p.push_str(&format!("If the theme is a book/movie/game, name levels after actual locations and reference actual characters. For example, if the theme were \"Lord of the Rings\" you'd have levels like \"Mines of Moria\", \"Fangorn Forest\", boss \"Balrog of Morgoth\", weapon \"Sting\", etc.\n\n"));
    } else {
        p.push_str("Be wildly creative with the setting. Invent something original and unexpected — the weirder the better.\n");
        p.push_str("Think more like: a sentient library that reshelves itself, a civilization built inside frozen music, a war between rival paint colors, a detective agency run by ghosts, an opera house where the architecture argues with the performers, a postal service that delivers to parallel dimensions, a courtroom where gravity is on trial.\n\n");
    }
    p.push_str("Return a JSON object with:\n");
    p.push_str("- name: campaign name (2-4 words, evocative)\n");
    p.push_str("- font: a Google Fonts font family for the campaign title\n");
    p.push_str("- description_font: a Google Fonts font family for the description text (readable, elegant)\n");
    p.push_str("- label_font: a Google Fonts font family for level name labels on the map\n");
    p.push_str("- description: one atmospheric sentence about the campaign\n");
    p.push_str("- bg_color: hex background color — must be DARK. Pick from varied palettes: near-black '#0a0a0a', dark teal '#0d1f2d', deep green '#0a1a0a', charcoal blue '#0d1117', dark brown '#1a0f0a', deep red '#1a0505', dark slate '#1a1a2e'. Do NOT always pick purple.\n");
    p.push_str("- text_color: hex color for title and label text — must have strong contrast against bg_color\n");
    p.push_str("- levels: array of exactly 6 level objects, each with:\n");
    p.push_str("  - name: level title (2-4 words)\n");
    p.push_str("  - font: a Google Fonts font family for the level\n");
    p.push_str("  - description: one atmospheric sentence\n");
    p.push_str("  - theme: detailed theme string (e.g. 'collapsing origami palace', 'volcanic glassblowing workshop')\n");
    p.push_str("  - color: a hex color representing the level's mood. Each level should have a distinct color.\n");
    p.push_str("  - palette: array of 4-6 hex colors for the level's tile types. Be creative and bold. IMPORTANT: Do NOT use these reserved colors: green (#66bb6a), red (#e64545), gold (#ffd700), cyan (#4dd0e1), orange (#ffa726).\n");
    p.push_str("  - budget: scapebux budget (integer)\n\n");
    p.push_str("RULES:\n");
    p.push_str("- Exactly 6 levels. The first 5 form a main path (easy→hard). The 6th is an optional side quest.\n");
    p.push_str("- Level 5 (the last main path level) is the FINAL BOSS — give it the highest budget (~250-300).\n");
    p.push_str("- Total budget across ALL 6 levels: approximately 1200 scapebux.\n");
    p.push_str("- Early levels ~120-160, middle ~180-220, boss ~250-300, optional ~150.\n");
    p.push_str("- Each level theme should be distinct but all should feel part of the same campaign.\n\n");
    p.push_str("Also include a \"store\" object with the shop inventory for the whole campaign.\n");
    p.push_str("You have a STORE BUDGET of 150 scapebux to spend on stock:\n");
    p.push_str("  - healing_potions: cost 10 each\n");
    p.push_str("  - speed_potions: cost 25 each\n");
    p.push_str("  - bombs: cost 30 each\n");
    p.push_str("Decide how many of each to stock. Once bought, they're gone forever. Be adversarial — don't be generous.\n");
    p.push_str("Example: {\"healing_potions\": 5, \"speed_potions\": 2, \"bombs\": 2}\n\n");
    p.push_str("Respond in ENGLISH ONLY. Return ONLY valid JSON, no commentary.");
    p
}

// ── Assembly ──

fn assemble_level(
    floor: i32, budget: i32,
    p1: &Phase1Result, p2: &Phase2Result, map: &crate::mapgen::MapGenResult,
) -> Result<(Level, [i32; 2], i32), String> {
    assemble_level_with_settings(floor, budget, p1, p2, map, &CampaignSettings::default(), None, 0)
}

fn assemble_level_with_settings(
    floor: i32, budget: i32,
    p1: &Phase1Result, p2: &Phase2Result, map: &crate::mapgen::MapGenResult,
    settings: &CampaignSettings,
    campaign_monsters: Option<&[MonsterTemplateRaw]>,
    campaign_tier: i32,
) -> Result<(Level, [i32; 2], i32), String> {
    let width = 60_i32;
    let height = 36_i32;

    // Build tile defs lookup
    let level_num = floor as u8;
    let damage_tiles_enabled = level_num >= settings.damage_tiles_from_level;
    let traps_enabled = level_num >= settings.traps_from_level;

    let mut tile_defs: HashMap<String, TileDef> = HashMap::new();
    let mut thematic_count = 0u32;
    let total_tile_types = p1.tile_defs.len();
    for (_ch, raw) in &p1.tile_defs {
        thematic_count += 1;
        // Make the last walkable thematic tile a damage tile if enabled
        let is_last_thematic = thematic_count == total_tile_types as u32 && raw.walkable && damage_tiles_enabled;
        tile_defs.insert(raw.name.clone(), TileDef {
            name: raw.name.clone(),
            color: raw.color.clone(),
            walkable: raw.walkable,
            char_display: raw.char.clone().unwrap_or_default(),
            damage: if is_last_thematic { settings.damage_tile_damage } else { 0 },
            image: raw.image.clone(),
        });
    }
    if !tile_defs.contains_key("wall") {
        tile_defs.insert("wall".into(), TileDef {
            name: "wall".into(), color: "#444".into(), walkable: false, char_display: String::new(), damage: 0, image: None,
        });
    }

    // Add locked door tile def if the map has one
    if map.key_position.is_some() {
        tile_defs.insert("locked_door".into(), TileDef {
            name: "locked_door".into(), color: "#aa6622".into(), walkable: false,
            char_display: "🔒".into(), damage: 0, image: None,
        });
    }

    // Use the procedurally generated grid directly
    let tiles = map.tiles.clone();
    let player_start = map.player_start;

    // Two flood fills: player side (blocked by locked door) and full map (ignoring lock)
    let player_side = flood_fill(&tiles, &tile_defs, player_start[0], player_start[1], width, height);
    let player_side_vec: Vec<(i32, i32)> = player_side.iter().copied().collect();

    // Full reachable: temporarily treat locked_door as walkable
    let mut full_defs = tile_defs.clone();
    if map.key_position.is_some() {
        full_defs.insert("locked_door".into(), TileDef {
            name: "locked_door".into(), color: "#aa6622".into(), walkable: true,
            char_display: "🔒".into(), damage: 0, image: None,
        });
    }
    let full_reachable = flood_fill(&tiles, &full_defs, player_start[0], player_start[1], width, height);

    // Locked side = full reachable minus player side
    let locked_side_vec: Vec<(i32, i32)> = full_reachable.iter()
        .filter(|t| !player_side.contains(t))
        .copied()
        .collect();
    let has_locked_side = !locked_side_vec.is_empty();

    // Combined reachable for general use
    let reachable_vec: Vec<(i32, i32)> = full_reachable.iter().copied().collect();

    // Boss position
    let bx = map.boss_position[0];
    let by = map.boss_position[1];

    use rand::Rng;
    let mut rng = rand::thread_rng();
    let remaining_budget;

    // Scaling factors (tuned so a level-1 player can beat campaign 1)
    let hp_per_point = 1.0 + floor as f32 * 0.2;
    let atk_scale = 2 + floor / 2;
    let def_scale = (floor / 2).max(0);

    let monsters;
    let items;
    let traps;

    if let Some(placed) = &p2.placed_entities {
        // ── Designer-placed entities: use their positions, engine computes stats ──
        let boss_cost = (budget * 20 / 100).max(10);
        let boss_hp = (boss_cost as f32 * hp_per_point).round() as i32;
        let boss_atk = atk_scale + boss_cost / 15;
        let boss_def = def_scale;
        let boss_xp = boss_cost + floor * 5;

        let mut mons = vec![Monster {
            id: format!("boss_{}", floor),
            name: p2.boss.name.clone(),
            x: bx, y: by,
            hp: boss_hp, max_hp: boss_hp,
            attack: boss_atk, defense: boss_def,
            xp_value: boss_xp,
            description: p2.boss.description.clone().unwrap_or_default(),
            is_boss: true,
            boss_enraged_turns: 0, boss_has_seen_player: false,
            boss_attacked_this_turn: false,
            boss_body: vec![(bx, by), (bx + 1, by), (bx, by + 1), (bx + 1, by + 1)],
            boss_flee_budget: 0, boss_flee_cooldown: 0,
        }];

        let mon_count = placed.monsters.len().max(1) as i32;
        let mon_budget_each = (budget - boss_cost) / (mon_count + 2); // leave room for gold
        for (i, pm) in placed.monsters.iter().enumerate() {
            let mon_cost = mon_budget_each.max(5);
            let mon_hp = (mon_cost as f32 * (0.8 + floor as f32 * 0.15)).round() as i32;
            mons.push(Monster {
                id: format!("m_{}_{}", floor, i),
                name: pm.name.clone(),
                x: pm.x, y: pm.y,
                hp: mon_hp, max_hp: mon_hp,
                attack: atk_scale, defense: def_scale,
                xp_value: mon_cost + floor * 2,
                description: String::new(),
                is_boss: false,
                boss_enraged_turns: 0, boss_has_seen_player: false,
                boss_attacked_this_turn: false, boss_body: vec![],
                boss_flee_budget: 0, boss_flee_cooldown: 0,
            });
        }
        monsters = mons;

        let mut itms: Vec<Item> = Vec::new();
        for (i, pi) in placed.items.iter().enumerate() {
            let value = pi.value.unwrap_or_else(|| match pi.item_type.as_str() {
                "weapon" => floor + 3,
                "armor" => floor + 1,
                "gold" => rng.gen_range(5..=15) + floor * 2,
                _ => 0,
            });
            itms.push(Item {
                id: format!("pi_{}_{}", floor, i),
                name: pi.name.clone(),
                x: pi.x, y: pi.y,
                item_type: pi.item_type.clone(),
                value,
                description: String::new(),
            });
        }
        items = itms;

        let mut trp: Vec<Trap> = Vec::new();
        if traps_enabled {
            for pt in &placed.traps {
                trp.push(Trap {
                    x: pt.x, y: pt.y,
                    damage: 3 + floor,
                    name: pt.name.clone(),
                    triggered: false,
                });
            }
        }
        traps = trp;
        remaining_budget = 0;

        eprintln!("Placed entities: boss + {} monsters + {} items + {} traps (designer-placed)",
            placed.monsters.len(), placed.items.len(), placed.traps.len());
    } else {
        // ── Auto-placement: engine places everything from budget ──
        let mut rem = budget;

        let boss_cost = rng.gen_range(budget * 15 / 100..=budget * 25 / 100).max(10);
        rem -= boss_cost;
        let boss_hp = (boss_cost as f32 * hp_per_point).round() as i32;
        let boss_atk = atk_scale + boss_cost / 15;
        let boss_def = def_scale;
        let boss_xp = boss_cost + floor * 5;

        eprintln!("Boss '{}' — cost {} → {} HP, {} ATK, {} DEF",
            p2.boss.name, boss_cost, boss_hp, boss_atk, boss_def);

        let mut mons = vec![Monster {
            id: format!("boss_{}", floor),
            name: p2.boss.name.clone(),
            x: bx, y: by,
            hp: boss_hp, max_hp: boss_hp,
            attack: boss_atk, defense: boss_def,
            xp_value: boss_xp,
            description: p2.boss.description.clone().unwrap_or_default(),
            is_boss: true,
            boss_enraged_turns: 0, boss_has_seen_player: false,
            boss_attacked_this_turn: false,
            boss_body: vec![(bx, by), (bx + 1, by), (bx, by + 1), (bx + 1, by + 1)],
            boss_flee_budget: 0, boss_flee_cooldown: 0,
        }];

        let pick_side = |rng: &mut rand::rngs::ThreadRng| -> &Vec<(i32, i32)> {
            if has_locked_side && rng.gen::<f32>() < 0.4 { &locked_side_vec } else { &player_side_vec }
        };

        let monster_types = campaign_monsters.unwrap_or(&p2.monster_types);
        if !monster_types.is_empty() {
            let mut i = 0;
            while rem >= 5 {
                let mon_cost = rng.gen_range(5..=8.min(rem));
                rem -= mon_cost;
                let mon_hp = (mon_cost as f32 * (0.8 + floor as f32 * 0.15)).round() as i32;
                let tmpl = &monster_types[i % monster_types.len()];
                let tiles = pick_side(&mut rng);
                if let Some(&(mx, my)) = pick_random_reachable(tiles, player_start, 3, &mons, &mut rng) {
                    mons.push(Monster {
                        id: format!("m_{}_{}", floor, i),
                        name: tmpl.name.clone(),
                        x: mx, y: my,
                        hp: mon_hp, max_hp: mon_hp,
                        attack: atk_scale, defense: def_scale,
                        xp_value: mon_cost + floor * 2,
                        description: tmpl.description.clone().unwrap_or_default(),
                        is_boss: false,
                        boss_enraged_turns: 0, boss_has_seen_player: false,
                        boss_attacked_this_turn: false, boss_body: vec![],
                        boss_flee_budget: 0, boss_flee_cooldown: 0,
                    });
                }
                i += 1;
            }
        }
        monsters = mons;

        let mut trp: Vec<Trap> = Vec::new();
        if traps_enabled {
            if let Some(trap_defs) = &p2.traps {
                for td in trap_defs.iter() {
                    let trap_cost = rng.gen_range(3..=8.min(rem.max(3)));
                    if rem < 3 { break; }
                    rem -= trap_cost;
                    let tiles = pick_side(&mut rng);
                    if let Some(&(tx, ty)) = pick_random_reachable(tiles, player_start, 4, &monsters, &mut rng) {
                        trp.push(Trap {
                            x: tx, y: ty,
                            damage: trap_cost + floor,
                            name: td.name.clone().unwrap_or_else(|| "Trap".into()),
                            triggered: false,
                        });
                    }
                }
            }
        }
        traps = trp;

        let mut itms: Vec<Item> = Vec::new();
        {
            let mut gold_i = 0;
            while rem >= 2 {
                let gold_cost = rng.gen_range(2..=5.min(rem));
                rem -= gold_cost;
                let amount = gold_cost * 2 + rng.gen_range(0..=floor);
                let tiles = pick_side(&mut rng);
                if let Some(&(gx, gy)) = pick_random_reachable(tiles, player_start, 2, &monsters, &mut rng) {
                    itms.push(Item {
                        id: format!("gold_{}_{}", floor, gold_i), name: format!("{} Gold", amount),
                        x: gx, y: gy, item_type: "gold".into(), value: amount, description: String::new(),
                    });
                }
                gold_i += 1;
                if gold_i >= 6 { break; }
            }
            let w_tiles = pick_side(&mut rng);
            if let Some(&(wx, wy)) = pick_random_reachable(w_tiles, player_start, 1, &monsters, &mut rng) {
                itms.push(Item {
                    id: format!("w_{}", floor), name: p2.weapon.name.clone(),
                    x: wx, y: wy, item_type: "weapon".into(), value: floor + 3 + campaign_tier * 2,
                    description: p2.weapon.description.clone().unwrap_or_default(),
                });
            }
            let a_tiles = pick_side(&mut rng);
            if let Some(&(ax, ay)) = pick_random_reachable(a_tiles, player_start, 1, &monsters, &mut rng) {
                itms.push(Item {
                    id: format!("a_{}", floor), name: p2.armor.name.clone(),
                    x: ax, y: ay, item_type: "armor".into(), value: floor + 1 + campaign_tier * 2,
                    description: p2.armor.description.clone().unwrap_or_default(),
                });
            }
            let mon_count = monsters.iter().filter(|m| !m.is_boss).count();
            let potion_count = (mon_count / 6).max(1);
            for i in 0..potion_count {
                if let Some(&(px, py)) = pick_random_reachable(&reachable_vec, player_start, 2, &monsters, &mut rng) {
                    itms.push(Item {
                        id: format!("pot_{}_{}", floor, i), name: "Health Potion".into(),
                        x: px, y: py, item_type: "potion".into(), value: 0, description: String::new(),
                    });
                }
            }
            if let Some(key_pos) = map.key_position {
                itms.push(Item {
                    id: format!("key_{}", floor), name: "Key".into(),
                    x: key_pos[0], y: key_pos[1], item_type: "key".into(), value: 0,
                    description: "Unlocks a locked door.".into(),
                });
            }
        }
        items = itms;
        remaining_budget = rem;

        let monster_count = monsters.iter().filter(|m| !m.is_boss).count();
        let trap_count = traps.len();
        let gold_count = items.iter().filter(|i| i.item_type == "gold").count();
        eprintln!("Budget: {} total, {} remaining — boss + {} monsters + {} traps + {} gold",
            budget, remaining_budget, monster_count, trap_count, gold_count);
    }

    let scale = p2.mode.as_ref()
        .map(|m| build_scale(&m.root, &m.scale))
        .unwrap_or_else(|| build_scale("C", "aeolian"));

    if let Some(m) = &p2.mode {
        eprintln!("Mode: {} {}", m.root, m.scale);
    }

    let level = Level {
        width, height, tiles, tile_defs, monsters, items, traps,
        title: p1.title.clone(),
        description: p1.description.clone(),
        font: p1.font.clone().expect("font was set from overworld config"),
        scale,
        victory_message: p2.victory_message.clone().unwrap_or_default(),
        defeat_message: p2.defeat_message.clone().unwrap_or_default(),
        revealed: HashSet::new(),
        visible: HashSet::new(),
        char_marks: Default::default(),
    };

    Ok((level, player_start, remaining_budget))
}

// ── Helpers ──

fn flood_fill(
    tiles: &[Vec<String>], tile_defs: &HashMap<String, TileDef>,
    start_x: i32, start_y: i32, width: i32, height: i32,
) -> HashSet<(i32, i32)> {
    let mut visited = HashSet::new();
    let mut stack = vec![(start_x, start_y)];
    while let Some((x, y)) = stack.pop() {
        if x < 0 || y < 0 || x >= width || y >= height { continue; }
        if !visited.insert((x, y)) { continue; }
        let tile = &tiles[y as usize][x as usize];
        if !tile_defs.get(tile).map_or(false, |t| t.walkable) {
            visited.remove(&(x, y));
            continue;
        }
        stack.push((x + 1, y));
        stack.push((x - 1, y));
        stack.push((x, y + 1));
        stack.push((x, y - 1));
    }
    visited
}

fn pick_random_reachable<'a>(
    reachable: &'a [(i32, i32)], player_start: [i32; 2], min_dist: i32,
    monsters: &[Monster], rng: &mut impl rand::Rng,
) -> Option<&'a (i32, i32)> {
    let candidates: Vec<&(i32, i32)> = reachable.iter()
        .filter(|(x, y)| {
            let dist = (*x - player_start[0]).abs() + (*y - player_start[1]).abs();
            dist >= min_dist && !monsters.iter().any(|m| m.x == *x && m.y == *y)
        })
        .collect();
    if candidates.is_empty() {
        reachable.iter()
            .filter(|(x, y)| !monsters.iter().any(|m| m.x == *x && m.y == *y))
            .nth(rng.gen_range(0..reachable.len().max(1)))
    } else {
        Some(candidates[rng.gen_range(0..candidates.len())])
    }
}

/// Build a scale of frequencies from a root note name and scale type.
/// Returns frequencies spanning 2 octaves in a comfortable range (C4-C6 area).
pub fn build_scale(root: &str, scale_name: &str) -> Vec<f32> {
    // Parse root note to semitone offset from C
    let root_semitone = match root.to_uppercase().trim_end_matches(|c: char| c.is_ascii_digit()).to_string().as_str() {
        "C" => 0, "C#" | "DB" => 1, "D" => 2, "D#" | "EB" => 3,
        "E" => 4, "F" => 5, "F#" | "GB" => 6, "G" => 7,
        "G#" | "AB" => 8, "A" => 9, "A#" | "BB" => 10, "B" => 11,
        _ => 0, // default to C
    };

    // Scale intervals (semitones from root)
    let intervals: Vec<i32> = match scale_name.to_lowercase().as_str() {
        "ionian" | "major" => vec![0, 2, 4, 5, 7, 9, 11],
        "dorian" => vec![0, 2, 3, 5, 7, 9, 10],
        "phrygian" => vec![0, 1, 3, 5, 7, 8, 10],
        "lydian" => vec![0, 2, 4, 6, 7, 9, 11],
        "mixolydian" => vec![0, 2, 4, 5, 7, 9, 10],
        "aeolian" | "minor" => vec![0, 2, 3, 5, 7, 8, 10],
        "locrian" => vec![0, 1, 3, 5, 6, 8, 10],
        "pentatonic_major" => vec![0, 2, 4, 7, 9],
        "pentatonic_minor" => vec![0, 3, 5, 7, 10],
        "blues" => vec![0, 3, 5, 6, 7, 10],
        "whole_tone" => vec![0, 2, 4, 6, 8, 10],
        "chromatic" => vec![0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
        _ => vec![0, 2, 3, 5, 7, 8, 10], // default aeolian (natural minor)
    };

    // Generate frequencies across 2 octaves starting from octave 4
    // C4 = MIDI 60 = 261.63 Hz, A4 = MIDI 69 = 440 Hz
    let base_midi = 60 + root_semitone; // root in octave 4
    let mut freqs = Vec::new();
    for octave_offset in 0..2 {
        for &interval in &intervals {
            let midi = base_midi + octave_offset * 12 + interval;
            let freq = 440.0 * 2.0_f32.powf((midi as f32 - 69.0) / 12.0);
            freqs.push(freq);
        }
    }
    freqs
}
